crawl/crawl

crawl-ref/source/player.cc
The effect of removing this cap is very small -- few games hit it and
not by much when they do.
<chequers> !lg * te current / ev>54
<Sequell> 5/5906 games for * (te current): N=5/5906 (0.08%)
<chequers> !lg * mf current / ev>49
<Sequell> 6/7832 games for * (mf current): N=6/7832 (0.08%)
<chequers> !lg * te current ev>54 s=ev
<Sequell> 5 games for * (te current ev>54): 2x 55, 2x 59, 71
<chequers> !lg * mf current ev>49 s=ev
<Sequell> 6 games for * (mf current ev>49): 3x 51, 58, 59, 56
=> Remove the +9 bonus EV cap for Mf & Te.

crawl-ref/source/spl-summoning.cc
This isn't a change in behavior; just a small simplification, and me dipping my toe in the water of contributing.
The old code summoned hostile snakes for cursed missiles, but there's no such
thing.
=> Sticks to snakes are always friendly

crawl-ref/source/itemprop.cc
These items used to prevent unequipping other items, but 0.14 changed that.
=> Xom is no longer extra amused by cursed cloaks and gloves

crawl-ref/source/webserver/game_data/static/map_knowledge.js, crawl-ref/source/webserver/game_data/static/util.js
Replace an expensive object-lookup-by-array-key with a preallocated array and a numeric lookup. Huge improvement in performance on low-end clients such as a Raspberry Pi.
=> Javascript client performance improvement.

crawl-ref/source/dat/descript/gods.txt
As previously written, it sounded like whole-body binding affected
the size of skill boosts, in addition to the "bound in armour"
bondage levels for specific slot groups, when actually whole-body
binding only affects piety gain.
=> Reword description of Ashenzari skill boosts

crawl-ref/source/describe.cc, crawl-ref/source/fight.cc, crawl-ref/source/fight.h
Previously base & minimum delay was revealed to the player, which
required maths to make use of. Now the base delay is hidden and instead
is shown mindelay and the skill required to reach it.
For weapons that cannot reach mindelay (eg Dark Maul), the level shown
is 28, which I think is nice :).
This commit would break for any weapons that require an odd skill level
to reach mindelay, but I don't think any such weapons do/can exist.
=> Explicitly reveal mindelay skill to the player.

crawl-ref/source/itemprop.cc
These aren't used much right now since they overlap so closely with
GSCs. 16dam/-4acc, compared to 15/-1 for eveningstar/double sword,
22/-7 for GSC and 17/-4 for great mace. Delay remains unchanged.
=> Tweak GC/GSC base delays

crawl-ref/source/dat/des/altar/altar.des, crawl-ref/source/enum.h, crawl-ref/source/feature-data.h, crawl-ref/source/godprayer.cc, crawl-ref/source/religion.cc, crawl-ref/source/terrain.cc, crawl-ref/source/tilepick.cc, crawl-ref/source/wiz-you.cc
Random altars appearing occasionally on d:2 or d:3 that worship an
unknown god. Using one grants a small amount of initial piety.
Also forbids Demigods gaining religion in wizmode, to guard an assert.
Original code by 'bugzilla', see mantis#9454.
PR notes:
Changes from bugzilla's version:
* After praying at the altar once, change it to the god's real altar, to prevent god-scumming
* Add another des vault
* If you already worship the god the altar is for, gain a bit of free piety!
=> Add ecumenical altars (bugzilla)

crawl-ref/source/godabil.cc
It was supposed to be NdX, but was accidentally XdN.
Also tidied up a bit by removing some repetition, and moving related
variables closer together.
=> Fix Ru's apocalypse damage

crawl-ref/source/enum.h
Conceivably this could be an intentional misspelling, I dunno.
=> Fix a misspelled comment

crawl-ref/source/dat/des/portals/volcano.des
To be more in line with armour loot generation elsewhere. Note the
absence of animal skins.
PR note: Similar to what was done with volcano weapons, adjusted
the weights to be in line with normal item generation, keeping the
aux armour-body armour ratio the same (approx 1:8)
=> Update Volcano armour loot distribution

crawl-ref/source/spl-clouds.cc
Storm cloud is arguably not more powerful than even mid-tier clouds
(fire, cold) on this rod unless the enemy has a lot of AC. With low AC,
the damage is comparable with the trade-offs of a lack of consistency
and a lot of noise. Acid has a very good extra effect in corrosion and
few enemies resist it, so it's certainly better than storm - arguably
negative energy is as well, but there's at least the issue of rN+ being
more common here, and storm cloud seems too exotic to show up that
early.
PR note: As discussed in IRC, storm deals approx 4x the damage 1/4
of the time and makes a lot of noise with no extra effect.
=> Swap the weighting for storm cloud/acid cloud on the Rod of Clouds

crawl-ref/source/mon-gear.cc
Greater naga and naga warriors shared a weapon list made up of
generally inferior weapons. This made sense for greater nagas
since they have Haste Self and offensive conjurations, but warriors 
shouldn't have an inferior weapon list to nagas and naga mages.
Swapping the weapon lists for naga mages and naga warriors.
This is a buff to warriors and will make Snake more dangerous, but
naga warriors are slow and there is no reason people shouldn't be 
cautious of them anyway.
=> Swap weapon lists for naga mages and naga warriors

crawl-ref/source/mon-gear.cc
There are already lines in the existing code that allow warmongers to 
spawn with shields. However, warmongers currently have guaranteed 
launchers at spawn (possibly due to the interaction with Grand Avatar,
which has since been removed). Since launchers preclude shields, 
reducing the chance of generating a launcher to one in three will allow 
shield generation.
=> Allow demonspawn warmongers to spawn with shields

crawl-ref/source/melee_attack.cc
Instead, they should be shoved backwards or something.
=> Don't say that flying things 'stumble backwards' when trampled

crawl-ref/source/item_use.cc
If you are half way through a recital, then abort reading a scroll with
monsters in sight with the blurry vision mutation, your recital is
interrupted unnecessarily.
=> Don't interrupt recitals if reading was aborted

crawl-ref/source/main.cc, crawl-ref/source/stairs.cc
If you don't have enough runes to enter a rune-locked branch, your turn
ends since the check is done after the staircase delay.
=> Don't end turn when not meeting runelock criteria

crawl-ref/source/cloud.cc, crawl-ref/source/dat/des/test/suite.des, crawl-ref/source/mon-movetarget.cc, crawl-ref/source/monster.cc, crawl-ref/source/monster.h
Fixes bugs involving monster movement near clouds. Wandering monsters no longer path into clouds. Intelligent monsters want more HP before entering a damaging cloud; in other words, friendly monsters are less likely to do walk into a friendly cloud & die.
https://crawl.develz.org/mantis/view.php?id=2980
https://crawl.develz.org/mantis/view.php?id=9759
=> make monsters have better self-preservation around clouds

crawl-ref/source/godwrath.cc
The old message could be confused with exhaustion status effect.
=> Update god wrath slow message

crawl-ref/source/religion.cc
When you join Ashenzari, scrolls of remove curse are identified but the player isn't notified about it. This change prints the usual identification message for that event: "f - a scroll of remove curse".
=> Tell the player when Ash identifies ?RC for you

crawl-ref/source/attack.cc
Currently, species that start with claws get extra unarmed accuracy at all times, including forms that suppress claws. Species that get claws later do not get this bonus. This is inconsistent with how all other mutations behave, so just give the bonus if the player has claws and their form does not suppress them.
=> Don't give species with innate claws an extra bonus to unarmed

crawl-ref/source/travel.cc
When crawl asks me "do you really want to use those stairs" and I hit escape, that should mean "no", not "yes".
=> Change the 'safe option' for using unorthodox stairs to 'no'

crawl-ref/source/dat/des/arrival/simple.des
ldierk_water_garden placed toadstools, bushes, plants, and trees in four
corners.
A player unfamiliar with the nuances of stationary plant monsters may
choose to attack the plant or bush corner, and if this character has no
weapon or using untrained UC this will take hundreds of turns.
Change it to spawn trees in 3 corners with one toadstool exit, which the
dungeon builder flip/rotate will randomize.
=> Tweak an arrival vault

crawl-ref/source/view.cc
This allows magic-mapped branches to be displayed in the dungeon
overview window and to be set as autotravel destinations.  The new Xv
behavior allows the specific branch to be determined already, so no
additional information is leaked by this change.
=> Note branch staircases when revealed with magic mapping

crawl-ref/source/describe.cc
To avoid reusing "experienced" for a different level bracket than
it was previously.
=> Update another xl_rank_name

crawl-ref/source/godwrath.cc, crawl-ref/source/mutation-data.h
Causing noise is pretty poor wrath, so instead of choosing that wrath
1/3 of the time, do it 50% of the time before the other two wrath types.
Note: this commit does not make Qaz wrath as dangerous as it should be.
=> Upgrade Qaz wrath.

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc, crawl-ref/source/main.cc, crawl-ref/source/options.h
I've had some close calls accidentally using a hatch that I thought was a stair.
=> Add rc option to prompt before using escape hatches

crawl-ref/source/newgame.cc
At present, answering the "Do you want to play this combination?" with
anything besides 'n', 'q', or Esc (interpreted as 'q') is interpreted as
'y'.  This change allows the player to re-press the key that meant "give
me a random combination" to do it again.
=> Interpret '!', '#', and Tab as "re-roll the random character"

crawl-ref/source/show.cc, crawl-ref/source/show.h, crawl-ref/source/view.cc
Toggle (m)onsters, (p)layer, (i)tems, and (c)louds visibility.
If you use only the '|' key, the functionality is exactly the same as
the original "show terrain".  However, you may now toggle certain layers
back on and that configuration will be remembered for the next time you
press '|'.
=> Allow selection of visible layers with '|'.

crawl-ref/source/itemname.cc, crawl-ref/source/potion.cc
Allow players to heal rot even with no device heal mutation. All of the other statuses are fixed by potions of curing even with no device heal, so fix this as well. Also let players use potions of heal wounds to heal rot, since they heal rot in the same way as curing.
=> Fix for issues related to no-device-heal + rot.

crawl-ref/source/book-data.h, crawl-ref/source/spl-data.h
With the removal of cTele, controlled blinking (both scroll and spell)
has become much more powerful and abusable in endgame areas that were
formerly -cTele. While the scrolls are at least limited in quantity, the
spell has no deterrent other than a middling amount of magic contamination.
Disjunction isn't used very often as it fills a similar purpose to
Controlled Blink while being harder to get castable. With CBlink at level 8,
it should see more use by players as they share the same book.
PR note: This was discussed some in IRC following cTele removal. The
issue of reworking/replacing the spell didn't reach a solid consensus,
so I propose this for 0.17 in hopes that it will be better addressed later
in development.
=> Make Controlled Blink a level 8 spell

crawl-ref/source/butcher.cc
This message triggers when you have butchering set to NEVER_CONFIRM and your god forbids butchering. It used to simply say "There isn't anything suitable to butcher here." which for a bit I thought was a bug... This message makes it clear it's a god restriction.
=> Improve message on refusing to butcher under Zin

crawl-ref/source/religion.cc
Went missing in 78de33285ae52079f3091dc8b233310c3a94a2bb.
=> Add back space in Trog ability message

crawl-ref/source/actor.cc, crawl-ref/source/actor.h, crawl-ref/source/beam.cc, crawl-ref/source/chardump.cc, crawl-ref/source/enum.h, crawl-ref/source/evoke.cc, crawl-ref/source/food.cc, crawl-ref/source/melee_attack.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/ranged_attack.cc, crawl-ref/source/throw.cc
Armour types
Dodged, Phased, or Deflected attacks
Blocked and Reflected attacks
Add tracking of auxillary attacks.
Rework count_action() to have a standard way to store auxillary information instead
of doing manual bit shifting.
=> Add tracking for defensive actions including:

crawl-ref/source/monster.cc
If asserts are not switched on during compilation, these methods are not
called, resulting in strange behaviour in-game (mobs don't follow the
player downstairs)
=> Removed important methods from within ASSERTs

crawl-ref/source/dat/des/portals/trove.des
Troves shouldn't ask for totally race-useless items, and that includes cMut for ghouls.
=> Don't ask ghouls for potions of cMut (celerity)

crawl-ref/source/mon-cast.cc
http://i.imgur.com/ShBaYnW.png
[dam=139;tdam=139] Senshi the Bludgeoner (L12 GrMo of Nemelex Xobeh),
blasted by Ohae the pandemonium lord (Shatter) (summoned
by the player character) on Lair:4 on 2015-11-19 15:57:16,
with 19475 points after 17935 turns and 0:44:58.
=> Friendly monsters shouldn't cast shatter.

crawl-ref/source/dat/descript/items.txt, crawl-ref/source/player.cc
Amulets and TLA increased regeneration (both a different amount) while
other artifacts with Regen+ did not. It wasn't a very noticable
tradeoff.
=> Remove increased metabolism from some regen items.

crawl-ref/source/evoke.cc, crawl-ref/source/spl-summoning.cc
Tweak the distributions on both items so they don't share any common monsters, and try to make both items more unique from each other.
This is done by giving the rod more killer bees and scorpions, and the sack worker and soldier ants instead of killer bees/scorpions/giant cockroaches. There is a higher proportion of worker ants to soldier ants than there was of the two chaff monsters to killer bees, and more spiders overall (their numbers scale up faster in the 6-15 evo range)
Rod of the swarm loses worker ants and 2/3 of its wasps (af_para). Also worms as they don't feel sufficiently swarmy. River rats were added at weight 2 to replace some of the variety lost.
=> Differentiate sack of spiders and rod of the swarm

crawl-ref/source/ghost.cc
Make unusual (for the player) brands more common, and weaker brands less
common.
Not tied to my lists of "strong" and "weak" brands at all, if people want to dispute my categorisation :P I just like the idea of making certain brands more and less common.
=> Tweak panlord brand distribution.

crawl-ref/source/dat/des/altar/overflow.des
1)  Death Squad: high evo !apt band takes down filthy low evo !apt brute.
2/3 chance of a wand with 0 charges (occasionally will spawn a kobold with a wand with 1 charge)
3/10 chance of a troll corpse (early troll hide chance)
Only low-level wands will spawn (frost, flame, m. darts)
A dash of blood was sparingly used for thematic effect.
The walls vary in material, somewhat referencing the current blinking P altar.
2) Dig!
a wand of digging with a single charge with a transparent rock wall that hides a P altar.
I wasn't sure if this was against the rules for an overflow vault, but seems like the player has a very clear choice on whether to use the wand to get to the altar, or take it (and recharge it the hard way later).
3) Pakellas's Ersatz Instruments!
90% basic wands with 15 charges …
=> A trio of Pakellas Overflow Altar Vaults

crawl-ref/source/mon-poly.cc
This could have some side effects in non-slimify polymorphing, but it seems to work okay: you still can't use /poly on derived undead, and slimify works on skeleton/zombie/simulacrum but not on spectral things.
=> Don't make buggy monsters on slimifying derived undead (Bamboomancer)

crawl-ref/source/player.cc
Gargoyles can't cast Statue Form anymore.
=> Remove special case for Gargoyles in Statue Form.

crawl-ref/source/godabil.cc
Maybe the rarer spellbooks were bigger? Seems like a strange way to scale the duration- especially since I don't think anything mentions it.
This change should make the effect ever so slightly better on average with a slightly lower topend.
=> Burn Spellbooks no longer factors rarity into cloud duration.

crawl-ref/source/dat/dlua/ziggurat.lua
[regret-index says:]
Filling zig floors entirely pretty quickly over additional zigs does
establish a very high tier of difficulty for ziggurats, but it also
thoroughly centralizes approaches and character builds towards mass
conjurations after the first few.  With the excess in-place being extra
visible with ziggurat figurines, easily reaching the hard monster cap
easily at seven to ten ziggurats, it seems appropiate to revise the
ziggurat stacking difficulty curve.
On a set-by-set basis, through tiered linear weighting, all ziggurat
monster sets now scale with ziggurat completion, spawning much less of
the weaker flavour spawns and much more of the high level spawns. Said
scaling mostly reach asymptotic points that differ based on the vague
preservation of first-zig set balance and the …
=> Zig stacking: slow down floor-filling, scale sets instead

crawl-ref/source/decks.cc
Currently, Nemelex worshipers get a card power bonus based on Piety, but
plain decks can NEVER be upgraded past level 0, making this bonus 100%
worthless for plain decks.
While there are more serious criticisms of the current Nemelex
implementation, it seems odd that the God of Decks doesn't provide any
bonus at all to plain decks (besides gifting them a bunch).
This update provides a very small chance for plain decks to be upgraded
to level 1.  This is roughly 1/2 the chance of an ornate deck to be
upgraded (remember that plain decks do not get the +150 bonus to power).
=> Sometimes upgrade plain decks for Nem worshipers

crawl-ref/source/dat/des/portals/trove.des
To account for the potion being ~50% more common, change fixed cost of 2
to 1+d3.
=> Adjust cure mutation trove entry fee

crawl-ref/source/webserver/game_data/static/monster_list.js
There were some issues with #209.
* Remove existing health classes when a monster's health changes
* Hide the span when it gets reused for a different monster
* Hide the span when another monster of the same type shows up
=> Some fixes for monster health in webtiles with tile_display_mode = glyphs

crawl-ref/source/wiz-item.cc
This code was doubly wrong:
* It should have been end() rather than rend() to modify the end of the string. (rend() is reverse end, which is actually the beginning.)
* end() points *past* the end of the string and dereferencing it is undefined behavior. We want the last character.
=> Fix abort when tweaking artefacts in wizmode

crawl-ref/source/art-data.txt, crawl-ref/source/art-func.h, crawl-ref/source/dat/descript/unrand.txt, crawl-ref/source/goditem.cc
The formula for disarming success has been changed and it is now based
on target HD. Disarming should be nominally easier to pull off.
Enchantment has been improved from +5 to +7. (was +10 pre-disarm)
There is now a chance when disarming to deal 18-35 (average 26.5)
non-elemental damage. This is akin to having a powerful flat damage
brand versus monsters wielding a weapon, but it will only trigger while
disarming.
TSO followers are still allowed to wield the weapon, but they won't use
the disarm feature.
PR notes: This seemed more interesting than just giving it +10 slay again.
The idea behind the attack is a disarmed monster is probably going to
be off-balance or trip/stumble, etc. so he's briefly vulnerable to your stabber
persona. Damage is a bit less than 2 elec brands, which seems to …
=> Enhance and expand upon the captain's cutlass

crawl-ref/source/shopping.cc
By 20%.
Strategic consumables should be more expensive than tactical ones, and the cost to fix a mistake/roulette should be high, but the old price is still too high for their rarity.
=> Reduce !cure mutation shop price

crawl-ref/source/behold.cc, crawl-ref/source/fearmonger.cc, crawl-ref/source/player.h, crawl-ref/source/shout.cc
It's a spoilery mechanic which encourages carting around mostly-useless
items (?noise) through a single branch of the game.
=> Don't let noise break mesmerisation.

crawl-ref/source/attack.cc, crawl-ref/source/beam.cc, crawl-ref/source/cloud.cc, crawl-ref/source/godpassive.cc, crawl-ref/source/melee_attack.cc, crawl-ref/source/ouch.cc, crawl-ref/source/player-reacts.cc, crawl-ref/source/player.cc, crawl-ref/source/ranged_attack.cc, crawl-ref/source/spl-damage.cc
This started as an attempt to add expose_to_element back into beam.cc so that Qazlal characters properly adapt in response to spells; it spiraled out of control due to consequences for other aspects of exposure to elements.  The PR will have two main effects: (i) cause Qazlal elemental adaptations to trigger (hopefully properly) on all appropriate spells, and (ii) cause cold-blooded players to be slowed properly on all appropriate spells.  Neither of these were working correctly.
This also eliminates the call to melt player enchantments from expose_to_element: it is called from elsewhere and wasn't working properly in any case (it expects damage, not "strength").  However, this call may have been doing some token melting in special cases (token in the sense that it wouldn't have a real …
=> fix for expose_to_element not being called properly (10293)

crawl-ref/source/attack.cc
STR = 9,10,11 would not pass either if statement, providing no appreciable benefit to damage scaling for going from 9 to 11 strength. This was a classic inclusive/exclusive range if statement bug.
=> Tightened the 0 bonus/penalty range for STR.

crawl-ref/docs/develop/coding_conventions.txt
PleasingFungus said something to this effect in IRC, and it seems a useful "rule" to have defined in the coding conventions.
=> commenting convention: don't comment out code

crawl-ref/source/mutation-data.h
- Consistently end the sentence, then put the effect in parens
- Did not add -rElec since it's not permanent and has a status light
- (Stealth, -foe acc) should be rephrased in its entirety, not touching
- others such as e.g. (Clar) and (*Rage) are probably not needed
Oh yeah, and remove two messages for nonexistent levels of Eyesight.
Those went extinct approximately the same time as Sludge Dwarves :(
=> Show more mutation effects more clearly on `A` screen

crawl-ref/source/branch-data.h, crawl-ref/source/branch.h, crawl-ref/source/dungeon.cc
`>` placed at branch ends, and `<` at branch entrances, used to be deleted
because those features aren't legal in those places. This could lead to
players being trapped, eg if an 'island' vault with a hatch down
generated on Lair:8. Now, we replace any vault-mandated escape hatches
with whatever escape feature is appropriate for the current branch/floor.
Could use some review, particularly from @neilmoore, who suggested the implementation some time ago but I never got around to it.
=> Make sure vault-produced escape hatches aren't erased

crawl-ref/source/job-data.h
It's (much) more common to build artificers as heavy-armour meleedudes
than spellcasters, so tweak artificer stats from 3,4,5 to 4,3,5.
To be honest, I could also see 5,2,5, or 6,2,4, but those seem more controversial. I'll happily update the patch if either of those are preferred though.
=> Tweak Artificer starting stats.

crawl-ref/source/describe-spells.cc, crawl-ref/source/describe.cc
There's one catch with this implementation: some natural abilities are affected by silence (howler monkeys, etc). Unfortunately, you can't readily access the spell slot flags through monster_info, and adding support seems quite difficult, so I just mark natural spells as "maybe" affected by silence 😒
=> Add silence/antimagic spell vulnerability info to x-v.

crawl-ref/source/dat/des/portals/wizlab.des
```< Sequell> Command: !wizrank => !lm * br.enter=wizlab s=regexp_replace(milestone, "entered ((the_hall_of_|the_chambers_of_)([_a-z]+(?=the_)))?(.*)\.", "\2\4") milestone!~~ering?ya|cekugob|mortuary|a_wizard|upun's_lair|cloud_mage's_chambers title:"WizLab ranking ($*)" $* / lg:br=wizlab o=%```
The above will still be needed for historical games, of course, but it should simplify matters going forward.
=> Remove unique names from two wizlab milestones.

crawl-ref/source/mutation.cc
The display of most such mutations was addressed in
7a8084aeb01337ba140cbf3eea07ba489de9968f
but this one lives in a different file and was overlooked.
=> Be consistent about Gr +AC mutation effect on `A`, too

crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/mon-cast.cc, crawl-ref/source/mon-spell.h
Double their cast rate, make legendary destruction cast two spells at a
time, and shorten the candidate spell list to fireball/iceblast/ghostly
fireball.
=> Buff Blood Saints (regret-index).

crawl-ref/source/dat/descript/status.txt, crawl-ref/source/duration-data.h
There's MR+ which increases MR by one pip,
there's MR++ which increases MR by two pips,
there's an MR- mutation lowering MR by one pip,
there's an MR-- mutation lowering MR by two pips,
and there's the MR- status light which … halves your MR.
No reason not to just tell players what is happening here, I think.
=> Don't mislabel DUR_LOWERED_MR status as MR- in HUD

crawl-ref/source/chardump.cc
Action count and skill tables use this style for their headers already,
as did the optional `turns_by_place` and `kills_by_place`.
=> Consistent table header style for chardump notes section

crawl-ref/source/l_you.cc
These had been out of commission since the removal of ziggurat entry fees
(which were accompanied by adding inaccessible ziggurats to shopping list)
in 07949ec7b9c0b9583012be218f9b887257a10cd9 .
=> Remove some unused dlua

crawl-ref/source/l_item.cc, crawl-ref/source/shopping.cc, crawl-ref/source/shopping.h
Rather similar to `items.shop_inventory()` for exposing a shop's stock as lua table, all in all.
(Except it works everywhere, not just when on the same tile as a shop.)
Said shop table gets a third return value per item as well, indicating whether the item in question
has been added to the shopping list.
=> Lua: Expose shopping list as `items.shopping_list()`

crawl-ref/source/dat/des/branches/pan.des
The second half of the comment "Four exits are given, with one placed randomly and the others in a room safe to teleport into." implies the player has control over his/her teleport destination, which is not possible after the removal of cTele.
=> Remove reference to cTele

crawl-ref/source/files.cc
Added a check to see if monster was incapacitated just as you started to ascend or descend stairs.
Testing done in wizmode with allies and monsters.
1. Monsters don't follow if incapacitated. 
2. Follow when they are not incapacitated.
3. They're still present when I go back.
=> FIX for bug#0010518

crawl-ref/source/dat/descript/monsters.txt
Mantis Bug 10638  https://crawl.develz.org/mantis/view.php?id=10638
Repeated word in Halazid Warlock description ("night night")
Fixed to remove extraneous repeated night.
=> Bug #10638: Halazid Warlock description typo

crawl-ref/source/actor.cc
Affects Aizul, satyrs, dream sheep, sleeping needles, hibernation, one
Hell miscast effect, and Dithmenos wrath.
With the removal of "Clarity, the only way for players to gain Clarity
is via Ashenzari (where the buff wouldn't hurt), a mutation (rare!), or
the autumn katana (very rare!), so this seems fine to do.
=> Make Clarity resist sleep

crawl-ref/source/fineff.cc
Doesn't cleanly handle the case where the monster is killed while
reflecting damage (since the monster no longer exists to have its name
called), but fixing that apparently may go on to cause more issues with
messaging.
=> Clarify which monster reflects damage (3774)

crawl-ref/source/feature-data.h
Turns out I forgot to edit the entry in feature-data.h, so it wasn't
showing the portal description at all!
=> Fix Desolation portal description

crawl-ref/source/Makefile
In NixOS several fonts are symlinked into the fonts directory. This patch fixes their discovery.
=> Follow symlinks when searching for fonts

crawl-ref/source/l_item.cc
Note that the absence of an inscription returns an empty string (since this is how it's represented in `item_def`). Not sure if it would be better to return `nil` to distinguish the absence of an inscription from an empty inscription.
This is my first time making a pull request, so please let me know if I've screwed up.
=> Lua: Expose inscriptions as item property

crawl-ref/source/items.cc
Having to pick up the manual to see what it'd train was annoying (especially with a full inventory) and
inconsistent with current book behavior.
Since you have to actually reach the tile that the manual resides on, the 'mystery' is still preserved.
=> Auto-ID manuals the player steps on

crawl-ref/source/enum.h, crawl-ref/source/externs.h, crawl-ref/source/store.cc, crawl-ref/source/store.h
Compiles without warnings and seems to work fine (I can save/load games, tweak artefact props, etc). 
But it would be a pretty big deal if there were a mistake in this commit, so I'd like it reviewed by someone before I merge it.
=> Make CrawlHashMap inherit from std::map

crawl-ref/source/item_use.cc
Previously, the text shown when an object was identified was always grey. Now, for example, the text identifying a scroll of random uselessness will be dark gray, and when following Chei a potion of haste will be shown in red.
=> Color the text when an object is identified by a scroll of identify.

crawl-ref/source/food.cc
Issue 10657 is about prompting before eating mutagenic chunks as a Zin worshiper, but it seems like the classes of food characterized by "is_bad_food" should prompt before eating regardless of god.
=> Prompt for confirmation before eating mutagenic/forbidden/noxious food (10657)

crawl-ref/source/mon-ench.cc, crawl-ref/source/mutation.cc
Don't despawn demonic guardian based on tension, instead make them
behave more like normal summons. This changes the life timer enchantment
from a 'guaranteed minimum' duration to 'summon length' duration --
double it in recompense.
Finally, lower the tension requirements to spawn a guardian at level 1 &
2.
=> Simplify demonic guardian spawning/despawning

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc, crawl-ref/source/l_option.cc, crawl-ref/source/libunix.cc, crawl-ref/source/options.h
Includes:
- A fix for a failsafe colour problem (amalloy)
- Fixes and tweaks for the options guide
- Removal of the no_dark_brand option (|amethyst)
=> Terminal rendering option fixes (for PR #377)

crawl-ref/source/godpassive.cc
The messages generated by burning/freezing flora made resting in certain
places (especially lair) quite noisy/tedious.
Hopefully doesn't prevent any cool tech?
=> Don't create Qaz clouds over firewood

crawl-ref/source/tilereg-inv.cc
Cards are now evoked like normal miscellany type objects, so
there shouldn't be a special case to say left clicking cards
will "wield" them.
=> Remove special case for tiles tool tip for cards (fixes #391)

crawl-ref/source/Makefile
The Makefile was initializing prefix and chroot_prefix to empty
strings, but never actually wrote anything "useful" to these
variables.  The builder is meant to be able to specify prefix
(per the examples in the Typical parameters notes at the top
of the Makefile).  chroot_prefix is also probably meant to be
specified similarly, though it seems to be an undocumented
option.
Fixes #412
=> Prevent Makefile from blowing away the prefix and chroot_prefix

crawl-ref/source/dat/clua/stash.lua
Warding was removed in 0.18, but the description of the staff of summoning still mentions the "{Ward}" stash search prefix.
=> Update the description of the staff of summoning

crawl-ref/settings/colemak_command_keys.txt
As far as I understood this commands for doors are obsolete now, so I removed it to stop crawl complaining about it every time.
=> colemak keyboard binding fixed

crawl-ref/source/dat/database/help.txt, crawl-ref/source/item-name.cc
In the "Known Items" menu, render useless items in dark grey instead of the default light grey used for other non-overridden items. Useful when configuring manual autopickup overrides for a randomly chosen character as it reminds me to e.g., not enable javelin pickup if I'm playing a kobold.
=> Render useless items in dark grey in Known Items menu

crawl-ref/source/spl-clouds.cc
"Roar" in Crawl is usually a loud noise, typically one issued by a beast or a Trog-worshipper.
Conjure flame, however, is quite a quiet spell and cautious (but inexperienced) players might avoid casting it for fear of a loud "roaring" noise if they fail to check the full spell details in the z ? ! menu. The description of the sound could stand to be toned down a little.
Perhaps "The fire ignites dangerously||menacingly!" would retain some of the original phrase's feeling of power and violence, at the risk of throwing around unnecessary adverbs!
Uncertain whether "The fire roars!" was being called by other sources than Conjure Flame, sources which perhaps **are** loud enough to earn a "roar".
=> reduce intensity of conjure flame verb

crawl-ref/source/items.cc, crawl-ref/source/items.h, crawl-ref/source/player.cc
Wands can be trivially type-identified by picking them up, and it's rather annoying when encountering a wand with a full inventory to figure out the safest item to drop, pick up the wand, then immediately discard it and pick up the item again because it's a trash wand (e.g. random effects or flame outside early-game). Spellbooks are in the same boat and identify just by standing over them; this extends that behavior to wands.
=> Identify wands when the player steps on them.

crawl-ref/source/items.cc
So the wand-identification PR I just sent has an issue where if you have unknown wands set to not be auto-picked-up, they'll get scooped up anyway if you step on them because they stop being unknown and start being a new type. This fixes that by marking the revealed type as undesired as well (since if you're ignoring all unknown wands, you probably don't want the second wand of random effects either).
=> Hack to make unidentified wands respect auto-pickup settings

crawl-ref/source/item-name.cc
1. `is_useless_item()` checks for potion and ring of flight did not check for innate racial permaflight ability, only whether you were permaflying at the moment. (Hence, toggling permaflight on and off would change the perceived uselessness of these items.) Added missing `racial_permanent_flight()` check to these two cases.
2. `is_useless_item()` checks for scroll of fog and wand of clouds considered Still Winds to be a permanent condition rather than a temporary one. Added missing `temp` check to these two cases.
=> Several is_useless_item() fixes

crawl-ref/source/item-use.cc
In `wear_armour`, don't call get_armour_slot until we know it's an armour item.
Fixes crash issue 10940 introduced by #423.
=> Fix issue 10940 introduced by #423

crawl-ref/source/stash.cc
Previously, `god_id_item` was called only from a distance, and then only on the
top item of the stack, so items not at the top of the stack would not be id'd
when you move onto their square.  This fix ids the whole stack when you stand
on it if appropriate.  This may overcall `god_id_item` but I haven't spotted
any detrimental effects.  Addresses 10580, 10919.
=> Have ash id stacks when standing on them (10580)

crawl-ref/source/main.cc
This needs some vetting to make sure there aren't unintended side effects -- I've checked the other cases where you.turn_is_over is false and didn't spot any problems, but it is nonetheless a change in the input loop.
Commit message:
This specifically addresses 10314, where shoals wave/beach tiles weren't being
updated after temporal distortion.  Temporal distortion results in
`you.turn_is_over` being false at this point in the loop, but apparently
`viewwindow` needs to be called at this specific time to get the waves right.
For non-instantaneous actions, `viewwindow` is called as part of
`world_reacts`.
=> Ensure viewwindow is called in the input loop for instantaneous actions

crawl-ref/source/dat/des/portals/ossuary.des
They were after the player had dealt with (nearly) all monsters in the
portal, and the portal is small enough there's no real need to move them
earlier.
=> Remove alarm traps in ossuary_tomb_3

crawl-ref/docs/crawl_manual.rst, crawl-ref/docs/develop/levels/triggerables.txt, crawl-ref/source/dat/database/monspeak.txt, crawl-ref/source/describe-spells.cc, crawl-ref/source/hints.cc
Duplicated "to", for example:
"Select a spell to read its description or *to to* memorise it"
=> Fix a few typos in docs and source

crawl-ref/source/output.cc, crawl-ref/source/tileweb.cc, crawl-ref/source/webserver/game_data/static/player.js, crawl-ref/source/webserver/game_data/static/style.css, crawl-ref/source/webserver/game_data/templates/game.html
Refactors noise bar webtiles code to use custom attribute selectors.
Also:
- Change silencing to show as "Silenced" instead of "(Sil)"  (all interfaces)
- Prevent a leak of exact noise information outside of wizmode (webtiles)
- Changes Gozag money to be lightgray instead of gold based on feedback in IRC (missed this in the commit message but this is in  31f7f79).
=> Noisebar tweaks

crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/dat/descript/status.txt, crawl-ref/source/form-data.h, crawl-ref/source/transform.cc
Blade hands, statue form and dragon form all had base unarmed damage
that scaled with strength (and dexterity, for blade hands). Remove this
scaling and replace it with flat damage.
Naive damage comparison, using the average stats of winning transmuters
at various XLs:
* XL10 (17str, 20dex)
* XL15 (22str, 24dex)
* XL20 (25str, 25dex)
* XL27 (28str, 28dex)
Blade Hands (10% more at XL10, 20% less at XL27):
* XL10: Old: 20, New: 22
* XL15: Old: 23, New: 22
* XL20: Old: 25, New: 22
* XL27: Old: 27, New: 22
Statue Form (same at XL10, 20% less at XL27):
* XL10: Old: 12, New: 12
* XL15: Old: 13, New: 12
* XL20: Old: 14, New: 12
* XL27: Old: 15, New: 12
Dragon Form (40% more at XL10, same at XL27):
* XL10: Old: 23, New: 32
* XL15: Old: 27, New: 32
* XL20: Old: 29, New: 32
* XL27: Old: 31, New: 32
=> Simplify base UC damage for forms

crawl-ref/source/god-passive.cc
Wall jump attacks had an aliveness check on the attack part, but didn't have one when displaying the initial "attack from above" text.
=> Fix DEAD_MONSTER message prompt on wall jump

crawl-ref/source/main.cc, crawl-ref/source/place-info.cc, crawl-ref/source/player.cc, crawl-ref/source/tag-version.h, crawl-ref/source/tags.cc
Some games transferred from pre-0.19 to post-0.19a will then save with
desolation's place info incorrectly numbered as the global place slot,
triggering an assertion failure on load.  This patch loads these files
without crashing; it limits the time-frame of this fix with a new minor
tag.  No one who has tried has been able to duplicate the save file
corruption, though we have several saves that result from it, so the
root cause may return or still be present.
Fixes some saves found attached to 10696 and 10788.
=> Load saves where desolation is incorrectly global

crawl-ref/source/spl-goditem.cc
Cleans up the detect_items() method in spl-goditem.cc.  Include
mutations.h to specifically check for MUT_JELLY_GROWTH instead of implying
it if Ashenzari isn't the player's god, initialize map_radius with a
starting value of 0, and add some descriptive comments.
=> Clean up detect_items()

crawl-ref/source/god-passive.cc
Fix more hardcoded 27s found in ash_skill_boost(); replaced with
MAX_SKILL_LEVEL.
=> Fix more hardcoded 27s.

crawl-ref/source/item-use.cc, crawl-ref/source/monster.cc, crawl-ref/source/player-equip.cc
"You are too angry to draw your sword" is a ridiculous state to be in. Warnings surrounding intentional berserk stay in place as swapping to a proper weapon is a waste of precious berserk turns.
Also enables the same for ranged weapon-having monsters who get unintentionally berserked, in the interest of player-monster symmetry. Given that launchers are used by almost nothing in the places where moths of wrath spawn, I don't think this is a huge balance change.
=> Allow (un)wielding items while berserk

crawl-ref/source/stash.cc, crawl-ref/source/stash.h
This is a basic implementation of an idea from Siegurt [on tavern](https://crawl.develz.org/tavern/viewtopic.php?f=8&t=23274&p=309432#p309432) to show only the
closest copies of items when searching stashes. It does this only for floor items that aren't missiles. This implementation always does the filtering -- at present, there is no way to disable it.
I'm not sure if this is the ideal way to do it, and this version is probably missing some stuff, so feedback is welcome.
Here are some screenshots to give a sense for what this looks like, taken from an actual player save (XL23) I had around for debugging something else (though I had at some point done &|).  
edit: see below for updated screenshots
=> Filter distant duplicates in stash search (Siegurt)

crawl-ref/source/job-data.h, crawl-ref/source/newgame.cc
Some context may be found here: https://crawl.develz.org/tavern/viewtopic.php?f=8&t=23161
And the commit msg for the change: 
```
Distribute the weapon skill points to fighting (4), dodging (4), and
stealth (4). This results in Monks starting with the highest fighting and
dodging in the game, and tied for the highest stealth, but no weapon or
related skills.
Previous rationale for moving to a weapon choice start was that having such a
high skill investment into UC disallowed experimentation. But having weapon
choice results in Monks playing far too much like weaker Gladiators. This change
mirrors the Monks' saved-up piety: starting with high generalist fighting skills
is essentially saved up xp to be used toward a weapon of choice, once one is
taken from the floor or an enemy. Though many …
```
=> Rework monk start to be more generalist

crawl-ref/source/beam.cc, crawl-ref/source/player.cc, crawl-ref/source/timed-effects.cc
Removes the contamination from gaining and extending the Haste effect, as
well as the per-turn contamination gain (and prevention of contamination
dissipation) while Haste is ongoing.
While Haste was a spell (and to a lesser degree, as a wand), it made sense
to limit the amount of times Haste was allowed to be used per tactical
encounter, as it could effectively be used as many times as desired
throughout the game.  However, now that the only source of Haste are
potions and unreliable god effects where the player cannot necessarily
guarantee they will receive Haste (Potion Petition, calling a potion shop,
decks of escape, Xom), tactical limitation no longer seems necessary.
=> Remove contamination from Haste.

crawl-ref/source/dat/des/variable/the_grid.des
Clarified connectivity rules.
"Spiral mode" chance is now 25% (was 50%).
Safeguarded against running out of subvaults.
Removed the chance of randomly replacing walls with floor, because islands are bad.
Added new shapes, main vaults, and subvaults to go with them.
=> Revise and expand the_grid

crawl-ref/source/dat/descript/spells.txt
Removes the reference to contaminating the player from the Haste spell
description (it should be impossible for a monster to cast Haste on the
player anyway, but this should reduce confusion just in case).
=> Update Haste spell description.

crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-cast.h
Lots of consensus that something like this is a good idea -- replacing
these pre-dcss breakpoints has been under discussion since at least
2014. This version uses minmay's polynomial solution explained at:
https://crawl.develz.org/tavern/viewtopic.php?f=8&t=23414
The argument that swayed me to make a branch: "One great effect of
getting rid of chance_breaks is that spells transition from 100% to 99%
to 98% etc. etc. earlier, instead of staying at 100% for ages and then
quickly falling. A 99% fail spell is still useless but it makes it much
easier for unspoiled players to tell how close they are to getting it
castable, compared to seeing both level 5 and level 9 spells as 100%
fail."
I've done some quick checking but not careful checking, and have mixed
feelings about introducing doubles …
=> Replace spell success breakpoints with minmay's polynomial

crawl-ref/docs/keybind.txt, crawl-ref/settings/dvorak_command_keys.txt
Minor fix that removes some warnings when starting/resuming a game using the Dvorak keybindings.
Also removed references to `CMD_MAP_FIND_F` and `CMD_TOGGLE_FRIENDLY_PICKUP` from `keybind.txt`.
=> Fix Dvorak keyboard binding

crawl-ref/source/religion.cc
It's a bit of a pointless message for players that Oka doesn't think
need ammunition (since they will never recieve ammunition gifts), but
prevents the case where ammunition-needing players receive gifts before
the 5* message about receiving gifts.
=> Mention Oka ammo gifting when you reach 3*

crawl-ref/source/windowmanager-sdl.cc
I don't know if I'm the only one, but I find it very annoying that Crawl locks the screen saver. [Apparently](https://forums.libsdl.org/viewtopic.php?t=4672&sid=867766d41acba06758c5315edc5c8641) it's the default behaviour set by SDL.
I tried setting `SDL_HINT_VIDEO_ALLOW_SCREENSAVER` but it didn't work. Calling `SDL_EnableScreenSaver()` did.
=> SDL Tiles: Don't disable screen saver

crawl-ref/docs/template/apt-tmpl-wide.txt, crawl-ref/docs/template/apt-tmpl.txt, crawl-ref/source/util/gen-apt.pl
Since e2bf7478f97, `aptitudes.txt` displays an aptitude of `0` for skills that cannot be learned by a species, which is misleading/confusing. This commit fixes the document generation to display `--` instead.
```
...
Arm Ddg Sth Shd     Inv Evo        HP  MP Exp  MR
----------------------------------------------------------------------
Human              0   0  +1   0      +1   0       +0%   0  +1  +3
Barachi           +2  +1   0  +1      -1  +1       +0%   0   0  +3
Centaur           -3  -3  -4  -3      +1  -1      +10%   0  -1  +3
Demigod           -1  -1   0  -1      --  -1      +10%  +2  -2  +4
Demonspawn        -1  -1   0  -1      +3   0       +0%   0  -1  +3
Draconian         --  -1   0   0      +1   0      +10%   0  -1  +3
Black    --  -1   0   0      +1   0      +10%   0  -1  +3 …
```
=> Make aptitudes table display '--' instead of '0' for unusable skills

crawl-ref/source/beam.cc
As far as I can tell, the only thing that uses BEAM_BERSERK and is capable of affecting the player is BEAM_CHAOS, which in turn is only used by apocalypse crab breath, and only the actual breath attack, not the clouds. I don't see any reason for this attack to ignore clarity, especially since the clouds (which are handled elsewhere) respect clarity. Monsters don't seem to actually check clarity when berserking so that case is untouched.
=> Don't let apocalypse crab breath attacks ignore player clarity

crawl-ref/source/god-wrath.cc
Kiku wrath has a fun bit of code that only runs if the player is less than level 27. (Level 27 players always get tormented, lower level players are more likely to be tormented the higher level they are). This code causes a necromancy miscast, then has a 20% chance to cause a second one, or so the comment implies. It also has a 1/125 chance of causing three miscasts, a 1/500 chance of causing 4, a 1/2500 chance of causing 5, and so on. Assuming the random number generator is random anyway, which it isn't. Kiku probably shouldn't be able to just lower all of an ex-follower's skill levels to 0, or damage of their attributes by 100, or rot away their entire health bar in an instant, or drop twenty reapers on their head, or kill them outright from 300+ HP, or all of these at the same time …
=> Don't let Kiku wrath inflict infinite miscasts

crawl-ref/source/dat/des/portals/bazaar.des
This adds a medium-sized bazaar vault that places the player in an autumn forest (or, in 1 out of 4 cases, a rather dead one). Upon entering, the player has to follow a path that suddenly widens and leads to a clearing in the forest where a few secretive shopkeepers have settled down and are offering their wares. After a successful shopping trip, the player can resume their voyage to follow the path out of the forest and the bazaar.
This vault contains 3 to 4 normal shops (one is abandoned half the time) and one that is always abandoned.
Note: I don't know what type of bazaar vault is more useful at the moment (common or more rare ones), so I've taken 5 as a somewhat rare `WEIGHT`. I have in the meantime made antique shops more likely to appear to justify this. I guess it could arguably …
=> Add an autumn forest themed bazaar vault

crawl-ref/source/util/gen-apt.pl
Self-explanatory, since Mottled Draconians are no more in 0.20 and on.
This should close [bug 11120](https://crawl.develz.org/mantis/view.php?id=11120) on Mantis.
=> Remove Mottled Draconians from table of aptitudes

crawl-ref/source/mutation.cc, crawl-ref/source/player.cc
This is an attempt at fixing the issue mentioned in https://crawl.develz.org/mantis/view.php?id=11116. I found that teleportitis wasn't suppressed either. This change also removes the evokable Blink ability gained from the mutation when in tree form, but not the one you get from, say, jewellery. This should be in line with how mutation-suppression works in other cases, notably draconian breath (thanks amalloy).
The second commit corrects the general message you get when trying to use either blink or teleport (any source) while not being able to for some reason. Before, it would always say "You cannot teleport because ..."; now it distinguishes between blinking and teleporting by using the already present `blinking` flag.
=> Fully suppress the 'blink' and 'teleportitis' mutations when in tree form

crawl-ref/docs/crawl_manual.rst
account for the escape character by adding an extra space
=> Fix alignment of Items table in crawl_manual.rst

crawl-ref/docs/crawl_manual.rst
Ogres no longer have a particularly good aptitude with maces and
flails, as mentioned in the manual. This commit replaces that line
with a more up-to-date take on what melee options they find natural.
=> Remove manual's reference to Ogres' especially good maces aptitude

crawl-ref/source/externs.h, crawl-ref/source/travel.cc
Consider the following scenario:
```
######+##
@
```
When running (Shift-moving) east, the player will stop before the door in the wall. When moving through the Vaults, I encountered the following situation and noticed a different behaviour:
```
@
#
#
+#
#
#
```
When running SE, the player will just pass the door without stopping. This happens for any of the 4 diagonal directions.
This is due to the methods checking only the tiles to the left and the right relative to the movement direction. When moving horizontally or vertically, this does suffice. In the above example (and analogously for other diagonal movement) however, "left" means the directional vector `(1,0)`, and "right" is `(0,1)`. So when trying to find out whether the movement should stop, only the wall tiles are actually …
=> Stop diagonal running when encountering doors

crawl-ref/source/item-use.cc
Gnolls can't have their stats modified by items, so it makes no sense to
warn them about reaching stat zero if they equip/unequip items that change
their stats.
=> Don't warn for stat zero from changing items on Gnolls (11151)

crawl-ref/source/religion.cc
The messages for gaining attributes from initially joining Chei or gaining
piety were already squelched, but the message for losing attributes from
losing piety was not.
=> Squelch Chei 'lowering attributes' after piety loss for Gnolls (mibe)

crawl-ref/source/hints.cc
Fixes:
- Repeated "a"
- Missing `</w`, which broke coloring.
=> Fix various typos in jewellery hints (fixes #571)

crawl-ref/source/beam.cc, crawl-ref/source/beam.h, crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-damage.cc
See: https://crawl.develz.org/mantis/view.php?id=10969
Currently, not all fire spells are causing Dith to dish out
penance/wrath.
inner flame
ignite poison
bolt of magma
ignition
firestorm
Had to add some extra BEAMS to apply_beam_conducts() and then point
cast_ignition and cast_fire_storm to the same function.
Ignite_poison is handled similar to how SPELL_SWIFTNESS is handled for
the is_hasty conduct (check for the spell and send a DID_FIRE to
did_god_conduct).
=> Make Dith hate all fire spells (bepbepimjep, #10969)

crawl-ref/source/spl-book.cc, crawl-ref/source/spl-util.cc, crawl-ref/source/spl-util.h
See https://crawl.develz.org/mantis/view.php?id=11180
This issue was caused by: https://github.com/crawl/crawl/commit/175666845826aeb963ffe902c9405cd886483b7f
When refactoring the code in spl-book.cc to Gray out spells that the player is not able to learn (not enough spell levels or too low XL), the function, spell_highlight_by_utility, in spl-util.cc wasn't properly modified to handle being used by both the spell memorisation menu and the spell casting menu (which was the only thing that used it previously).
I thought of 2 options.
1. revert the refactoring. Move the check back to spl-book.cc.
2. modify spell_highlight_by_utility in spl-util.cc to accept an additional boolean argument indicating if a check against being able to memorise the spell is requested (similar to the existing …
=> Fix Incorrectly grayed-out spells in casting menu (#11180)

crawl-ref/docs/options_guide.txt, crawl-ref/source/cio.cc, crawl-ref/source/cio.h, crawl-ref/source/directn.cc, crawl-ref/source/initfile.cc, crawl-ref/source/options.h
A new setting is introduced called `use_modifier_prefix_keys` that
enables and disables '/' behaving as SHIFT and '*' as CTRL.
It's set to true by default.
=> Toggle setting for modifier prefix keys / and *

crawl-ref/source/mon-util.cc
A huge chunk of it is defending against `"_laughs_"` not being in monspeak.txt,
which is not a very likely scenario. Even if that did happen, the only
consequence of removing this extra logic is displaying a worse string
to the user (not a segfault or a machanics change).
Sending as a PR instead of committing directly since it sounded like geekosaur might disagree with my priorities, so here's a chance for someone to tell me not to merge it.
=> Simplify code for making mimics cackle

crawl-ref/source/glwrapper-ogl.cc, crawl-ref/source/macro.cc, crawl-ref/source/mon-info.cc, crawl-ref/source/player.cc, crawl-ref/source/tilereg-abl.cc, crawl-ref/source/tilereg-map.cc, crawl-ref/source/tilereg-menu.cc, crawl-ref/source/tilereg-text.cc, crawl-ref/source/tilesdl.cc
Mostly these were many-years-old TODOs that never got done,
or some debugging code meant to be toggled by editing the source.
The former are never going to get done, and the latter are doing
things the wrong way: they should use some debug variable, if they
are important toggles to keep. But I think they're not important, and
the authors of these debug options have moved on, so away goes the
dead code. If you miss any of these badly, feel free to add them back
in controlled by a flag.
I left in two `#if 0` clauses that looked like they might be valuable
someday:
- One in dbg-asrt.cc representing partial work towards a solution of
a difficult problem (better ASSERTs on Windows tiles) that someone
with more expertise in the right area could pick up someday.
- One in fontwrapper-ft.cc that …
=> Remove a bunch of #if 0 clauses

crawl-ref/source/ability.cc, crawl-ref/source/canned-message-type.h, crawl-ref/source/message.cc, crawl-ref/source/religion.cc, crawl-ref/source/religion.h, crawl-ref/source/tilereg-abl.cc
In https://crawl.develz.org/mantis/view.php?id=11203, UsaSatsui reports that when playing local tiles, you can use god abilities while under penance, provided that you click their icon rather than trying to use them through the (a) menu.
I fixed this by adding a `god_power_usable` function, and then referencing that from within the existing `_check_ability_possible` function, which is used by the tiles renderer to decide how to draw the ability as well as whether to activate it or print an error message when clicked.
I would welcome a style or functionality review before merging. I did test the change, and it appears to work, but of course there could be edge cases I'm not thinking of.
=> Don't let local-tiles players use god abilities under penance

crawl-ref/source/player.cc
See: https://crawl.develz.org/mantis/view.php?id=11104
Currently, self-haloing prevents !invis, even when umbraed.
The issue is, the msg to the player is vague and doesn't clarify that the reason the player can't go invisible at all is due to their weapon (EOS) or their Divine Halo (TSO or Wu Jian). Additionally, since the player is actually able to quaff !invis when non-self-haloed haloed (angels, sunshine, etc) + umbraed, it could be confusing and feel inconsistent. 
With this fix, the actual reason for preventing quaffing !invis is provided to the player.
I don't know if I'm using ASSERT appropriately, but my concern was a future halo source that wouldn't get properly handled by this message.  I'm assuming there may be a better way to do what I'm trying to do.
I also briefly considered …
=> Clarify failure message for quaffing !invis while haloed (Yermak, #11104)

crawl-ref/source/xom.cc
First contribution, please be gentle.
This is just a simple fix for something I noticed while playing a Xom character.
The pseudo miscast code just looked for anything in the cloak slot, and would display "Your cloak billows in an unfelt wind" even if you had a scarf equipped.
It seemed appropriate to change it so that you get a different message if you have a scarf. I initially chose "Your scarf is twisted by an unfelt wind", but changed it to "Your scarf briefly wraps itself around your head!" which I think is funnier.
I have compiled and tested that it works as intended.
=> Different messages for cloaks and scarves in _xom_pseudo_miscast

crawl-ref/source/player.cc
While waiting in an area if there are submerged enemies nearby ghoul hp does not regenerate. Occurs very often in swamp with swamp worms.
Mutation text in game states: You do not regenerate when monsters are visible.
Changed the mutation to ignore submerged enemies.
(Issue's: 0011199, 0011197 on Mantis.)
=> Ghoul HP regeneration near submerged enemies

crawl-ref/source/initfile.cc
Also, update other target checks in the #ifdef chain to check against
an appropriate TARGET_OS macro.
Needed for the readlink() call in _find_executable_path().
=> initfile.cc: Make sure unistd.h is included for Cygwin targets.

crawl-ref/docs/options_guide.txt, crawl-ref/source/command.cc, crawl-ref/source/fontwrapper-ft.cc, crawl-ref/source/fontwrapper-ft.h, crawl-ref/source/glwrapper-ogl.cc, crawl-ref/source/glwrapper-ogl.h, crawl-ref/source/glwrapper.h, crawl-ref/source/initfile.cc, crawl-ref/source/macro.cc, crawl-ref/source/menu.cc, crawl-ref/source/menu.h, crawl-ref/source/tilereg-dgn.cc, crawl-ref/source/tilereg-dgn.h, crawl-ref/source/tilereg-grid.cc, crawl-ref/source/tilereg-grid.h, crawl-ref/source/tilereg-inv.cc, crawl-ref/source/tilereg-map.cc, crawl-ref/source/tilereg-mon.cc, crawl-ref/source/tilereg-tab.cc, crawl-ref/source/tilereg-tab.h, crawl-ref/source/tilereg-text.cc, crawl-ref/source/tilereg.h, crawl-ref/source/tilesdl.cc, crawl-ref/source/tilesdl.h
General tiles UI streamlining:
- The gridded tabs in the sidebar are now flush with the right side of the window.
- The sidebar now has fixed width, and is always flush against the right side of the window.
- The main dungeon view expands to fill all remaining space, showing parts of partially visible tiles.
- The messages box sticks to the bottom of the screen.
There's some other fixes/enhancements as well. Some of them aren't really tiles related and should perhaps be in a separate PR...
=> Tiles, WIP: improve layout spacing on main dungeon view

crawl-ref/source/potion.cc
After f20264c8 ghouls get the "You cannot mutate at present." message when they try to quaff an identified potion of mutation. The "at present" part is not correct, since it's a permanent restriction.
This commit fixes that and a typo in the function's description.
=> Fix message displayed when Gh tries to quaff potion of mutation

crawl-ref/source/unwind.h, crawl-ref/source/wiz-you.cc
Currently, the player can't give their character the mutation resistance mutation in wizard mode. This fixes that, by adding a way to invalidate unwind_var's if they are no longer needed.
Also, first PR, nice to meet you.
=> Fix wizmode mutation resistance bug

crawl-ref/source/shout.cc
The previous message should be flushed regardless of whether the player
is berserk. The if-condition is causing the "Anything else - Cancel"
text to not appear.
=> Fix issue orders prompt when not berserk

crawl-ref/docs/crawl_manual.rst
According to this change https://github.com/crawl/crawl/pull/606, OoD spawns were removed. It would be right to remove them from crawl manual, too.
=> Remove reference to cleared levels from "Out of the depths" paragraph.

crawl-ref/source/tilereg-dgn.cc
This can happen when viewing the map with X and then panning.
=> Fix health minibars being drawn outside viewport

crawl-ref/source/tilesdl.cc
Earlier changes hardcoded the sidebar pixel width. This change now bases
the sidebar width mostly on the width of the stat HUD (dependent on its
font size), but with a minimum width in tiles as well.
There's also a bunch of dead code removal, and the way the stat HUD is
fitted into the sidebar is improved slightly as well.
=> Fix sidebar for large tile_font_stat_size

crawl-ref/source/stairs.cc, crawl-ref/source/travel.cc, crawl-ref/source/travel.h
This prevents auto-travel via staircases that lead to excluded areas,
and asks when traversing staircases into an excluded area. This works
only when the staircase's destination is known, and single-tile
exclusions on the destination staircase (indicating excluded travel in
the reverse direction) are ignored.
=> Don't (auto)travel via stairs into exclusions

crawl-ref/source/god-passive.cc, crawl-ref/source/god-passive.h, crawl-ref/source/main.cc
Used to only be cleared after a movement turn, instead of after any time consuming action, which made it able to kite enemies for longer.
=> Fix Whirlwind pin

crawl-ref/source/util/monster/monster-main.cc
This commit adds Cling to the list of flags displayed by the monster
utility.
The result looks like this:
=> Add Cling flag to monster info

crawl-ref/source/tilesdl.cc
The old continue statement never worked at all: its while loop had
(!key) as a condition, so it was equivalent to a break. I've moved
the check to the start of the MOUSEMOTION handling: there's no point
partially processing the event if there's another mouse motion event
right behind it. Also updated the comment text a little to clarify.
This fix makes targeting mode gloriously smooth when rapidly moving the
mouse; probably fixes lag in other places as well.
=> Fix tiles not properly processing mouse move events

crawl-ref/source/describe.cc, crawl-ref/source/describe.h, crawl-ref/source/tilereg-abl.cc
The workaround is a bit ugly - I had to use getchm() in order to let the
screen appear, and I'm not sure what show_as_menu() does.
This change is a response to [this Mantis bug report](https://crawl.develz.org/mantis/view.php?id=11231),
=> Fixed no ability description on R-click (#11231)

crawl-ref/source/files.cc, crawl-ref/source/files.h, crawl-ref/source/ghost.cc, crawl-ref/source/ghost.h, crawl-ref/source/mon-util.cc, crawl-ref/source/monster.cc, crawl-ref/source/ouch.cc, crawl-ref/source/tags.cc, crawl-ref/source/tags.h, crawl-ref/source/wiz-mon.cc
These are cleanup changes that are a precondition for doing pretty much any of the non-remove plans for ghosts, leading up the ability to load ghosts one by one.  They shouldn't change the status quo much if at all.
Would be helpful to get a sanity check on these changes, since the ghost save/load code is a bit of a mess, so I'm opening them as a PR.
=> Spooky cleanup

crawl-ref/source/mon-info.cc, crawl-ref/source/mon-info.h
The acting_part member was entirely unused. The i_ghost struct it is
part of is hashed to determine ghost appearances. While it is cleared
in the (monster_type, monster_type) constructor, it isn't cleared in
the (monster*, int) constructor, which seems to be used when monsters
move between cells.
=> Fix ghost doll cycling through parts

crawl-ref/source/tile-player-flags.h
See https://crawl.develz.org/mantis/view.php?id=11333
Crash was caused by a collision between this enum and a player doll part
tripping up an assertion.
No save incompatibility: player doll data is serialized in a manner
independently of this enum's value, and mcache_ghost entries have their
dolls reconstructed from species and equipment on creation.
=> Fix crash in player doll editor (GuideCritic, #11333)

crawl-ref/source/tilereg-menu.cc, crawl-ref/source/webserver/game_data/static/cell_renderer.js, crawl-ref/source/webserver/game_data/static/menu.js
This makes the ?/M menu much nicer when big uniques (e.g. hell lords)
are shown:
Fix included for both webtiles and local tiles
Edit: this fixes mantis issue https://crawl.develz.org/mantis/view.php?id=10213
=> Clip tall menu entry tiles to top section

crawl-ref/source/tiledgnbuf.cc
https://crawl.develz.org/mantis/view.php?id=11364
Nothing too serious; just a small addition to what was in the original zombie hands commit, changing the format to fit this function.
=> Display zombie hands icon for offline tiles users (MainiacJoe, #11364)

crawl-ref/source/dat/defaults/messages.txt
Timed portals have a default force more prompt for their initial
announcement message. The following messages do not cause additional
more prompts by default.
This commit makes the Desolation of Salt messages also behave like that.
Before this commit, the force_more was defined just as "distant wind".
Since "distant" is also used in many of the followup messages to
describe how far away the player is from the portal, this caused a lot
of additional "more" prompts for the player.
=> Do not force "more" prompts for (most) of the desolation of salt messages.

crawl-ref/source/beam.cc
See https://crawl.develz.org/mantis/view.php?id=10710
In the mantis item, PleasingFungus recommended just setting friend_info.power to a high number if a summoned monster targets its own summoner, so that's what this does.
I didn't know if 100 is the correct value, but it gets the job done. 
Boggarts will now last indefinitely since their minions will no longer pulverise them with bolts.
=> Discourage summoned creatures from Bolting their summoners (jwoodward48ss, #10710)

crawl-ref/source/mon-place.cc
They work on known or unknown traps without protest. The summoned thing sits on the teleporter or shaft, does its job, and does not reveal the trap if it isn't already known. (Though somewhat weird, this is already how they behaved with respect to zot traps.)
=> Allow Fulminant Prism and Lightning Spire to be cast on traps.

crawl-ref/source/crash.cc, crawl-ref/source/crash.h, crawl-ref/source/dbg-asrt.cc
*This is a PR because of the following question: can anyone spot some unintended consequences of changing the milestone this way?*
This includes the signal information in the crash milestone if there's
no assert message; before, the milestone would just be empty (which I
guess translates to "?"). It also will give the signal info on the first
line of the crash dump in these circumstances so that any non-windows
crash dump always has a cause on the first line.
=> If there's no assert message on crash, put signal into the noun

crawl-ref/source/ability.cc, crawl-ref/source/command.cc, crawl-ref/source/command.h, crawl-ref/source/describe.cc, crawl-ref/source/directn.cc, crawl-ref/source/invent.cc, crawl-ref/source/item-name.cc, crawl-ref/source/lookup-help.cc, crawl-ref/source/main.cc, crawl-ref/source/menu.cc, crawl-ref/source/menu.h, crawl-ref/source/newgame.cc, crawl-ref/source/shopping.cc, crawl-ref/source/spl-book.cc, crawl-ref/source/spl-cast.cc, crawl-ref/source/stash.cc, crawl-ref/source/tilereg-menu.cc, crawl-ref/source/tilereg-menu.h, crawl-ref/source/tilereg-popup.cc, crawl-ref/source/tilereg-popup.h, crawl-ref/source/tilesdl.cc, crawl-ref/source/webserver/game_data/static/menu.js, crawl-ref/source/wizard.cc
Changes include:
- removal of some unused interfaces
- consolidating rendering code: all menu rendering on local tiles is done in `tilereg-menu.cc`
- ?/ menu can now show the entire set of results (e.g. ?/M .* for all monsters): duplicated hotkeys are handled by never showing >52 items at once.
- two-column menus now wrap horizontally, and have separator lines between categories. This makes scrolling large menus (e.g. ?/m .*) much more intuitive, as the two columns move in tandem. Unfortunately it also makes scanning the menu slightly slower, especially when looking at the inventory menu, as the eye must move horizontally to look at all items of a particular type. To mitigate this, only one column will be used if there is sufficient screen space, which is usually the case on commonly used …
=> Menu refactor

crawl-ref/source/dat/des/branches/dis.des
Stealing runes is one of the most effective ways to do 15 runes currently, and one of the easiest runes to steal is the iron rune of dis_grunt. This PR makes that somewhat less easy to do by randomising the placement of Dispater and the iron rune, having it occasionally place in the central structure and an equal chance of placing in any one of the four corners, instead of just the two corners nearest to the entrance, as was previously the case. It also adds an extra Hell Sentinel to the vault, just to make everything symmetrical with the same number and difficulty of enemies in all the different arrangements.
(Also apparently I messed up the formatting of the commit comment, in that it should be 72-characters per line. Sorry about that, I don't know how to easily fix it.)
=> Randomise the placement of the rune in dis_grunt

crawl-ref/source/dat/descript/monsters.txt
"Its wool looks quite flammable" was a reference to dream sheep fires, a special-cased sticky flame mechanic. Because it was removed in 1d1b1003d6 and there are no other fire-related mechanics (dream sheep are not even vulnerable to fire) that bit of flavor is now misleading.
=> Update dream sheep description

crawl-ref/source/items.cc
Usually items are removed from the shopping list when they are put into
inventory. But after the introduction of spell library books no longer
take up inventory space, so the usual code path,
_put_item_in_inv() -> _got_item() -> cull_identical_items(),
no longer works for them.
=> Remove books from shopping list on pickup (Kipster)

crawl-ref/docs/develop/release/guide.txt
~~according to geekosaur, LTO doesn't do much even when it works correctly.~~ what geeko said is actually more complicated than that. bytecode something or other.
and according to me, cross compiling from Arch to Windows with LTO=y causes teleport scroll crashes!
=> don't recommend LTO for cross-compiling to windows

crawl-ref/source/item-prop.cc
Two fixes:
* Ash was giving warning messages for wands of clouds and iceblast
even though monsters don't use them.
* Ash wasn't warning the player about monsters carrying a wand of
enslavement, which can be used to confuse the player.
Also add missing wand of scattershot.
=> Improve Ashenzari's warnings for wands

crawl-ref/source/dat/clua/autofight.lua, crawl-ref/source/dat/clua/automagic.lua, crawl-ref/source/l-you.cc
Automagic wasn't working with LOS > 7. Setting LOS_RADIUS to 8 would have been enough, but exposing the actual LOS is harmless and nicer since it saves processing time for LOS < 8.
=> Expose current LOS in CLua, adjust autofight and automagic to use it

crawl-ref/source/mon-death.cc
The call to create the dragon scales item (which triggered the "You hear
a splash" message over deep water/lava) was before the message being
printed for "The scales are intact enough to be worn."
=> Remove the dragon scales creation message when item is to be destroyed by water/lava (Leszczynek, #11464)

crawl-ref/source/abyss.cc
Remove an unnecessary call to push_features_to_abyss from banished()
=> Code cleanup

crawl-ref/source/spl-damage.cc
The spell will have no effect so don't waste a turn and mp casting it.
=> Abort Vampiric Draining at full health

crawl-ref/source/dat/database/help.txt
It seems that "stick" tag is not available since commit 8afc29eb8.
=> fix help; "stick" tag is not available in current version

crawl-ref/source/describe.cc
Fixes a grammar mistake that affected Mennas' description. Previously read "Reciting Zin's laws will not affect he". Reworded to more closely resemble the other Zin's laws description.
=> Fix grammar in Zin's recite description (0011491)

crawl-ref/.gitignore, crawl-ref/source/webserver/config.py, crawl-ref/source/webserver/process_handler.py, crawl-ref/source/webserver/server.py, crawl-ref/source/webserver/static/scripts/chat.js, crawl-ref/source/webserver/static/scripts/client.js, crawl-ref/source/webserver/static/style.css, crawl-ref/source/webserver/templates/client.html, crawl-ref/source/webserver/userdb.py, crawl-ref/source/webserver/ws_handler.py
Implement some basic tileschat admin commands for the player, mainly aimed at dealing with spamming; this allows muting and unmuting, and will save mute lists on the server. This branch is ready for some review.
These changes may require a server admin to update code that's not usually updated on a new version (for the webtiles server).
=> Tileschat mute

crawl-ref/source/dat/des/branches/temple.des
Previously this would place erroneous floor tiles on some altars, because it was missing B in the FTILE assignment. This can be seen here:
=> Fix some floor tiles in pf_slime_end_temple

crawl-ref/source/actor.cc, crawl-ref/source/attack.cc, crawl-ref/source/attack.h
That function stood out like a splinter of hot garbage in a sore thumb while I was casually browsing the code base. Here's an equivalent replacement (as well as axes for duplicate code).
=> Refactor attack punctuation

crawl-ref/source/dat/descript/spells.txt
Injury Bond affects all allies in LOS, not just one.
=> Fix Injury Bond description

crawl-ref/source/spl-data.h
Iron Giants can throw monsters at the player protected by Sanctuary.
They can do up to 35 damage (random2(HD*2)) per throw without angering
Zin. Originally Throw Ally was a Robin-exclusive ability, so this was
not a problem.
Normally monsters don't use abilities that can harm the player, if the
player is in sanctuary. These checks are done in
mon-cast.cc:_ms_waste_of_time(). But for spell_harms_target()
Throw Ally is not a harmful ability. This is because the ability
doesn't have a SPFLAG_TARGETING_MASK flag (either SPFLAG_DIR_OR_TARGET
or SPFLAG_TARGET). Since Throw Ally is a smite-targeted ability, the
appropriate flag for it is SPFLAG_TARGET.
=> Make Iron Giants and other Throw Ally users obey Sanctuary

crawl-ref/source/dat/des/variable/ghost.des
Ghosts and monsters were dying to them. Replaced with black smoke, which
gives similar flavor but without the monster deaths.
=> Remove flame clouds from inner flame vault (jboons)

crawl-ref/source/fight.cc, crawl-ref/source/fight.h
Hello; this is my first pull request for an open-source project.  Forgive me if I am a little green...
So... the conditions which trigger this bug in the master branch of the main game:  
1.  You need multiple critters allied to the main character.
2.  You need a hostile monster with a cleaving weapon.
3.  You need the main character to be attacking with a 'long sword of distortion'.
The probability of producing the bug is quite low on the main branch, given that the riposte probability is 33%, and given that the probability of triggering a blink or a teleport with a distortion weapon is 25%.  I found that I needed to create a separate branch where these probabilities are 100% each.
=> Alcon cleave bugfix

crawl-ref/source/spl-miscast.cc
Previously zot traps would cast a friendly malign gateway when a non-player triggered the trap. This has been changed to always cast a hostile malign gateway.
Mantis issue: https://crawl.develz.org/mantis/view.php?id=11042
=> Fix zot traps casting friendly malign gateways (0011042)

crawl-ref/source/makeitem.cc
In commit 651d724, scarves were increased from being 1/6 to 1/4 of items generated for the cloak slot, however the actual increase in spawn rate for scarves was minimal, from 1/30 to 1/28 of all auxiliary slot armours generated, because what this commit actually did was reduce the spawn rate of cloaks from 5/30 to 3/28 by reducing the weight of cloaks.
It seems like an accident that this meant the total weight for this random_choose_weighted was not the 30 that a comment implied, and that the cloak slot items (cloaks and scarves combined) were made 2/3 as common as other auxiliary slot armours.
As a result, this commit buffs the spawn rate of cloaks and scarves to bring the overall spawn rate in line with that of other auxiliary armours, whilst maintaining the same 3:1 ratio of …
=> Make items for the cloak slot be equally common as other auxiliary armour slots again

crawl-ref/source/beam.cc, crawl-ref/source/losparam.cc
Chase down some edge case behavior with trees being opaque these days.
Removes one instance of trees getting OPC_HALF opacity, and modifies beam explosions to be blocked by them in a fashion consistent with how they modify LOS.
=> Lrd tree bug pr

crawl-ref/source/travel.cc
Prevents annotations for runed doors and transporters from stacking up.
=> Don't re-check forgotten map squares (10461)

crawl-ref/source/artefact.cc
Because Dithmenos doesn't have an anti-fire conduct any more, it is
no longer necessary to veto names like "...of Dithmenos's Generosity"
for randart flaming weapons.
=> Allow naming randart fiery weapons after Dithmenos

crawl-ref/source/dat/descript/ability.txt, crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/dat/descript/status.txt
This commit updates descriptions of all forms that can use wands since
7d43e34acb. It also fixes Fungus form's description: players in that
form can't wear hats or helmets (commit 7346924bb0).
=> Update descriptions of forms

crawl-ref/source/dat/database/FAQ.txt, crawl-ref/source/hints.cc
Multiple instances of 'p'raying still existed in FAQ and hints. These have been replaced with references to using > to pray rather than 'p'.
=> Replace outdated commands in FAQ and hints

crawl-ref/source/colour.cc, crawl-ref/source/colour.h
Make awoken forests an animated RED/LIGHTRED (angry trees) so that the
effect stands out to the player.
Old behavior is awoken forests are an animated GREEN/LIGHTGREEN
alternation. This sticks out a bit in swamp, where trees are
GREEN/BROWN, but is still not as dramatic as the berserk faces now in
tiles. It is also much less noticable outside of the swamp (some lair
ends in particular) where trees are GREEN/LIGHTGREEN to begin with.
=> Refactor elemental colours and recolour awoken forests in console.

crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-transloc.cc, crawl-ref/source/spl-transloc.h
This is inspired by the Tavern post made by Doesnt outlining the targeter's problems, which can be found here: https://crawl.develz.org/tavern/viewtopic.php?f=17&t=25497&p=329839&hilit=gell%27s#p329839
Previously, the formula used to calculate the targeted area was
completely different to that which the spell itself used, resulting in
the targeter blatantly lying to the player about the tiles which could
and could not be affected.
The current behaviour of Gell's Gravitas is entirely predictable based
on spell power, with no randomness involved, therefore the new targeter
is entirely in the darker yellow colour to indicate the certainty. The
power breakpoints are:
\>0 power: at radius 1 from the centre, the monster is pulled 1 tile;
\>0 power: at radius 2, the monster is pulled 1 tile; …
=> Fix the spell targeter for Gell's Gravitas

crawl-ref/source/dat/des/portals/wizlab.des
This wizlab previously had eight teleport closets, designed to be
terrariums of various shapeshifted monsters placed on display. They are
completely disconnected from the rest of the map and visible only
through their transparent walls.
This commit adds the no_tele_into flag to all tiles inside these eight
areas, to avoid the player teleporting/being teleported into these areas
and then having no way to get out of them. We use nine new symbols to
ensure that the content of the wizlab isn't changed at all.
If there is a better way to do the SUBST line, please let me know, as it seems really ugly. I tried `SUBST: -FGHIJKPR = .123467!W` and that didn't work.
=> Fix teleport closets in Cigotuvi's Fleshworks (11570)

crawl-ref/source/dat/clua/stash.lua
When a player has a good shield and has trained a lot of shield skill,
it would be nice to filter out two-handed weapons. Likewise, later in
the game once a player is committed to two-handed weapons, it can would
be nice to filter out one-handed weapons. However, no stash search
prefix has previously existed so it was impossible to search for a
particular handedness.
Hence, add a stash search prefix for handedness. There is no check in
the hands function defined in l-item.cc that the item searched for is
actually a weapon, so we check that the item is a weapon first.
Additionally, filter out throwing weapons because they don't occupy the
weapon slot, therefore their handedness is not useful to search for and
will instead clutter up the search results list.
Re throwing, if you would rather …
=> Add functionality to search items by handedness.

crawl-ref/source/butcher.cc, crawl-ref/source/butcher.h, crawl-ref/source/spl-selfench.cc, crawl-ref/source/spl-summoning.cc
Currently, if you cast animate skeleton, you get a skeleton and chunks.
However, if you forget that you have animate skeleton (or have
auto-butcher on or whatever), you have a one_chance_in(3) chance of
being left with a skeleton to animate.
This behavior gives Animate Dead an extra hidden nutritional trade-off,
in exchange for an interface screw.
This commit changes the behavior of butchering to always leave a
skeleton, so that butchering and casting animate skeleton commute.
A consequence is that Animate Dead becomes *slightly* stronger, as a
player could now butcher every corpse for nutrition and then animate the
skeleton, at the expense of a few HD for the undead minions. This isn't
actually a buff, though, because said hypothetical player can already walk to
each corpse and cast …
=>  Have butchering always leave a skeleton.

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc, crawl-ref/source/options.h, crawl-ref/source/output.cc
This commit modifies the equip bar to process elemental colours (coming
from unrands) for equipment glyphs in the equip bar.
By default, the colours are not animated, since a goal of the equip bar
was to lower visual noise. The option "animate_equip_bar" is added to
toggle this behavior, as the other goal is to show of your cool stuff.
=> Add elemental colour support to the equip bar

crawl-ref/source/player.cc
Fixes https://crawl.develz.org/mantis/view.php?id=11279
You can reproduce the bug consistently by entering a floor with a portal, leaving the floor, waiting for a while, and returning to that floor. While catching the floor up to the current time, the portal message is triggered while the player is not yet on the floor.
=> Do not hear sounds from nowhere when changing levels

crawl-ref/source/ability.cc, crawl-ref/source/god-abil.cc
Firstly, allow wall jumping via the ability whilst berserk. Previously, the ability menu simply would not open whilst berserk. (11687)
Secondly, disallow wall jumping while stuck in nets or webs - previously this was impossible via movement but the ability method was successful. (the second issue reported in 11690)
I am working on fixing the first issue in https://crawl.develz.org/mantis/view.php?id=11690, and may have a fix for that soon. For this issue, it seems logical that the player gets their attacks when landing in a web, so the only actual issue that needs fixing is the message order. This is more complicated than it looks though.
For now I thought I would post these two fixes, since these can be merged anyway. If there are any code style issues, feel free to post them and I can …
=> Fix a couple of wall jump inconsistencies (11687, 11690)

crawl-ref/source/evoke.cc, crawl-ref/source/mon-attitude-type.h, crawl-ref/source/mon-clone.cc, crawl-ref/source/mon-clone.h
See https://crawl.develz.org/mantis/view.php?id=11171
This implements option 3 from the bug report.
clone_mons() now accepts monster_attitude_type as a default parameter.  This allows us to directly set the monster attitude to handle the bug in question and maybe bypass some funky gymnastics related to the bug in question.
Additionally, an unused default parameter, pos, is removed from clone_mons() because it is not passed by any of the other locations that call clone_mons().
Finally, the call to clone_mons() from _phantom_mirror() has been updated to pass ATT_FRIENDLY.
=> Allow setting attitude of cloned monsters (damerell, #11171)

crawl-ref/source/transform.cc
When wearing faerie dragon scales with the HP artefact property and
entering or leaving a transformation that modifies HP, HP would be
scaled incorrectly. This was because:
- On entering a transformation, equipment was melded after the
transformation took effect, which meant the new max HP was used as
the finishing value for the HP change from melding the scales
(resulting in a much higher than expected final value).
- On exiting a transformation, equipment was unmelded before the max HP
was downscaled, which meant the old max HP was used as the starting
value for the HP change from unmelding the scales (resulting in a
much lower than expected final HP).
Hence, in transform(), meld equipment before changing the value of
you.form, and in untransform(), downscale HP from the transformation …
=> Fix HP+ faerie dragon scales causing HP-scaling transmutations to overscale the player's current HP (11728)

crawl-ref/source/spl-damage.cc
Fixes https://crawl.develz.org/mantis/view.php?id=11695
There are currently no stone doors in the game.
Damage unchanged.
=> Properly explode Wooden doors

crawl-ref/source/tilemcache.cc
Fixes #858
If a dual-wielder's primary weapon was removed by Tukima's
(determined by a coin-flip in monster::weapon()) , their mcache
entry would be invalided by this check, which didn't consider the
valid option of an alt-hand-wielded weapon.
=> Leave Dual-Wielders Alone

crawl-ref/source/monster.cc
Acidic attacks, from the acidic bite mutation and Punk, previously
displayed the "[Enemy] is splashed with acid" line against all targets,
which suggested to the player that acid immune targets still took extra
damage from these attacks even though any damage was in fact resisted.
Additionally, this was able to corrode acid immune enemies, which does
not seem thematically correct.
Therefore, in `monster::splash_with_acid`, add a check at the start of the
method for acid immunity, which if true, return early from without any
opportunity to damage or corrode the monster.
Acid resistant enemies correctly take half-damage from acid splash and
resist corrosion half of the time both before and after this change.
=> Don't corrode or appear to damage acid immune enemies with Punk or acidic bite (11746)

crawl-ref/source/fight.cc
Killing natural monsters while under Elyvilon's divine protection causes
penance. However, there is no prompt for this, and it seems natural
for the player to invoke divine protection when low on HP so they don't
die, then heal up, and once they've healed, try to fight the enemy
causing them trouble. It was easy for players to accidentally cause
penance by killing enemies while under divine protection in this way.
Hence, add a prompt for attacking natural monsters while divine
protection is active. Penance will not actually trigger until the
monster is killed, but it's better to be safe than sorry.
One thing: attacks like this do not necessarily cause penance; they only do so if the monster is killed by the attack. Is it therefore appropriate to display the line "This attack would place …
=> Add a prompt for attacking living things while under divine protection

crawl-ref/source/hints.cc
Due to the way strings are formatted after being read from this function, this
</magenta> tag was being treated as extra text. It's not needed, so remove it.
Doing it the reverse way doesn't work.
http://self.organizing.systems/x/dcss1.png .
Fix a grammar oopsie.
=> Fix Spellbook </magenta>

crawl-ref/source/hints.cc
The text from hints_target_mode was not properly broken up. See the image in a comment below for the original issue. (I'd rather not post it multiple times).
As stenellad mentions, there are still issues with how it's rendered, but after this simple fix it will no longer go a long way off the right of the screen. These issues may be fixed in a later PR, which is probably best done by adding this information to the dat/descript/ folder so that lines are wrapped at their normal place automatically.
I found this while trying (and failing) to fix an issue posted in ##crawl-dev concerned with the presence of the `</magenta>` tag at the end of this description in tutorial/hints modes. See http://self.organizing.systems/x/dcss1.png [Now fixed in PR #896.]
=> Fix a hints mode memorise menu message from extending horizontally

crawl-ref/source/player.cc
See mantis bug report 11768: https://crawl.develz.org/mantis/view.php?id=11768
Previously, the sturdy frame mutation was taken into consideration only
for the adjusted_armour_evasion_penalty method, not the
unadjusted_armour_evasion_penalty. The latter of the two methods is used
for stealth penalties, Jiyva stat shuffling, autotraining and some parts
of the dodging penalty calculations, which means these things were not
affected by the sturdy frame mutation. This meant the claimed ER-2 of
the sturdy frame mutation did not have the full effect of reducing the
ER by 2.
Hence, move the sturdy frame mutation's effect to
unadjusted_armour_evasion_penalty.
=> Let the sturdy frame mutation reduce stealth/dodging penalties (11768)

crawl-ref/source/melee-attack.cc
Previously phantasmal warriors were able to halve the MR of magic immune
creatures, which was announced and appeared to have an effect even
though it really had no effect whatsoever.
Hence, add a check to exit the case for AF_VULN early if the defender is
immune to hostile enchantments.
=> Don't halve the MR of magic immune creatures from AF_VULN (11754)

crawl-ref/.gitignore, crawl-ref/source/MSVC/crawl.vcxproj, crawl-ref/source/MSVC/include/stdint.h, crawl-ref/source/util/gen-all.cmd
Update gen-all.cmd to be up to date with the current makefile,
namely adding aptitudes and crawl_manual.txt, which stops
MSVC builds from crashing when they can't find the files.
Add some more MSVC build outputs to gitignore
Copy CREDITS.txt from the root directory to docs/CREDITS.txt
to match the makefile/release versions; add it to gitignore.
Change MSVC/stdint.h to match MSVC/include/stdint.h , which
we changed earlier in the first MSVC compatability commits.
=> MSVC support cont.

crawl-ref/source/dat/descript/branches.txt, crawl-ref/source/terrain.cc, crawl-ref/source/terrain.h, crawl-ref/source/view.cc
Granting exploration piety for deep water, lava, and "endless" features
encouraged players with flight or deep water swimmers to wander around
the non-threatening boundaries of shoals and certain lava vaults.
Granting exploration piety in the Temple encouraged a player to
autoexplore the threat-free temple.
I'm not totally happy with the way this is communicated to the player in this branch, and wanted to get some feedback before merging it. However I think the mechanical change is a good one to make.
=> Don't grant exploration piety for Deep water, Lava, and the Temple

crawl-ref/source/traps.cc
Web traps were made permanent to prevent the player from tediously
stepping in and out of them to remove them. But it is still possible to
remove them by luring a giant enemy (e.g., an emperor scorpion) through
a web. (Less realistically, the player may also transform into a giant
form, e.g., using dragon form, and then tear through them.)
Since webs frequently block choke points in retreat paths, this can
easily be worth doing, but is not rewarding gameplay after the first
time the interaction is noticed. In the absence of compelling positive
effect on gameplay from the interaction between size and web traps, the
problem is solved by removing the special case.
=> Make giant creatures no longer tear through webs

crawl-ref/source/tileweb.cc
Commit 1406302deb reversed the meaning of the get_real_hp()'s second
parameter and updated all instances of this function, except for one
in tileweb.cc.
=> Fix display of rotted HP on WebTiles (11759)

crawl-ref/docs/options_guide.txt
Add the options:
tile_transporter_col,
tile_transporter_landing_col, and
tile_explore_horizon_col
to options_guide.txt.
Adjust whitespace to retain alignment of the other tile colour options.
=> Add three tile colour options to the options guide (11802)

crawl-ref/source/showsymb.h
This function is never defined or called.
(Apologies---this was supposed to be a part of the previous cloud patch, but in the second version I forgot to bundle it in.)
=> Remove useless function declaration

crawl-ref/source/melee-attack.cc
Fixes bug #0011815 on Mantis.
If the player wielded certain unrands that do damage to nearby actors on
attack, and had allies nearby, then they got a prompt for confirmation
when attacking. This prompt happened even if the player could not see
the enemy. So the location of the enemy was revealed, in no time, by the
player's trying to move into the cell. This commit changes that: the
player trying to move into a cell with an unseen monster will attack
without a prompt.
NB: now characters walking around with one of these weapons equipped and
without SInv may inadvertently anger their allies or their god.
=> Fix information leak for invisible monsters

crawl-ref/source/spl-other.cc
Simply remove the check in cast_death_channel for returning spret::abort
when at max duration. The information that the player has maxed out
their duration is not given to the player for other spells, and so
should not be given for death channel.
=> Fix death channel duration leak when cast at max duration (11828)

crawl-ref/source/spl-damage.cc
This commit adds a call to behaviour_event to, among other things, wake
sleeping monsters, when they are attacked by an animated tree from
summon forest as long as the attack hits.
Reproducing this bug is difficult: I recommend the method Yermak talked about in his bug report: that is, place monsters behind a closed door, cast the spell, then open the door.
=> Fix monsters not being woken when hit by animated trees (11819)

crawl-ref/source/MSVC/Common.props, crawl-ref/source/MSVC/crawl.vcxproj
Rather than defining __STDC_LIMIT_MACROS for every single build type, move it to common.props.
At the moment it's only defined in one build type, which is due to lack of completeness (on my part) in the past.
=> Move a MSVC property to a property file

crawl-ref/source/dgn-overview.cc
After commit eddfa9bf, if an illusionary unique created by phantom
mirror outlives the original, the corresponding unique annotation
won't be removed.
Fix this by not adding annotations for illusions.
=> Don't add unique annotations for an illusory unique (u/kitchen_ace)

crawl-ref/source/player.cc
Previously, the effects of flat evasion bonuses such as rings of
evasion, the amulet of the acrobat, mutations, and potions of agility,
were scaled up by the effects of flying as a tengu, and swimming as a
merfolk, and halved by the petrifying and held statuses.
This led to weird behaviour where flying as a tengu meant acrobat
actually gave 18 EV, and other oddities, which are inconsistent with how
flat bonuses generally function.
Therefore, this commit makes it so that the evasion bonuses are added to
the post-scale evasion, rather than the pre-scale evasion.
There is a remaining inconsistency in paralysis, full petrification,
tree form, and most notably, dexterity stat zero, where these evasion
bonuses are not accounted for at all. In the case of paralysis and full
petrification this …
=> Don't scale EV bonuses when a flying Te/swimming Mf/petrifying/held (11463)

crawl-ref/source/describe.cc
Previously, the AC granted by armour when the player has deformed body
was sometimes lower than that indicated in the item description's
"Wearing mundane armour of this type will grant the following:" line.
This was because:
- player::base_ac_from calculates the AC reduction from
deformed body as `AC - baseAC / 2`;
- the description called the player::base_ac_from method with scale
parameter 1, resulting in the AC being rounded up;
- the actual AC calculation called the method with scale parameter 100
and then performed integer division on the final result, resulting
in the overall AC being rounded down.
Fix this by calling base_ac_from with scale parameter 100 and then
dividing by 100, so that the maths here is equivalent to that in the
real AC calculation.
=> Fix AC calculation in item description with deformed body (Monsterracer)

crawl-ref/source/hiscores.cc, crawl-ref/source/player-reacts.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h
Display "Slain by X ... while petrified [by X]" on the death screen when
the player was killed while petrified, in the same way as paralysis.
This applies only when fully petrified, not when petrifying, and the
monster that first applied the petrifying status is used in the death
message, even if the player is hit again with the petrify spell by a
different source on the following turn and this accelerated the
petrification process.
=> Include petrification information in death messages (11374)

crawl-ref/source/dat/descript/tutorial.txt, crawl-ref/source/skill-menu.cc
Update a traps message that stated traps aren't always revealed, and a
berserk hunger message that stated you can't berserk while very hungry;
this restriction is now limited to near starving or worse.
Shorten the "Read skill descriptions" button description to "Skill
descriptions" to avoid this overlapping the text on the following line.
I have completely played through the tutorial; these were the only issues I found.
=> Update tutorial, fix tutorial/hints mode skill menu text (11851)

crawl-ref/source/timed-effects.cc
Re-enables the stat shifting passive for Gnolls who are worshipping
Jiyva. This is a leftover fragment from the static attribute iteration
of Gnolls.
=> Re-enable stat shifting for Gnolls worshipping Jiyva

crawl-ref/source/directn.cc
When multiple enemies entered line of sight at once including at least
one dancing weapon, the message "There is." was being printed. This is
because there was an unnecessary check for enemies not being dancing
weapons in get_monster_equipment_desc. Remove this check, and add a
special case to the helper function _describe_monster_weapon to prevent
these messages being printed as "There is wielding a +4 trident."
These messages should now properly print as e.g.
"There is a +4 executioner's axe of electrocution."
=> Fix dancing weapon description when multiple monsters enter LOS (11843)

crawl-ref/source/dat/species/draconian-yellow.yaml
This apparently needs to be set at XL 7 not XL 1.
=> Fix yellow draconians' rAcid mutation not being applied (malacante)

crawl-ref/source/directn.cc
Previously the dancing weapon's name was being duplicated because there
weren't proper checks for dancing weapons in the second half of
get_monster_equipment_desc. This was broken in f44d0c5.
Apologies for breaking this.
=> Fix dancing weapon description on hover (11887)

crawl-ref/source/god-abil.cc
The range of grand finale was hardcoded as 7 rather than using
LOS_RADIUS, so when barachim were added, this wasn't updated.
This commit changes the grand finale targeter to use targeter_smite's
default parameters, which include range = LOS_RADIUS.
=> Let barachim use grand finale at range 8 (11917)

crawl-ref/source/monster.cc
This is an artifact from when player ghosts were totally unable to leave the floor they started on by any means. Now that they don't have this trait, and don't broadcast it in their descriptions, there isn't any reason for them to be special-case immune to shafts, or for them to destroy shafts uselessly on moving over them.
=> Player ghosts aren't immune to shafts

crawl-ref/source/mon-death.cc
Fixes bug 11909
Affects hell rats because they get the MH_EVIL flag applied as well as MH_DEMONIC, the bug would also affect any demonic monster with more than one holiness flag.
Probably just overlooked in c932079a4eb94c70e47aebf39e9aad417afd7f93 back in 2014 but I didn't do a lot of digging.
Thanks!
=> Use OR instead of equal for holiness check (11909)

crawl-ref/source/ng-setup.cc
After this commit, all new characters who start with a weapon wielded
will find that weapon in slot 'a'. This was already true for all
backgrounds except wanderer.
=> Start new wanderers with weapon in slot 'a'

crawl-ref/source/ability.cc
When the Sacrifice Purity ability was granted to the player with the
inhibited regeneration mutation, the ability's cost description is
Purity (inhibited regeneration)
which is 31 characters, however the cost string is only allocated 30
characters, so the last parenthesis was being cut off.
Hence, extend the string length for the ability cost description to 32
characters, and adjust the ability screen's title line accordingly.
I am fairly confident inhibited regeneration is the longest of all the ability cost descriptions. If anyone finds one longer, please tell me.
=> Fix cut-off ability cost description for Sac Purity (11893)

crawl-ref/source/items.cc
Added a missing `!`. Behavior was reverse of intended: instead of
swimming characters being the only ones exempt from item splash sounds,
they were the only ones making them.
=> Fix splash noises when dropping item into water

crawl-ref/source/dat/des/branches/vaults_rooms_ghost.des, crawl-ref/source/dat/des/variable/ghost.des
This commit prevents the vaults ebering_ghost_disaster_area and
ebering_vaults_ghost_disaster_area from placing shaft traps, instead
placing only water and lava tiles, implementing option 2 in 11926.
This change is to prevent ghosts in these vaults from being shafted
immediately when they enter line of sight of the player, before the
player can do anything to stop this.
These vaults were introduced by commits bb431e2 and a6a7277
respectively, and appear to have been introduced with the idea that
ghosts cannot be shafted. Ghosts can now be shafted, as of 8c2e593, and
this means that these vaults in particular could cause ghosts to be
shafted to lower floors, leaving behind an empty (or mostly empty) ghost
vault for the player to raid, and allowing the ghost to be encountered
outside of its …
=> Don't place shafts in ebering_ghost_disaster_area (11926)

crawl-ref/source/movement.cc
Previously, the types of walls that formicids could dig was hardcoded in
move_player_action. This commit changes the check to use the function
feat_is_diggable, the same check that is used for digging wands, to make
formicid digging exactly equivalent to the wand form.
=> Let formicids dig statues (Yermak)

crawl-ref/settings/colemak_command_keys.txt
CMD_MAP_UNFORGET is overwritten in colemak_command_keys.txt
I propose setting it to F since it is similar to CMD_MAP_FORGET [^F]
=> Fix CMD_MAP_UNFORGET in colemak keybindings

crawl-ref/source/items.cc
Food generated by autobutchery was being allowed to re-use the item_needs_autopickup result from back when it was a corpse. Force it to be re-checked after creation instead.
=> Don't ignore autopickup settings after autobutcher

crawl-ref/source/monster.cc
When reapplying ENCH_CORROSION on a monster, make it clearer in the printed message that it's just a duration increase and not a stacking effect.
Old: zap wand of acid -> The acid corrodes the death yak! -> zap -> The acid corrodes the death yak!
New: zap wand of acid -> The acid corrodes the death yak! -> zap -> The death yak seems to be corroded for longer.
=> Add new message for re-corroding a corroded foe

crawl-ref/source/art-data.txt, crawl-ref/source/dat/descript/unrand.txt, crawl-ref/source/throw.cc
The storm bow is functionally the same as a +8 elec longbow; fairly
strong, but unremarkable. Piercer is a little better since it's a bow
user's only way to get a penetration weapon, but that's still not too
special.
Adding a penetration effect to the storm bow makes it much more
exciting, fits the electric/lightning theme, and puts it almost on par
with the other unrand bow Zephyr. This also makes Piercer obsolete.
=> Merge Piercer into the storm bow

crawl-ref/source/dbg-maps.cc
As a followup to 17bec22d, this commit prevents mapstat from generating
the other removed branches: the Dwarven Hall and Hall of Blades.
It affects only the latter though, because the Dwarven Hall doesn't have
any maps and cannot be generated anyway.
Before this change, the Hall of Blade's info could be found between the Vaults:5's and Crypt:1's data in mapstat.log.
=> Don't try to generate any removed branches in mapstat

crawl-ref/source/player.cc, crawl-ref/source/skills.cc
Add a call to check_training_targets() into the function
check_skill_level_change(). Also, update an inaccurate comment about
this function.
=> Turn off skill targets when aptitudes change from level up (11943)

crawl-ref/source/stairs.cc
Gauntlet prevents long distance translocations from happening (NoTele),
but the user won't know about this until they check the % screen,
read a scroll of teleportation or notice that teleportitis hasn't
triggered since they entered the branch.
=> Warn the player that teleportation doesn't work in gauntlet

crawl-ref/docs/options_guide.txt, crawl-ref/source/output.cc, crawl-ref/source/webserver/game_data/static/player.js
Because of how the score is calculated, it might be more useful to have
player turns instead of elapsed time on the HUD.
`show_game_time = false` replaces time with player turns, but also
hides the duration of the last action. The HUD is the only place that
shows this duration, so players who care about their score have to use
the default value for show_game_time and have to regularly check their
turns via the E or % commands.
After this commit, the HUD will display the duration regardless of the
show_game_time's value.
This change was suggested on ##crawl-dev on 2018-08-30.
=> Always display the duration of the last action on the HUD (Yermak)

crawl-ref/source/directn.cc
This is a minor UI tweak and a bit of code cleanup in full_describe_view (which handles the ctrl-x screen).
=> Traps in full describe view

crawl-ref/source/tilecell.h
This was happening because the packed_cell constructor was not
initializing `is_highlighted_summoner`.
=> Fix local tiles monster panel showing summoner halo for all enemies

crawl-ref/source/dat/defaults/messages.txt
"Careful!" was being triggered by allies that sometimes said
"Be careful!".
=> Minor changes to default force_more_messages

crawl-ref/source/describe.cc
Duplicates the text description, but the only alternative I could come up with was special-casing the breaks in the switch statements which is probably worse?
=> Add second brand to description for Thermic Engine and Storm Bow

crawl-ref/source/tilesdl.cc
Previously the 512x512 app icon was only used on MacOS, and all other
platforms used the 32x32 icon. This change is to use the 512x512 icon on
all platforms.
Note that I only have access to Linux, so that is all I've tested this on.
=> Use high-res app icon on all platforms

crawl-ref/source/dat/defaults/autopickup_exceptions.txt
Make some autopickup-related lua code less eager to forget about
potentially-useful jewellery.
Old defaults for autopickup_exceptions would remove some items (e.g.
ring of poison resistance) from autopickup as soon as the subtype was
known, since you only ever need one. Now that it's possible to learn
what an rPois ring looks like by seeing a monster wear it, that behavior
occasionally leads to useful rings and amulets being left unnoticed on
the ground. To prevent that, don't assume such only-need-one items are
safe to ignore unless the player is actively carrying one around.
=> Don't assume some identified jewellery is boring

crawl-ref/source/dat/descript/ability.txt, crawl-ref/source/dat/descript/spells.txt
Add a one-line description of how bolt spells' range is reduced by one
for each monster the bolt strikes, to all relevant bolt and bolt-like
spells and abilities. The description is:
"The range of the [bolt/blast/jet/ball] is decreased by one for every
creature it strikes."
The spells whose descriptions are changed by this commit are:
Breathe Dispelling Energy
Breathe Frost
Breathe Steam
Breathe Noxious Fumes
Bolt of Cold
Bolt of Draining
Bolt of Fire
Bolt of Magma
Chilling Breath
Cold Breath
Corrosive Bolt
Crystal Bolt
Energy Bolt
Fire Breath
Metal Splinters
Quicksilver Bolt
Steam Ball
Venom Bolt
The bolt-like spells and abilities whose descriptions are not affected
by this commit are:
Breathe Fire (I'm not actually sure what uses this ability, apart from
red draconian players, for whom …
=> Add bolt range behaviour to bolt spell descriptions

crawl-ref/source/webserver/config.py, crawl-ref/source/webserver/server.py
This change has been tested on a local dev environment with and without a reverse proxy. Tested with Tornado 2.4.1 and trunk webtiles server. I used getattr so this will not crash when config.py is missing the new option.
See below for relevant Tornado documentation.
http://www.tornadoweb.org/en/stable/httpserver.html#http-server
http://www.tornadoweb.org/en/stable/httputil.html#tornado.httputil.HTTPServerRequest.remote_ip
Commit message reproduced below:
> This change allows webtiles to accurately log IP addresses when it is
> running behind a reverse proxy.
> 
> Webtiles logs IP addresses when users connect to the server. This is
> done by looking at the value of 'request.remote_ip', provided by
> Tornado. When webtiles is running behind a reverse proxy, the value
> returned by Tornado …
=> Webtiles: Log IPs correctly when behind a reverse proxy

crawl-ref/source/mon-cast.cc
Avatar song’s displayed success rate was incorrect, displaying 0% when the player could be vulnerable. This patch addresses the issue. 
*Editor’s note: the original pr message included unhelpful and unwelcome passive aggression.*
=> Fix Avatar Song displayed success rate

crawl-ref/source/stairs.cc
Always print the number of floors, so the message is consistent between falling one or multiple levels.
=> Improve shaft messaging

crawl-ref/source/dat/defaults/messages.txt, crawl-ref/source/dat/defaults/misc.txt
This was broken by the shaft message change in 52ca42d.
=> Fix a default force_more_message

crawl-ref/source/describe.cc
Previously, descriptions for projectiles were based largely around
whether they had a damage value associated with them, under the logic
that "inherent missile damage => throwable missile". This made life easy
in dealing with the old needles and with regular launcher missiles.
However, it led to:
* the sling bullet description having lots of throwing information
(despite sling bullets not being throwable) and
* the throwing net description lacking the fact that a net's delay is
lowered with Throwing skill
With the changes to throwing missiles, we can now just focus on
throwable-ness to fix these issues and more.
=> Simplify missile description cases

crawl-ref/source/spl-summoning.cc
The monster spell Monstrous Menagerie and monsters using scrolls of
summoning use the same functions in spl-summoning.cc as the player
versions of the spell; this is not the case for any other summoning
spells.
This was allowing the player to cancel casting a monster's monstrous
menagerie or using their scroll of summoning if they had OTR up. We add
special checks to these two functions to avoid calling
otr_stop_summoning_prompt with monster casters.
=> Don't allow the player to cancel monster spells with OTR (11990)

crawl-ref/source/dat/descript/spells.txt
Draining gaze heals ghost moths and eyes of draining for the amount of
MP drained by the gaze. This commit adds a note to this effect to the
draining gaze spell description.
Note: orange crystal statues also cast this spell, but they don't get
healed from it because they cannot regenerate HP.
=> Mention draining gaze's healing effect

crawl-ref/source/Makefile, crawl-ref/source/webserver/templates/client.html
I heard someone mention they weren't ever seeing the newer title splash images on webtiles so I had a look at my test webtiles install and noticed they were completely missing. This fix seems to work at least tho perhaps it would've been better to refactor the makefile so the source folder is just scanned for images and client.html generated accordingly rather than having to explicitly add the images individually each time one is added. First time making a pull request here so apologies if I did anything incorrectly and if so please help me out with some tips. Thanks!
=> Add missing loading images to webtiles.

crawl-ref/source/fight.cc
Addresses Mantis issue [#0011907](https://crawl.develz.org/mantis/view.php?id=11907).
(Edit: Amended commit to pass EOL whitespace checkwhite fail.
=> Removed barehanded attack prompt while in treeform

crawl-ref/source/dat/descript/spells.txt
Simple testing with a deep elf high priest and another spellcaster reveals this information is not correct. The spell was added in commit 19433d8 and it appears that this information was added incorrectly in this commit.
=> Fix incorrect information in Aura of Brilliance description

crawl-ref/source/dat/des/variable/arcadia.des
Should fix a bug where this vault places an item marked as removed.
=> Remove possible placement of blowgun from vault

crawl-ref/source/ouch.cc
And also Xom butterfly spawns.
This exception dates back to when Jiyva was first introduced (in
[0.6.0-a0-258-g6d7627cb65](https://github.com/crawl/crawl/commit/6d7627cb65e54dae22237da82ea076bf17b1f9b7)).
It's an exception which isn't mentioned anywhere to the player and
probably unnecessary in terms of balance for both gods.
=> Don't ignore torment damage for Jiyva jelly spawns

crawl-ref/source/dat/des/variable/float.des, crawl-ref/source/dat/des/variable/mini_monsters.des
Replace an empty square in one with $ to simplify the KPROP logic.
=> Mark some runed door vaults as no_tele_into

crawl-ref/INSTALL.txt
The SDL build dependencies on Fedora are provided by the `SDL2-devel` and `SDL2_image-devel` packages. The current, non-"2", versions will cause the build to fail.
=> Fedora build deps rename SDL* to SDL2*

crawl-ref/docs/options_guide.txt, crawl-ref/source/chardump.cc, crawl-ref/source/describe.cc, crawl-ref/source/initfile.cc, crawl-ref/source/options.h
Obsolete since the introduction of the spell library.
=> Remove dump_book_spells option

crawl-ref/source/l-travel.cc, crawl-ref/source/travel.cc, crawl-ref/source/travel.h
As `travel.set_exclude` and `travel.waypoint_delta` exist as clua functions, I believe `travel.set_waypoint(int waynum, int x, int y)` is a pretty harmless and useful addition to the `travel` clua module. This function sets the position of waypoint #`waynum` to `(x, y)` in player-centered coordinates. In addition, this PR slightly refactors the current `TravelCache.add_waypoint` function to separate out the logic of actually setting the coordinates of a specific waypoint (which is now `TravelCache.set_waypoint`) from the logic of getting and parsing the player's input for which waypoint should be set. The `set_waypoint` clua function simply calls `travel_cache.set_waypoint`.
=> Add setting a waypoint to clua

crawl-ref/source/dat/dlua/ziggurat.lua
Based on absolutely nothing, I think the average stack size of mutation potions is a touch over 1, adjust the new weight accordingly.
=> Unify two loot lines

crawl-ref/source/l-crawl.cc, crawl-ref/source/state.cc, crawl-ref/source/state.h, crawl-ref/source/viewmap.cc
A clua function can be run by adding a level map keymap from a given key to ===functionName. When the function ends, we will still be in map mode unless the function kicked us out of it.
The new clua functions `crawl.in_map_mode`, `crawl.cursor_pos`, and `crawl.cursor_level` all give information specific to map mode. `cursor_level` only validly returns if in map mode, and `cursor_pos` only validly returns if in map mode and the cursor level is the same as the player's level.
=> Allow running clua from map viewing mode; add clua functions to get information about map cursor

crawl-ref/source/l-travel.cc, crawl-ref/source/map-knowledge.cc, crawl-ref/source/map-knowledge.h, crawl-ref/source/viewmap.cc
The set_exclude, del_exclude, and set_waypoint functions all previously ignored the bounds normally set on your cursor in map mode, i.e. you can only move your cursors to points within the bounding box of the known map. These bounds being ignored by the above functions meant both that clua could do something that couldn't be done manually, and that your absolute coordinates could be leaked by careful use of the above functions. This fix will prevent both from happening.
=> Check for known map bounds in the clua travel library

crawl-ref/source/l-crawl.cc, crawl-ref/source/state.cc, crawl-ref/source/state.h, crawl-ref/source/viewmap.cc
Reverts crawl/crawl#1103
Adds a bunch of new untested code paths, for example calling `get_monster_at` when the cursor is on the level above the player causes the grid of the level above to be accessed using the player's current coordinates. No easy fix besides fixing all these codepaths, we should revert for now.
=> Revert "Allow running clua from map viewing mode; add clua functions to get information about map cursor"

crawl-ref/source/dat/des/variable/mini_monsters.des
As both are protected by runed doors / transporters, it shouldn't be possible to teleport randomly inside.
=> Mark two unrand vaults no_tele_into

crawl-ref/docs/develop/levels/guidelines.md
Discourage overuse and explicitly reject the idea all runed door / transporter vaults require it.
=> Add guidelines for no_tele_into usage

crawl-ref/source/main.cc
Ziggurat figurines are usually buried below other loot and could be
easy to miss. This commit adds a confirmation prompt when exiting
Zig:27 without the figurine.
This change was suggested here:
https://www.reddit.com/r/dcss/comments/al6bxh/
=> Warn the player about leaving a ziggurat figurine behind (u/Quatzecoatl)

crawl-ref/source/tilepick.cc
In mon-data.h, the colour of red draconians is LIGHTRED, not RED,
since 54374eb4.
Because tilepick.cc:tileidx_monster_base() had no matching colour for
red draconian Tiamat, it returned a tile with offset 0, the black
draconian Tiamat tile, instead.
=> Fix red draconian Tiamat tile (12043)

crawl-ref/source/command.cc, crawl-ref/source/command.h, crawl-ref/source/dat/database/help.txt, crawl-ref/source/dgn-overview.cc, crawl-ref/source/stash.cc, crawl-ref/source/stash.h, crawl-ref/source/travel.cc
Currently, players need to use `Ctrl+O` to check discovered altars, but then have to use `Ctrl+F` to travel to the desired one.
This change makes it possible to travel to the nearest discovered altar within the Dungeon Overview
1. Within Dungeon Overview, press `_`.
2. Players will then be asked to enter the initial of a god. 
(`A/a` for Ashenzari except for TSO, which is replaced by `1`.)
3. Auto-travel to the nearest (level distance -wise) altar is then started.
This is done by modifying `G` such that `G_` can now be used to select the desired altar for travel, and `_` in dungeon overview is made a shortcut to `G_`.
However, this introduces UI inconsistencies now that `_` can only be pressed in dungeon overview while G only works in the main UI.
Therefore, `G` and `$` keypresses in …
=> Allow travelling to altars, shops, and branches in ^O

crawl-ref/settings/colemak_command_keys.txt
colemak bindings had CMD_ATTACK_<direction> on qwerty vi keys
=> bound missing colemak attack keys

crawl-ref/settings/colemak_command_keys.txt
Reverts crawl/crawl#1138
Rebinding ctrl-i is not great, because that's also TAB.
=> Revert "bound missing colemak attack keys"

crawl-ref/source/stash.cc, crawl-ref/source/stash.h, crawl-ref/source/tilepick.cc, crawl-ref/source/tilepick.h
Currently, the stash search menu doesn't show tiles for several features, including net traps, large runed doors, and permanent teleport traps:
This PR fixes that by handling tile picking for these features separately.
=> Add missing feature tiles to the stash search menu

crawl-ref/source/tiledoll.cc, crawl-ref/source/tilepick-p.cc, crawl-ref/source/tileweb.cc
Scarves weren't being shown at all unless the player chose one through
the doll editor. And even then they were practically invisible, since
they were drawn behind the body (like cloaks) instead of in front
where I think they were meant to be.
The green scarf tile looks quite strange to me, but that's a separate
problem.
=> Show scarves on player in tiles (11977)

crawl-ref/source/mutation.cc, crawl-ref/source/webserver/game_data/templates/game.html
When player is Vampire:
- Toggling works wrong. (console)
- Hit 'A' -> '!', 'Mutations' is still highlighted, then, Hit '!', 'Blood properties' is highlighted.
- Didn't highlight mutations/vamp-attrs tab (webtile)
=> fix mutations/vamp-attrs toggle

crawl-ref/source/player.cc
Currently, if a player discovers an altar and get shafted by a trap at the same time, the altar will appear in dungeon overview but not in stash tracker.
This change ensures items, shops, and altars discovered at the moment the player gets shafted are correctly registered.
=> Ensure stash update on being shafted (minqmay)

crawl-ref/source/stairs.cc
On entering the gauntlet the current message misleadingly suggests no
one can teleport, but the restriction is on the player only.
=> Change gauntlet teleportation message (bugfix)

crawl-ref/docs/crawl_manual.rst
The "wands" and "religion" issues raised in ticket #1125 were already fixed.  And in some places the spellbooks problems were already fixed. But not in all places.
This is a minor documentation fix for spellbooks, since they are no longer "r"ead.
=> #1125 spellbooks are no longer 'r'ead

crawl-ref/source/rltiles/dc-item.txt, crawl-ref/source/tilepick.cc
As a followup to 1cd5daa3, this commit adds code to upgrade Wyrmbane's
tile as the lance grows more powerful.
It'll look like this:
=> Upgrade Wyrmbane's tile according to its enchantment

crawl-ref/source/mon-cast.cc
Because of an incorrect formula added in a559921a, Mara and rakshasa
clones had 200% hp of their original instead of 50%.
Regular monsters copied via `cast_phantom_mirror()` had 286% hp
and max hp instead of 35%.
=> Fix HP of summons created via the Phantom Mirror spell

crawl-ref/source/mon-cast.cc
A copy created via rakshasa's Phantom Mirror has only 35% of
the target's hp and max hp. If the original monster is almost dead
(1-2 HP), its copy will have 0 hp, which crashes the game.
Fix this by giving cloned monsters at least 1 hp. Also, it allows
rakshasas to clone lurking horrors, who always spawn with only 1 hp.
Thanks to geekosaur for finding what was causing two recent crashes on CUE.
=> Fix a crash when cloning an almost dead monster (geekosaur)

crawl-ref/source/spl-goditem.cc
=> A meagre spelling correction for AUS english

crawl-ref/source/beam.cc, crawl-ref/source/dat/descript/features.txt, crawl-ref/source/describe.cc, crawl-ref/source/directn.cc
This PR updates descriptions of trees to make it possible to distinguish flammable and non-flammable trees as well as permanent and summoned ones.
=> Fireproof trees

crawl-ref/source/dat/des/portals/trove.des
Beyond the early game, once almost all the potions and scrolls in the
game are identified, scrolls of identify become a convenience tool more
than anything else; it is simply easier and faster for the player to
identify this unknown ring on the floor using a scroll than to find
something to drop, pick the ring up, put it on, decide it's useless,
drop it, and pick up the other thing. This especially applies when the
player has 5+ spare identify scrolls in their inventory, which is fairly
common around the time of Vaults and Depths.
Troves asking for identify scrolls encouraged players to employ the
tedious second behaviour, and to some extent take risks with
wear-identifying artefacts, in order to horde the scrolls and eventually
enter the trove. Additionally, being reduced to 0 identify …
=> Remove troves asking for scrolls of identify

crawl-ref/source/wiz-dump.cc
Recognize "HP:" and "MP:" as morgue line starts. These happen when
the character is rotted (see output.cc#L2173)
Recognize Gozag which doesn't have a piety meter, causing the God line
to only have 8 fields.
Sample morgue file: !lg collin38 502 -log
=> Fix wizdump loading when rotted or Gozag follower.

crawl-ref/source/god-passive.cc
Currently, there are several Gold Sense-related bugs:
* on webtiles, detected gold is not displayed on the minimap;
* on local tiles, it disappears from the minimap after reloading the
game and after reentering a floor;
* on console, it's not possible to scroll the map in the X mode to see
all detected piles of gold on a new level.
This happens because now update_item_at() runs more than once for each
pile of gold.
Prior to 063869c, the gold detection code from files.cc:_count_gold(),
which contains update_item_at(), run only once for each new level.
After that commit and after 4488db6, the gold detection code, which is
now in god-passive.cc:gozag_detect_level_gold(), runs twice when the
player enters a new floor. First, it runs as a delayed action, then it
runs for counting the generated …
=> Fix display of detected gold on the minimap (11950)

crawl-ref/source/player-act.cc
Change the function is_habitable_feat to an equivalent formulation which is
simpler and idiomatic.
=> Clean up a function

crawl-ref/source/dat/descript/status.txt
This is in reference to Mantis 12049: https://crawl.develz.org/mantis/view.php?id=12049
People thought "deadly liquids" when referring to lava was redundant.  I agree. 
My new phrasing is more flavourful and fun, without trying to specifically call out lava as a "deadly liquid".
=> Mantis 12049 - Lava is deadly

crawl-ref/source/tiledoll.cc
If the player has tile_player_tile = mons:natasha, show the felid
version of blade hands. It's still not perfect (and doesn't match
with many of the other felid tiles) but looks much better than the
human blade hands tile.
=> Use felid blade hands tile with mons:natasha

crawl-ref/source/spl-damage.cc
This commit brings Ignite Poison in line with other damaging spells
that use exclamation marks to show the amount of damage done.
It is a followup for PR #952 and commits 4a3ee908 and 1f260a4b.
=> Indicate damage done by Ignite Poison

crawl-ref/source/item-name.cc
Vampires now heal when bloodless as long as no monsters are in LOS.
=> Fix showing regen amulets as useless for Vampires

crawl-ref/source/mutation.cc
It's not obvious that vampires can heal themselves when they bite
something, and that this works only when they're bloodless. Add some
messages to the abilities screens.
Also make a word lowercase for consistency. 
I don't feel strongly about the wording used on the new messages. Perhaps they could be improved.
=> Show that bloodless vampires' bite can heal

crawl-ref/source/delay.cc, crawl-ref/source/delay.h, crawl-ref/source/player-equip.cc
If you are auto-travelling, and you lose stats from armour
melding or unmelding, don't stop auto-travel for that reason
alone. This is really only relevant for merfolk with artefact
boots, but the fix should apply to the general case.
=> Don't stop travel for changes from (un)melding

crawl-ref/source/ability.cc
This is in reference to Mantis 8887:
https://crawl.develz.org/mantis/view.php?id=8887
Someone pointed out that the second phrase when renouncing religion is confusing to the point of being wrong.
Well, it's easy enough to fix.
=> Misleading text when renouncing religion (8887)

crawl-ref/source/status.cc
It is tactically useful to know how much damage is due to flay. For
example, it matters in deciding whether to quaff cancellation or who to
attack.
This information is already revealed to the player, but not in a
convenient way. At the moment the careful player must pay attention to
what the sources of damage are as the fight proceeds in order to know
this; and, if this is neglected, it is difficult to recover the
information from the message log later in the fight.
This commit reveals that information more straightforwardly by adding it
to the flay status light. I show a number instead of a more
coarse-grained indicator. Note that otherwise the conscientious player
will still want to keep track manually of damage since they can get
better information that way.
The damage is displayed as …
=> Show flay damage in status light

crawl-ref/source/monster.cc
Torment shouldn't be able to kill spriggan riders or their mounts.
=> Prevent torment from killing spriggan riders

crawl-ref/source/tilemcache.cc
They used to have shields drawn on them in tiles; I don't know why this changed but I suspect it was a mistake. Here's how they looks after this patch:
=> Draw shields on deep elf knights

crawl-ref/source/mutation-data.h
I fixed a grammatical typo in the wands mutation text.
Mantis issue:
https://crawl.develz.org/mantis/view.php?id=12103
=> Fixed typo in wands mutation (12103)

crawl-ref/source/ng-wanderer.cc
This PR relates to Mantis ticket 12115:
https://crawl.develz.org/mantis/view.php?id=12115
Essentially, Formicid Wanderers can start with haste potions, but that is a useless item for them.  We already have already have several exclusions so that various types of wanderers don't start with items that would be useless for them (`crawl-ref/source/ng-wanderer.cc`).
It appears this items was an oversight on the useless item exclusions.  Luckily, it was super easy to fix.
=> Remove haste potion from FoWn start (12115)

crawl-ref/source/beam.cc
Commentary about the omnireflection property granted by the Warlock's Mirror (see line 3099 of beam.cc) indicates that it is intended to reflect 50% of ench-type effects at 20 displayed SH; however, the the actual chance is 33% due to a mathematical error. This commit changes the chance to the intended 50% at 20 SH.
=> Make the Warlock's Mirror's reflection chance scale as intended

crawl-ref/source/util/species-gen.py
PyYAML's yaml.load is insecure and it is deprecated in 5.1. Some
distributions even disable it, making it difficult to build DCSS on
them. Use the recommended safe_load instead.
=> Use yaml.safe_load instead of load

crawl-ref/source/invent.cc
Although the player cannot pickup carrion anymore, the pickup menu
still displays a hotkey for it. The hotkey already does nothing
because corpses and skeletons are stationary objects (62bc8482).
=> Remove an inventory hotkey for corpses and skeletons

crawl-ref/source/dat/des/variable/ghost.des
Fixes an ugly green tile when placed in Lair:
=> Add missing SUBST to gammafunk_ghost_icy

crawl-ref/source/religion.cc
Ability slots need to be claimed before setting initial piety. This is because if a player's starting piety is at least 1*, the local tiles version will trigger a redraw of the ability tab, a side effect of which is to fix any available but unassigned abilities using the default logic (starting at f) rather than the god ability rules (a-e + X).
=> Fix initial god ability slot assignment in local tiles

crawl-ref/source/ability.cc
Divine abilities are blocked by silence, but renouncing your religion
isn't really a divine ability.
=> Let the player renounce religion while silenced

crawl-ref/source/view.cc
Commit 7046ed1b expanded the conditions under which headsup messages
happen and how much information they give, but broke the special case of
dancing weapons. The result was that when multiple enemies came into view
the game tried to warn the player about an interesting dancing weapon
with the unhelpful message 'There is .' This commit fixes that.
=> Fix dancing weapon headsup messages (hittemvvvhard)

crawl-ref/source/tilepick-p.cc
Follows the same breakpoints as the color of the 'Pois' status indicator.
=> Change player tile to use multiple levels of poison

crawl-ref/INSTALL.txt, crawl-ref/source/.gitignore, crawl-ref/source/Makefile, crawl-ref/source/platform.h
This uses gcov and gcovr to generate pretty HTML reports of code
coverage for catch2 tests.
Usage: make catch2-coverage COVERAGE=1
Then open coverage-html-report/index.html
In future, it would be nice to improve the UX so:
1. There's no need to remember to specify COVERAGE=1
2. You can generate coverage from execution of crawl normally, not just
catch2.
=> Catch2 Coverage

crawl-ref/docs/develop/arena.txt, crawl-ref/docs/develop/testing.md, crawl-ref/source/.gitignore, crawl-ref/source/Makefile, crawl-ref/source/util/coverage
Add code coverage tracking
Supports both GCC and LLVM toolchains.
Bluffer's guide:
1. make catch2-tests
2. util/coverage
More explanation has been added to testing.md (which reworks
testing.txt) and `util/coverage --help`.
=> Add code coverage tracking

crawl-ref/source/beam.cc, crawl-ref/source/item-use.cc, crawl-ref/source/target.cc
This PR fixes an information leak about Mara/rakshasa clones by making all illusions inner-flameable.
=> Fix an information leak about Mara and rakshasa clones

crawl-ref/source/describe.cc, crawl-ref/source/item-name.cc, crawl-ref/source/item-name.h
These mostly served to confuse players and hide the relation between
the vorpal brands.
=> Remove the per-weapon-type vorpal brand adjectives

crawl-ref/source/dat/descript/items.txt
Recently, a player new to DCSS pointed out she/he didn't know if a "scroll of summoning" would summon friendly or dangerous creatures:
https://old.reddit.com/r/dcss/comments/exa6zm/observations_from_a_dcss_newbie/
Which is a fair point.
I added a single word to clarify that this scroll only ever summons allies.
=> Clarified scroll only summons allied creatures

.github/workflows/ci.yml, .github/workflows/deps.py
I initially implemented this for code coverage support, which is
included. But using GA for all CI tasks has several advantages over
Travis:
* Simpler configuration language.
* Easier composability of steps from third parties. The steps can be
published as Docker images or Node modules and are fully versioned.
* Better integration with GitHub (one status check per build job, rather
than one for the whole CI system).
Requires `CODECOV_TOKEN` set up as a GitHub repo secret (from
codecov.io).
=> Add Github Actions CI

crawl-ref/source/dat/descript/ability.txt, crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/database.cc
This PR introduces a new type of marker for database entries, `[[foo]]`, and fixes several descriptions of monster spells.
=> Fix several monster spells descriptions

crawl-ref/source/Makefile
macOS provides BSD sed which lacks -r. Allow the user to override the
sed binary name so they can specify eg make sed=gsed.
macOS also provides BSD find which lacks -o as an alias for -or. Use -or
instead as it's also supported by GNU find.
=> Improve macOS Makefile support

crawl-ref/source/dat/defaults/autopickup_exceptions.txt
Fixes a syntax error in 458a23e4a.
=> Put runes back on default autopickup (Lici the Crawler)

.github/workflows/ci.yml
Pull requests from forked repositories don't have access to secrets in
the master branch (because attackers could trivially retrieve them).
This means we can't upload Codecov reports from cross-repo pull
requests.
Luckily, the Codecov action has an option for this.
(In future, it would be better if this value was `true` for in-repo
builds and false for cross-repo builds, but the implementation of that
is awkward and probably not worth it. (For the record: write a previous
step which uses a shell script to determine the parent repo and set
`true` or `false` as an output, which you can reference to set the value
of fail_ci_if_error.)
=> Don't fail CI if Codecov upload fails

crawl-ref/source/player.cc
passive_t::extend_berserk is available at 0 stars of piety, so there's no minimum protection level.
=> Fixes comment about Trog paralysis protection.

.github/workflows/deps.py
There have been several cases of builds failing due to dependency install issues. This PR adds retry capability to deps.py which matches the logic previously used for Travis (before the big refactor moved package installation to Travis's responsibility).
=> GitHub Actions dependency install retry

crawl-ref/source/dat/descript/gods.txt
Correct spelling of 'worshiper' -> 'worshipper' in Sif Muna
and Fedhas descriptions, consistent elsewhere in the game.
=> Fix spelling in god descriptions

crawl-ref/source/Makefile, crawl-ref/source/webserver/templates/client.html
Commit ee0576305db0a1a64f1e85ae863a749289b8fd71
added the new image to local tiles, but not to webtiles.
I used commit da47cbf8c3a56b00bc71d06f4eb5fa7dc4a1203e
as a template for this.
=> Add the new octopode loading image to webtiles

crawl-ref/source/dat/des/arrival/simple.des, crawl-ref/source/dat/des/arrival/small.des
This file is also intended as a tutorial of sorts for reading vaults, so I attempted to keep changes I made as syntactically simple as possible. This was most impactful in some of the large vaults (eg erik_arrival_triangle_huge) which needed the first few rooms marked no_monster_gen; I made the entire vault no_monster_gen rather than introduce a KMASK in such cases to retain their syntactic simplicity.
Vault list:
minmay_arrival_wavy_path: Single path, single exit vault. I added a second exit with a door.
matt_arrival_spirals: Two of the three starting locations could have you trapped by a randomly generated monster. Adding no_monster_gen allows the player to get to the main corridor, with multiple exits, prior to finding monsters.
lemuel_arrival_funnel: The island in the center of this …
=> Added room for tactics to vaults in simple.des

crawl-ref/source/dat/database/rand_wpn.txt
Missing end of line, probably caused by the recent commits
that reorganized the lookup files.
=> Fix randart weapon names (12228)

crawl-ref/source/mon-cast.cc
Commit 3b7ae84e64 removed SPELL_DISPEL_UNDEAD from monsters and replaced
it with SPELL_DISPEL_UNDEAD_RANGE, but forgot to update the case in
_ms_waste_of_time accordingly. This resulted in monsters attempting to
cast dispel undead on non-undead creatures; before they never thought
that was worth trying. This commit restores the check.
=> Check holiness before casting dispel undead

crawl-ref/source/dat/descript/unrand.txt
As a followup to 234afa57, this commit replaces an outdated reference
to multiple evocable spells with a reference to OTR.
=> Tweak staff of Olgreb description

crawl-ref/source/map-knowledge.cc
After c225cfcd, notes for dungeon features end in a colon instead
of a full stop.
For example, "60174 | Depths:2 | Found a sacrificial altar of Ru,"
=> Fix stray commas in chardump notes for dungeon features

crawl-ref/source/tilepick.cc
To properly derive the bee spectral and simulacrum tiles
from the new meliai and hornet zombies.
=> Correct meliai and hornet spectral and simulacrum

crawl-ref/source/terrain.cc
This PR fixes the stash search menu no longer displaying tiles for some dungeon features:
Also, it fixes the ?/F lookup-help.
=> Fix stash search menu not showing tiles for some dungeon features

crawl-ref/source/libutil.cc
Treat SIGTERM the same as SIGHUP -- eg gracefully save and quit.
When a SSH client disconnects from a remote session (eg, with
dgamelaunch), the session processes receive SIGHUP. But if a local user
runs eg `killall crawl`, the processes are sent SIGTERM which crashes
the game. Most job control systems (eg systemd, docker) send SIGTERM, so
it makes sense to handle this with the logic that already exists for
SIGHUP.
Don't rename any of the functions or variables relating to this, eg
handle_hangup or seen_hups. That can be done in a future commit, if
desired.
=> Shut down cleanly on SIGTERM

crawl-ref/source/webserver/process_handler.py
Both signals do the same thing now (controlled crash), but this is
hopefully the first step in changing SIGTERM to handle the same way as
SIGHUP (cleanly shut down).
It was a bit off a toss-up between using SIGQUIT and SIGABRT. QUIT means
"quit program" while ABRT means "abort program", so both are probably
suitable. But dgamelaunch-config uses ABRT already:
https://github.com/crawl/dgamelaunch-config/blob/master/utils/webtiles
so we'll follow convention.
=> Send DCSS processes SIGABRT rather than SIGTERM

crawl-ref/source/directn.cc
Currently, if icy walls made by Frozen Ramparts are covered in blood,
then they have only the second part of a covering description:
for example, "A rock wall, and spattered with blood."
=> Fix the x-mode description of walls covered in ice and blood

crawl-ref/INSTALL.md
Currently INSTALL.md refers to the release guide for building packages
under MSYS2, which is not very clear and also doesn't mention the zip
and nsis dependencies. While users can figure this out, I think it would
be good to have it explained directly in the INSTALL file.
Additionally, the 'mingw64/' prefix in row 222 is not needed.
=> Clarify windows package build instructions

crawl-ref/source/religion.cc
Based on discussion in Mantis ticket 12221, this tweaks the range
of Vehumet spell gifts to try to avoid repeated offers at gifts
number 10, 11 and 12.
Extending the range from 6-7 to 5-7 is a small nerf, however
level 5 contains desirable spells (Fireball, LRD). To compensate,
range of gift 12 (the last one before the final) is extended
from 6-7 to 6-8.
=> Adjust Vehumet gift range

crawl-ref/source/end.cc, crawl-ref/source/files.cc
We don't need to ask the player this. It's a simpler mental model for
macro changes to be always saved, rather than sometimes asking the
player (during normal session end, but not eg webtiles tab close /
dgamelaunch hangup).
=> Always save macros

.github/workflows/ci.yml, crawl-ref/INSTALL.md, crawl-ref/source/Makefile, crawl-ref/source/util/species-gen.py
Rather than "python".
Currently this script works with both major versions, so `python` was
specified to use whatever version is installed. But we are starting to
see OSes that install Python 3 only with a python3 name and no python
shortcut. For example, macOS Catalina (10.15), and possibly msys mingw
on Windows.
This new behaviour follows recommendations from the Python project (PEP
394), so is likely to become more prevalent over time.
---
Older webtiles servers (CAO, CDO) may not have Python 3 already
installed, so will need some manual intervention.
If getting Python 3 on these servers proves too difficult, the build process could be changed to initialise a Python virtualenv and run the command within that (to guarantee the existence of a `python` binary). But this would add …
=> Make species-gen.py explicitly depend on python3

crawl-ref/source/dat/des/builder/layout_cellular.des
layout_cellular_growth was disabled way back in 0.15 with a note that it sometimes takes a long time to finish generating a level.  I've bumped up the minimum size in grid_opts from 2 to 3, which noticeably speeds up level generation.  A better solution would be to optimize the layout generator so that using smaller values won't slow things down, but at least this way the layout can be utilized, rather than sitting totally unused.
=> A tweak to reactivate layout_cellular_growth

crawl-ref/source/xom.cc
At low XL, it's difficult for Xom to effectively kill a waitscumming mummy or vampire. This change is largely washed out at larger XLs, but should effectively create more nasty monsters to drop on low-level waitscummers.
=> Add the possibility of one more Xom demon

crawl-ref/source/l-you.cc
This commit adds a clua bind for you.noise_perception().
This information has been available to players visually through the noise bar,
but it wasn't exposed through clua. Noise information can be helpful for
scripted decisions re: resting and retreating, so here's a bind for it.
=> Expose player::get_noise_perception() through clua.

crawl-ref/source/item-use.cc
Since this scroll was added in 388d670c250b25dcf88b5f54042bb083f48a9a51,
the effect has been limited to non-summoned creatures. It's hard to be
exactly sure why.
This limitation is a little non-intuitive, and for a limited resource
like scrolls, probably unnecessary. The scrolls are situational enough
as-is.
---
If you decide not to accept this PR, please update the description to mention the scroll has no effect on summoned creatures.
=> Let scroll of immolation affect summons

crawl-ref/source/dat/descript/items.txt
Change description to better indicate that only monsters hit by the
initial wave will be affected by silence, not monsters that walk into
the water later.
Also I noticed the acrobat amulet description having a line too long,
so fixing that too.
=> Tweak phial of floods description (Flugkiller)

crawl-ref/docs/options_guide.txt, crawl-ref/source/dat/clua/stash.lua, crawl-ref/source/dat/defaults/food_colouring.txt, crawl-ref/source/dat/defaults/menu_colours.txt, crawl-ref/source/food.cc, crawl-ref/source/item-name.cc
This PR removes a few *leftovers* from when potions of blood and more types of
food for carnivores/herbivores existed.
Also, it removes `menu_colour` rules for decks of cards and the lantern of shadows.
=> Preferred food and menu_colour rules cleanup

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc
I recently watched a few players play their first games, and they all made the same errors:
* Running out of food as MiBe (due to auto butcher leaving chunks behind)
* Auto exploring at low HP
The show_more change is a little more speculative, I saw it cause a problem in one game where a newbie was surrounded and getting attacked multiple times. They didn't even realise the `--MORE--` prompt was showing up, and started getting frustrated that the game was ignoring their commands. They figured out pressing spacebar made the problem go away, but didn't understand the underlying principle.
=> Tweak some option defaults

crawl-ref/source/rltiles/tool/tile_colour.cc
Cppcheck complains "Resource leak: fp" at lines 254 and 260 where the
function write_png returns on error without closing the file opened
at the beginning of the function. After write_png returns, the file
would still be open, but the pointer to it has been lost.
Cppcheck errors:
```
[crawl-ref/source/rltiles/tool/tile_colour.cc:254] (error) Resource leak: fp [resourceLeak]
[crawl-ref/source/rltiles/tool/tile_colour.cc:260] (error) Resource leak: fp [resourceLeak]
```
=> Fix resource leak if allocating PNG structs fails.

crawl-ref/docs/options_guide.txt
This commit updates examples, removes mentions of obsolete items
and spells, and fixes some typos.
Also, it adds missing entries into TOC and reorders options in TOC
so they match the order of the descriptions.
=> Update the options guide

crawl-ref/.gitignore
Change to wildcard matching, also add the exe, which is already excluded
elsewhere with *.exe, but should be also here for consistency.
=> Fix gitignore for windows packages

.github/workflows/ci.yml
Current runs are giving the following error during the "post cache
compilation" step:
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/17c1f8fd-a821-43cb-a606-fc036b1b78dc/cache.tgz -C /home/runner/work/crawl/crawl/$HOME/.ccache .
/bin/tar: /home/runner/work/crawl/crawl/$HOME/.ccache: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now
[warning]Tar failed with error: The process '/bin/tar' failed with exit code 2
It seems like environment variables are not supported. However, examples
in the actions/cache repo show use of `~`, so we can use that instead:
https://github.com/actions/cache/blob/master/examples.md#python---pip
=> Fix CI ccache caching

crawl-ref/source/rltiles/tool/tile_list_processor.cc
Fixes the following Cppcheck errors:
```
[crawl-ref/source/rltiles/tool/tile_list_processor.cc:1006] (warning) %d in format string (no. 3) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint]
[crawl-ref/source/rltiles/tool/tile_list_processor.cc:1166] (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint]
[crawl-ref/source/rltiles/tool/tile_list_processor.cc:1180] (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint]
[crawl-ref/source/rltiles/tool/tile_list_processor.cc:1201] (warning) %d in format string (no. 2) requires 'int' but the argument type is 'unsigned int'. [invalidPrintfArgType_sint] …
```
=> Fix signed/unsigned int format mismatch (%d vs %u)

crawl-ref/source/spl-cast.cc
The actual math in this function was updated to calculate the max miscast damage
properly, but the comment was incorrect. dam now uses the sum of level and raw_fail
instead of the product of level and actual fail.
=> Fix the comment on max_miscast_damage

crawl-ref/source/makeitem.cc
Put +6 on stat rings, +4 on the stronger rings, and curses are only -3 or -4, instead of somewhere between 2 to 6.
=> Simplify ring plusses

crawl-ref/source/mon-util.cc, crawl-ref/source/tilepick.cc
Having this information on the main view is useful because confused
allies can attack the player, and paralysed allies block movement.
Also, since the player gets the top-tier stabbing bonus when
attacking sleeping/paralysed/petrified allies, that should be
indicated by the Zz's, TILE_FLAG_STAB, too.
=> Display Zz and ? status icons for allies

crawl-ref/source/timed-effects.cc
This was most noticeable for Summon Forest, whose trees wouldn't tick down while off level.
=> Fixed terrain change duration not decrementing while off-floor

crawl-ref/source/dat/defaults/autopickup_exceptions.txt
...even for players who enable autopickup of them
via `autopickup_exceptions ^= <tin of tremorstones`.
=> One tin of tremorstones should be enough for anybody

crawl-ref/source/main.cc
Every game is displaying the seed, whether or not it's a custom game since the statement evaluates as true.
=> Change = to == in checking crawl_state.type

crawl-ref/INSTALL.md
We are stuck in a limbo of supporting ancient webtiles servers with
Python 2 installed only as 'python', and also newer OSes where Python 3
is only available as 'python3'.
Ideally the Makefile can try all three names for Python automatically
and use the first it finds. But until someone adds this behaviour we
should document the correct approach.
=> Document python-is-python3 for Ubuntu

crawl-ref/INSTALL.md
Most distros package SDL2 separately from its child libraries (SDL2_image, SDL2_ttf, etc).
Adding this to the dependencies for other OS distributions to reduce confusion.
Should clear up #1363
=> Added SDL_image to dependency requirements in INSTALL.md

crawl-ref/source/actor.cc
Commit 19c8d55 added harm to scarves, but used the 'wearing' function,
which is only valid for getting jewellery subtypes. Need to use
'wearing_ego' to get the scarf ego instead.
=> Fix scarf of harm not working

crawl-ref/source/dat/descript/backgrounds.txt, crawl-ref/source/job-data.h
Wizards are a weird background. Their name and starting stats both
point towards a 'pure magic' playstyle, but their starting book
is quite poorly suited to such an approach - they aren't
well-equipped to 'blast' foes, and are much better advised taking
advantage of their imps and mephitic clouds to do a little
backstabbing.
This playstyle seems fine and distinctive, so let's make it
clearer to players. Renaming them to 'hedge wizards' shows that
they aren't expected to be masters of 'high magic' (pure blasting),
as does tweaking their stat spread closer to skalds'. (If we want
the extremely high-int spread to be on some background, Cj would
be a reasonable choice.)
=> Rename Wizards to Hedge Wizards

crawl-ref/source/describe.cc
After 324b7566, amulets of reflection lost their plusses, and as
a result no longer have a part of their description that mentions
the shielding bonus.
=> Fix description of amulets of reflection

crawl-ref/source/dat/des/altar/altar.des
Our code specifically bans shallow and deep water mimics in vaults,
but not lava mimics. Someone could take advantage of that...
Putting this as a PR rather than merging directly because I feel like some people might just want to remove lava mimics. I leave it to a jury of my peers to decide.
=> Add a new altar vault

crawl-ref/source/mon-behv.cc
Currently a foxfire will attack a monster it's aggroed to that is just outside LoS (while the foxfire is in LoS.) Since a foxfire attacks 5 times per turn for 1 damage, this is actually somewhat usefully abusable in the early game vs 0 AC monsters (you can get 3-4 extra damage out of a foxfire by manipulating this.)
This change makes it follow the rules of normal summons and refuse to attack monsters out of player LoS.
=> Fix foxfire attacking out of LoS

crawl-ref/docs/options_guide.txt
The default value was changed to `true` in 750a858e.
=> Update `restart_after_save` default in the options guide

crawl-ref/source/directn.cc
During the do_look_around loop, placing the cursor over an invisible or out of
los monster highlighted the summoner. This commit makes the highlighting code
call can_see to make sure the character should know about the summon.
(A leak with respect to invisible monsters in los remains if you scan with the
cursor while scrying without sinv. This is leaked anyway in that case by the
monster description in the message log area, and there are other leaks with
respect to invisibility while scrying. I've left this alone here on the grounds
that it is part of a bigger, separate problem with scrying and invisibility, and
deserves a more general fix.)
=> Plug an information leak in summoner highlighting

crawl-ref/source/mon-pick-data.h
Remove shadows and wights entirely, they are complete popcorn by this
point.
Push the placement weights earlier for flying skulls, necromancers and
wraiths. These are all very on-brand but still quite easy.
=> Make the Crypt monster list tougher

crawl-ref/source/god-abil.cc
In its present state, charm is not a major sacrifice.  Its most powerful spells are dual-school with Hexes or Necromancy, but being barred from those schools has a larger impact because those schools have further powerful spells, some of which are single-school. It could make sense for charms to be a major sacrifice if/when the school has some heft to it once again.
Necromancy, on the other hand, like conjurations or summoning, can be your school of choice for the whole 3 rune game.  Unlike charms, it does not require a weapon, nor significant investment in other schools.
=> Make necro a major sac, and charm a moderate sac

crawl-ref/source/dat/des/portals/trove.des
These are mostly useless unless there's gauntlets of war, boots of running, etc in the trove.
=> Prevent draconians from getting armour troves

crawl-ref/source/dat/descript/items.txt, crawl-ref/source/delay.cc, crawl-ref/source/delay.h, crawl-ref/source/item-use.cc, crawl-ref/source/item-use.h, crawl-ref/source/player-equip.cc, crawl-ref/source/player-reacts.cc, crawl-ref/source/player.cc
We've added a ton of special logic to amulets to emulate the strategic restrictions of armour equipment/removal. Let's cut out the middle step and just make them take a while to wear or remove.
"acrobat and "reflect lose their attunement, and "gspirit doesn't drain MP (except for deep dwarves). Possibly "regen and "mpreg could lose their attunement, but I'm uncertain about them. "faith definitely keeps its penalty.
=> Make amulets take 5 turns to remove or equip

crawl-ref/source/beam.cc, crawl-ref/source/beam.h, crawl-ref/source/evoke.cc
Previously, phial of floods did three things:
a) It fired a Primal Wave at the target
b) It created a pool around the target
c) It waterlogged monsters in the pool
Primal Wave deals damage, potentially knocks back a tile, and creates its own pool. This led to phial of floods creating two different overlapping temporary pools, one waterlogged and the other not.
This commit consolidates everything into Primal Wave. Phial no longer manually creates its own pool; instead player-created Primal Waves now scale with power like the Phial pool did, and apply waterlogged appropriately.
This commit also reworks Primal Wave's pool generation. Previously, it created the center tile manually, and then randomly added tiles on a 2-radius circeLOS ring to it. I switched it to use the Phial pool generation …
=> Simplify Phial of Floods

crawl-ref/source/dat/des/portals/wizlab.des
As a followup to f75c35ca, this commit replaces a scarf of cloud
immunity with a scarf of repulsion in the Cloud Mage wizlab.
It was reported by Yermak on ##crawl-dev on 2020-06-19.
=> Fix a leftover scarf of cloud immunity (Yermak)

crawl-ref/source/dat/des/sprint/sprint_mu.des
Fixes issue 12302. Existing cloud generators kill sleeping monsters in several places across the map within the first few hundred turns. This tones down aggressive cloud spawn, while keeping the danger in the affected rooms.
=> Adjust Sprint III cloud generators

crawl-ref/source/attack.cc, crawl-ref/source/attack.h, crawl-ref/source/describe.cc, crawl-ref/source/melee-attack.cc, crawl-ref/source/melee-attack.h, crawl-ref/source/ranged-attack.cc, crawl-ref/source/ranged-attack.h
Note that this modifies PR #1464 by Pleasing Fungus, not master.
* Generalizes '_apply_defender_effects' to all post-roll modifiers (including things like a confused player or inaccuracy.)
* Eliminated randomizing EV, since that's only done for monster attacks
* Added iterating over the mhit roll, and enumerating hits there.
* Moved applying post-roll modifiers to post-roll to properly handle repel missiles (whose post-roll modifier is a function of the rolled mhit.
* Switched auto-hit calculation to use Bayes theorem, because I think it's a lot more readable.
* Factored out post-roll modifiers in the attack classes into their own functions.
* Made the lighting modifiers in attack.cc use the relevant consts.
=> Fixes several issues with the xv monster evasion chance calculation.

crawl-ref/source/dat/database/monspeak.txt
Bug reported by Mintice in Discord, the speech shows yells with
at signs around it. I suppose the intention here was to have the
verb randomized as per the _yells_ list.
=> Fix fleeing Harold speech

crawl-ref/source/attack.cc, crawl-ref/source/attack.h, crawl-ref/source/describe.cc, crawl-ref/source/form-data.h, crawl-ref/source/melee-attack.cc, crawl-ref/source/melee-attack.h, crawl-ref/source/ranged-attack.cc, crawl-ref/source/ranged-attack.h
To give players a better understanding of enemies, their weapons, and the combat system, display to-hit chances next to monster EV. 
```
AC: ++
EV: ++++ (37% to evade your +3 rapier of flaming)
```
To do so, we calculate every possible EV roll and compare to the player's to-hit with their current weapon (if any). As part of doing so, certain modifiers have been moved earlier in to-hit calculation:
- backlighting (corona, halo, sticky flame)
- umbra
- repel missiles
- confusing touch
- form UC bonuses
My belief is that this will cause fairly small impacts in practice, but thorough testing should be done before this is merged into master. elliptic suggested using a small script to compare old and new hit chances with various combinations of modifiers and base to-hit, which seems reasonable …
=> Display monster evade chance on xv

crawl-ref/source/webserver/ws_handler.py
Hi, iam currently writing https://github.com/syranez/dcss-lobby which connects to a dcss server and listens to lobby-messages. dcss-lobby parses the messages and gives them in an edited form for further processing. The lobby_remove message does not give any information, why some player got removed from the lobby, thus:
The lobby_remove message contains now additionaly this three attributes:
* reason: the players cause for exiting the game ("saved", "bailed out", "dead")
* message: exit message if the reason is not "saved". Otherwise it is
null.
* dump: contains an url to the final morgue file or player morgue
directory if game is not finished yet.
=> Webserver: Enhance lobby_remove message

crawl-ref/docs/develop/monster_creation.txt
`monster_creation.txt` had previously contained several references to enum.h,
which was split into several files in 895272c. This commit updates the
documentation accordingly.
=> Update monster creation documentation

crawl-ref/source/item-use.cc
Unidentified acquirements scrolls are now cancellable after they are
read, so they should not crumble to dust.
=> Don't crumble acquirement scrolls (12336)

crawl-ref/source/item-use.cc
Currently the message sequence when reading un-id acquirement is:
This is a scroll of acquirement!
_Something appears at your feet! It was a scroll of acquirement.
The second message is not necessary as it only applies to scrolls
which produce an immediate effect without a prompt/menu.
=> Don't repeat acquirement identification message (dinky)

crawl-ref/source/actor.cc, crawl-ref/source/artefact-prop-type.h, crawl-ref/source/artefact.cc, crawl-ref/source/describe.cc, crawl-ref/source/god-item.cc, crawl-ref/source/item-prop.cc, crawl-ref/source/item-prop.h, crawl-ref/source/monster.cc, crawl-ref/source/player-equip.cc, crawl-ref/source/wiz-item.cc
Rampaging is currently pretty rare in practice:
* Ego boots are extremely rare spawns at itemgen.
* Many species cannot equip boots.
* Some characters end up with melded boots due to build choices.
* The positioning choices and skilling choices offered by rampaging
are more impactful when presented earlier in the game.
This commit aims to make rampaging available to a wider range of
characters, by adding it as a potential randart armour property.
ARTP_RAMPAGING generates as 'potentially_good', similar to Harm.
-----
As another way to address rampaging rarity, @PleasingFungus had previously suggested adding rampaging to a new or existing unique monster. That still seems like a good idea to me, but my own attempts at writing a branch to that effect have been uninspired so far. 
In the …
=> Allow Rampaging on randart armour

crawl-ref/source/evoke.cc
Phantom mirror no longer shatters after use with 1d127b8.
=> Correct phantom mirror message

crawl-ref/source/dungeon.cc
In some circumstances, it was possible to be shafted adjacent to a
slime wall, and take damage before having a chance to act.
This commit adds a slime wall adjacency check to shaft destinations.
-----
As a side note, that do while in `_get_feat_dest` scares me a bit, and maybe it could use an assert or something(?), but I'm just going for the quick fix here.
=> Prevent slimy shafting (/u/zeunysos)

crawl-ref/source/movement.cc
This fixes a rampage interaction with deep water / lava.
Previously, the rampaging tracer wasn't properly failing on dangerous
terrain. This was causing the rampage to abort at its moveto check instead,
which erroneously blocked the second half of the move.
-----
This PR fixes [mantis issue 12353](https://crawl.develz.org/mantis/view.php?id=12353).
=> Fix a rampaging bug (12353, Flugkiller)

crawl-ref/source/initfile.cc
The "info" command is missing from the --edit-save usage message.
=> Add missing "info" command to --edit-save help

crawl-ref/source/acquire.cc, crawl-ref/source/makeitem.cc, crawl-ref/source/makeitem.h
These rings aren't supposed to exist anymore as of 2607d5cfa1. However
acquirement was making them by producing -4 bad stat rings and then
setting the rings' plus value to abs(the old plus).
This commit has acquirement directly set the plus for acquired rings to
the "good" value for that base type. This does not affect unrandarts but
may modify randarts.
=> Stop acquirement of +4 stat rings

crawl-ref/source/viewmap.cc
This should fix the recent bug where using X and then [ or ] while on the stairs often did not take you to the other end of the stairs.
(see the commit message for details)
=> Remove bad position clamp for peeking through stairs

crawl-ref/source/tilesdl.cc
When tile_force_overlay is set the divider should always be set to the
end of the of the screen. Move the code that sets that to later in the
code so it doesn't get overwritten.
Without this fix, the space reserved for the message window is still
left unused at the bottom of the screen while the message overlay is
moved to the top of the screen.
=> Fix the divider position when tile_force_overlay is set

crawl-ref/source/output.cc
Artefacts with long names have their properties trimmed on the % screen. For example, it can be just `m - +2 pair of gloves of the Vanishing Shrikes {`.
Harm, Rnd*Rage, and other egos are all displayed in the second column of resistances on the overview screen. This PR adds a similar indicator for Rampage.
=> Display Rampage on the % screen

crawl-ref/source/spl-damage.cc
This commit silences the hailstorm ally warning prompt for battlesphere,
spectral weapon, orb of destruction, and demonic guardians.
Monsters with M_PROJECTILE, (allied) M_AVATAR, or MF_DEMONIC_GUARDIAN flags
are bypassed in bolt targeting by bolt::ignores_monster, and hailstorm cannot
actually deal damage to them.
=> Fix Hailstorm ally warning prompt (12362)

crawl-ref/source/directn.cc, crawl-ref/source/invent.cc, crawl-ref/source/invent.h
This expands 2a96157, which lets you select from an item in a stack when x-v-ing, to list monsters and features as well. Now you are not blocked from examining items when there is a monster on the tile or from examining features when there is a monster or item.
Unfortunately if you use ctrl-x or ctrl-f with the menu in travel mode to see where something is and then want to check the description, you can end up needing to select the same item twice from similar menus. This isn't new with this commit but this does sort of double down on that. I'm open to suggestions.
=> Give x-v a selection menu when there are many describable things

crawl-ref/source/webserver/game_data/static/cell_renderer.js, crawl-ref/source/webserver/game_data/static/game.js
This PR fixes handling of dynamic DPI situations (e.g., dragging the window between hidpi and non-hidpi displays) in webtiles glyphs mode that I accidentally broke in 4531bab [#1512].
=> Handle dynamic DPI in webtiles glyphs mode

crawl-ref/source/duration-data.h, crawl-ref/source/god-abil.cc, crawl-ref/source/god-abil.h, crawl-ref/source/religion.cc
Currently, only Heroism, Finesse, and Elyvilon's Divine Protection
don't expire immediately when the player is placed under penance. It
seems thematically appropriate for Divine Protection, but even Elyvilon
removes all divine effects on abandonment.
This commit puts Okawaru in line with other gods.
=> Cancel Heroism and Finesse on angering or abandoning Okawaru

crawl-ref/source/describe-spells.cc
After 424c9a47, xv displays hex chances only for spells of friendly
monsters.
=> Fix display of hex chances on the xv screen

crawl-ref/source/artefact.h
Re-submit only the documentation of `artp_value_type` as suggested by Pleasing Fungus.
=> docs: Document artp_value_type

crawl-ref/source/spl-cast.cc
`spell_range()` can return 4 instead of 3 for Hailstorm, because
Vehumet supports the use of this spell. But Hailstorm's range never
changes, since it's hardcoded as 3 in `cast_hailstorm()`.
=> Don't show a bigger targeter for Hailstorm when worshipping Vehumet

crawl-ref/source/dat/clua/autofight.lua, crawl-ref/source/l-moninf.cc
After 9c76b8a6, there are only two stabbing tiers. Also, the player
gets a top-tier stab bonus when attacking petrified enemies.
This commit updates autofight rules so petrified enemies get the same
priority as sleeping or paralysed ones.
=> Fix autofight not prioritizing petrified enemies
