crawl/crawl

crawl-ref/source/dat/descript/ability.txt
This PR fixes Shaft Self description, because the ability has an equal chance of taking the player 1, 2, or 3 levels down.
Although all shafts work the same way now, the following still might be interesting.
Shafts became a single-use dungeon feature in [0.6](https://github.com/crawl/crawl/commit/60739d90). The same commit changed how shafts work: known shafts were supposed to send the player fewer floors down than unknown ones.
Unknown shafts had an equal chance to drop the player 1, 2, or 3 levels down. Known shafts, including Formicid-made ones, worked differently:
| Version / chance  |  1 level |  2 levels |  3 levels |
| :---              |     ---: |      ---: |      ---: |
| 0.6 - 0.18        |      5/8 |       2/8 |       1/8 |
| 0.18 - 0.23       |      2/3 |       1/3 | …
=> A small description fix and a story about known shafts

crawl-ref/source/dat/descript/status.txt
After 4cbea82f, Drain temporarily reduces max HP instead of skills.
=> Update Drain status description

crawl-ref/source/spl-cast.cc
As a followup to 6ee96136, this commit colourizes the names of monsters
on the /polymorph targeter to show their potential threat level.
This gives the player a quick way to see if polymorphing a monster is a
good idea.
It'll look like this:
=> Display threat levels on the /polymorph targeter

crawl-ref/source/dat/des/variable/winding_woodlands.des
Two sub-vaults (15x15_boxy_spiral and 5x15_jagged) had errors which could either veto vaults or cause the vaults to place buggily.
Per recommendation of gammafunk and after watching some players play through the winding_woodlands vaults I think increasing the density of connector rooms by approximately 1.5x will make the vaults feel less empty and decorative.
Also fixes a typo: winging_woodlands->winding_woodlands in one sub-vault name.
=> Fix two winding_woodlands sub-vaults, and increase monster density.

crawl-ref/docs/options_guide.txt
Eringya's Noxious Bog has a default force_targeter now,
so update options guide accordingly. Also fix two stray rows
which were longer than 80 characters.
=> Small update in options guide

crawl-ref/docs/crawl_manual.rst, crawl-ref/source/dgn-overview.cc
After commit 8436896, any level can be annotated. Update instructions
in Ctrl+O and in the manual accordingly.
=> Clarify annotations in Ctrl+O and in the manual

crawl-ref/docs/changelog.txt
This changelog entry was only commited in 0.25 branch when 0.25.1
was released, not to master, so it's missing now from 0.26 and master
changelog file.
=> Update changelog for 0.25.1

crawl-ref/settings/colemak_command_keys.txt
This is no longer needed since eating is out.
=> remove CMD_EAT from colemak

crawl-ref/source/describe.cc, crawl-ref/source/player-equip.cc, crawl-ref/source/player.cc
Currently, the spectral brand is the most complex weapon ego in the game.
It has two significant drawbacks:
1. It can significantly increase the damage the wielder takes, since the
spectral weapon shares damage with the player.
2. It requires Evocations training to use.
Both due to the overall complexity and the perceived weakness of this
brand, I'm inclined to simplify by removing one of these effects. Pain
sharing makes the brand a bit harder to evaluate, since most brands have
no downside at all vs an unbranded weapon (chaos being the notable exception).
Evocations scaling has several other problems, though:
- It confuses players on a regular basis. People miss the subtle messages about
'ineptitude' and fail to understand why the spectral weapon isn't triggering -
'is it broken?' Some …
=> Remove Evocation scaling from Spectral

crawl-ref/source/dat/des/portals/ossuary.des
Resolves another vault which has the same issue in #1639
=> Mark an ossuary enterance as transparent 2

crawl-ref/source/ability.cc, crawl-ref/source/god-abil.cc, crawl-ref/source/movement.cc, crawl-ref/source/movement.h, crawl-ref/source/player-act.cc, crawl-ref/source/player.cc, crawl-ref/source/spl-other.cc, crawl-ref/source/spl-transloc.cc, crawl-ref/source/stairs.cc
There were several inconsistencies in the types of movement that would end Ozocubu's armour and frozen ramparts and/or trigger barb damage: for example, palentonga's rolling charge and Wu Jian's wall jump would trigger these effects, but barachian's hop and Ru's power leap would not. Furthermore, the effect of frozen ramparts is tied to the player's position at the time of casting, making it intuitive for any change of position to end the effect. This PR resolves these issues by making Ozocubu's armour and frozen ramparts end whenever the player's position changes (providing a prompt when the player attempts to change their position voluntarily), and by making barb damage trigger whenever the player's position changes in a way that thematically requires physical movement.
=> Ice armour bug fixes

crawl-ref/source/dat/des/sprint/arena_sprint.des
Saw an error (that I didn't write down) in someone else's game. Seemed to block progress.
=> Don't try to spawn spiny frogs in arena sprint

crawl-ref/docs/changelog.txt
The player is notified about the Zot clock when there are 1000 turns
left. The notification schedule is in `_bezotting_level_in()`.
=> Correct a change log entry

crawl-ref/source/l-file.cc, crawl-ref/source/quiver.cc
This PR removes compiler warnings I get with gcc 10.2.0 when compiling Crawl (in l-file.cc, quiver.cc and view.cc). I don't think it has any other effect.
=> Remove 3 compiler warnings

crawl-ref/source/dat/des/branches/spider.des
The vault has several spiders trapped behind deep water, as they can
no longer cling to walls.
This commit frees the spiders and reduces the number of water and deep
water tiles in the vault. Also, it removes an escape hatch in the
inner area, since the vault is not a teleport closet anymore.
-----
A code archaeology fact of the day: when monster clinging was removed in 0.13, there was exactly the same problem with spiders trapped behind deep water. `mumra_spider_spiderweb` and other Spider vaults were fixed in bdc56382, but the changes were reverted in 40eb2104 when clinging was brought back.
=> Remove some water from mumra_spider_spiderweb

crawl-ref/source/monster.cc
Currently the SH returned is negative when a monster has an amulet
of reflection equipped without a shield.
=> Make amulets of reflection actually grant monsters SH

crawl-ref/source/prompt.cc
Move the "[Y]es or [N]o only, please" message from MSGCH_PLAIN to MSGCH_PROMPT in yesno() and yesnoquit(). This has two effects.
1. The message no longer appears in the previous message list. The original yes/no question does not appear here, so this message previously appeared in the log with no context. If you're looking through the list to work out what happened, this message doesn't help.
2. The message is blue rather than white by default. This could be changed, but it would take more work.
=> Keep "[Y]es or [N]o only, please" messages out of the log.

crawl-ref/source/mon-info.cc
Previously, if there were 6 sheep, the monster list would show:
(poisoned) if 1 had been poisoned;
(2 poisoned) if 2 had; and
(poisoned) if all had.
This changes the first case to (1 poisoned). It displays (poisoned), as now, if only one sheep is left.
This makes it easier to see when (in this case) a sheep needs more poison.
=> Distinguish between "1 poisoned" and "all poisoned" in the visible monster list.

crawl-ref/docs/develop/levels/syntax.txt
This commit updates examples and removes mentions of obsolete/deprecated
item types, glyphs, and modifiers.
=> Update the des syntax doc

crawl-ref/source/dat/des/branches/swamp.des
grunt_witch_cave gets a real witch now that they exist.
cheibrodos_swamp_witchery seemingly wanted to place exactly one
witch in one of the huts randomly, but actually placed zero to
two witches. Replacing SUBST with NSUBST leads to the intended
behaviour.
=> Tweak some Swamp witch vaults to better fit their creators' intentions

crawl-ref/source/dat/des/portals/wizlab.des
Two vaults - Cloud Mages' Chambers and Roulette of Golubria have boots of running as possible rewards. With the removal of boots of running, these were missed. Replace these with boots of rampaging since they still fit the intended theme/reward of the wizlab.
=> Replace running with rampaging in wizlabs

crawl-ref/source/travel.cc, crawl-ref/source/travel.h, crawl-ref/source/viewmap.cc
Split find_travel_pos() into two functions (one with move_x and move_y, one with features).
Remove some unnecessary code from the latter version.
=> Split find_travel_pos().

crawl-ref/source/travel.cc, crawl-ref/source/travel.h
Make travel_pathfind::points a local variable in pathfind().
Move _find_explore_status() into travel_pathfind.
Delete set_annotate_map(), set_distance_grid(), greedy_square(), travel_move(), unexplored_square() and get_unreachables(). The functions which had referred to them (if any) now refer to the underlying variables.
=> Delete some unnecessary things from travel_pathfind.

crawl-ref/source/spl-transloc.cc
Also, fix an overlap between ``wont_attack()`` and ``neutral()`` in a condition.
The former means ``ATT_FRIENDLY || ATT_GOOD_NEUTRAL || ATT_STRICT_NEUTRAL``,
the latter means ``ATT_NEUTRAL || ATT_GOOD_NEUTRAL || ATT_STRICT_NEUTRAL``.
=> Don't assault firewood

crawl-ref/docs/crawl_manual.rst
This fixes a small typo in the help section, "2. List of character backgrounds" in the file `crawl_manual.rst`
=> fix typo in crawl_manual.rst

crawl-ref/source/mon-info-flag-name.h, crawl-ref/source/mon-info.cc
1. Fix the handling of singulars and plurals in _condition_string(). It had been saying "(1 reflect damage)", where it should have been "reflects".
2. Fix a typo in a flag name in monster_info_flag_names.
3. Fix a copy/paste error in mons_conditions_string() which prevented missile-wielders from being reported correctly in the monster list.
=> Make the "1 corona" status message grammatically correct, and others.

crawl-ref/source/describe.cc, crawl-ref/source/spl-util.cc
After 4502bb1e, the player can cast Sublimation when at max MP. The description still has the "This spell would have no effect right now" warning, and the spell is correctly greyed out on the quiver in this situation, though.
Fix this by moving Sublimation's MP check into a function that is called before subtracting the MP cost. This adds a spell-specific check to casting-specific ones, but it's good to have all MP-related checks in one place. Also, it's clearer than temporarily refunding the spell cost, as it was before 4502bb1e.
=> Don't waste time casting Sublimation of Blood when at max MP

crawl-ref/source/actor.h, crawl-ref/source/monster.cc, crawl-ref/source/monster.h, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/religion.cc, crawl-ref/source/religion.h, crawl-ref/source/terrain.cc
Add a "temp" parameter to player_can_join_god() and player::undead_or_demonic(). If false, the functions ignore temporary effects from things like mutations and spells, and only consider permanent barriers such as the player's species and Ru sacrifices.
Use this to stop the game from making a note on finding an altar for a god the character will never be able to worship.
=> Don't make a note when you find an altar you can't use.

crawl-ref/source/travel.cc
Change how auto-explore responds to excluded areas of the level (to address the issues I raised in #1766).
1. Walls and trees are never considered reseedable (so you can't change a level from being explored to not being explored by adding a travel exclusion).
2. Excluded squares may be considered travelsafe when ignore_hostile is set (so the game will look beyond the start of the excluded area to find out if the level has been explored).
3. Explore will consider putting the explore_target somewhere where point_distance < 0 (so that it reports when it can't reach items in an excluded area).
3 is actually achieved by reversing e99fe26798. I added a similar check in _explore_find_target_square(), so that the explore command continues to go up to a runed door which is preventing you from …
=> Make explore behave better with exclusions

crawl-ref/source/chardump.cc, crawl-ref/source/spl-cast.cc
A third of player spells - 35 out of 110 [1] - have damage info, but this information is well hidden.
This commit adds a quick way to compare spells and to see all the numbers at once.
It'll look like this:
Not sure what was the purpose of trailing spaces after the spell levels in morgues. Removing them doesn't mess up line wrapping on the `?#` screen in console and both -tiles, as far as I can see.
-----
1. There are eight more spells that could have damage info: Tornado, Summon Lightning Spire, Poisonous Vapours, Olgreb's Toxic Radiance, Airstrike, Eringya's Noxious Bog, Borgnjor's Vile Clutch, and Chain Lightning.
=> Add spell damage info to the `I!` menu and morgues

crawl-ref/source/god-item.cc
This was a very silly thematic restriction that eliminated a potentially
interesting character choice. The weapon of speed restriction is pretty silly
too, but those are at least supposed to be magically fast or something;
quickblades are just a weapon type with low attack delay. Chei does not care
about the player reducing their attack delay by gaining weapon skill, nor does
Chei care about the player taking quick actions like removing a ring or
unwielding a weapon, so there is no reason to ban a weapon type merely because
it has low delay.
=> Allow Chei followers to use quickblades.

crawl-ref/source/god-conduct.cc
from `Trog doesn't appreciate your training magic!`
to `Trog doesn't appreciate that you’re training magic!`
The grammar of the former one was questionable.
=> god-conduct.cc trog grammar

crawl-ref/source/shopping.cc
At present, trying to place a gadget shop or a food shop will cause
the game to crash.
This commit adds a missing TAG_MAJOR_VERSION == 34 for gadget shops,
and adds a guard against placing either gadget or food shops.
=> Fix a wizmode shop placement crash

crawl-ref/source/items.cc
This was broken in 83025b5. It turns out that items_stack() has some fairly
particular conditions that don't necessarily match ISFLAG_IDENT_MASK, due
to a potential lua info leak. For some background on this, see:
crawl-dev-20151123.lg
If this commit somehow breaks identify again, I apologize in advance.
=> Fix shop purchase potion/scroll stacking

crawl-ref/source/l-spells.cc, crawl-ref/source/spl-cast.cc
This series of commits:
* Adds clua documentation for spells.fail_severity()
* Replaces a miscast threshold magic number in spl-cast.cc with MISCAST_THRESHOLD
* Staticifies MISCAST_THRESHOLD and MISCAST_DIVISOR
=> Add clua documentation for spells.fail_severity()

crawl-ref/source/webserver/templates/client.html
Currently, adding the webtiles interface to the desktop on iOS or iPadOS creates what is effectively a bookmark. It opens in the browser, with the domain displaying, and tabs available.
By adding these meta tags, if a user creates a PWA for WebTiles on iOS, it will launch in full screen as a separate application to the browser, without the standard tabs interface.
This should be a fairly low risk change, as users have to opt in to creating a PWA. The biggest issue is that this hides the browser navigation if you’re using a PWA, so you might theoretically be able to navigate to part of the site that you couldn’t easily return from.
This might seem like an edge case, but it would be awesome to be able to play DCSS full screen on an iPad with a keyboard.
=> Enable fullscreen PWA for WebTiles on iOS

.gitmodules
Fixes unexplainable breakage with `git submodule update`.
As discussed with ebering on IRC.
=> Use https rather than git protocol for submodules

crawl-ref/source/player.cc
As things stood, trying to travel with barbs stuck in you would see the game ask for confirmation, move a single square (if you accept) and then stop because of the HP loss.
This change makes it so that the game waits for the spikes to time out before moving.
You can't remove barbs if you are confused or asleep, but you can't travel then either, and player::is_sufficiently_rested() isn't used for anything else.
=> Make autoexplore/travel wait for barbs to time out.

crawl-ref/source/beam.cc
Add a debug statement to give the odds of blocking an AUTOMATIC_HIT bolt with the warlock's mirror.
Reduce the chance to block AUTOMATIC_HIT bolts with a displayed SH of 20 from 2/3 to 1/2.
=> Don't nerf the warlock's mirror. Improve debugging messages & comments

crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/l-you.cc
The old Blade Hands description used the word "hands" regardless of
the manipulator type for the species. In addition, it failed to mention
that it would meld shields and gloves. A function was added to l-you.cc
to get the hand type of the player species, and the Blade Hands
description now checks hand type to determine the noun used for the
player's manipulators. The description was also changed to say that
shields and gloves are also melded.
=> Update to Blade Hands description

crawl-ref/source/tilesdl.cc
These last remaining warnings on Windows have been bugging me:
```
tilesdl.cc: In function 'void _init_consoles()':
tilesdl.cc:151:30: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'ac_func' {aka 'int (*)(long unsigned int)'} [-Wcast-function-type]
151 |     ac_func attach_console = (ac_func)GetProcAddress(
|                              ^~~~~~~~~~~~~~~~~~~~~~~~
152 |         GetModuleHandle(TEXT("kernel32.dll")), "AttachConsole");
|         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tilesdl.cc: In function 'void _shutdown_console()':
tilesdl.cc:178:28: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'fc_func' {aka 'int (*)()'} [-Wcast-function-type]
178 |     fc_func …
```
=> Supress a compiler warning on Windows

crawl-ref/source/ng-setup.cc, crawl-ref/source/religion.cc, crawl-ref/source/religion.h
If automatic training was set, and the skills the player actually used all reached 27, the game would start to train the other skills, including the magic skills. This means that someone could offend Trog by training magic skills without casting a spell or visiting the skill management screen.
This change turns magic skills off at the start of the game for a berserker (as already happened when you joined Trog at an altar), and avoids that possibility.
It's pretty easy to experience this problem if you play Meatsprint as a ghoul berserker.
=> Disable spellcasting skill gain for new berserkers.

crawl-ref/docs/develop/levels/guidelines.md, crawl-ref/source/dat/des/altar/altar.des, crawl-ref/source/dat/des/altar/ashenzari_visionary.des, crawl-ref/source/dat/des/altar/ecumenical.des, crawl-ref/source/dat/des/altar/kiku_cage.des, crawl-ref/source/dat/des/altar/nemelex_the_gamble.des, crawl-ref/source/dat/des/altar/overflow.des, crawl-ref/source/dat/des/altar/trog_burn_book.des, crawl-ref/source/dat/des/altar/trog_wizard.des, crawl-ref/source/dat/des/altar/vehumet_trees.des, crawl-ref/source/dat/des/altar/xom_monty_hall.des, crawl-ref/source/dat/des/altar/xom_sheep.des, crawl-ref/source/dat/des/altar/yredelemnul_ordeal.des, crawl-ref/source/dat/des/builder/shops.des, crawl-ref/source/dat/des/serial/column_ruins.des, crawl-ref/source/dat/des/variable/float.des, crawl-ref/source/dat/des/variable/mini_monsters.des, crawl-ref/source/dat/des/variable/the_grid.des, crawl-ref/source/defines.h, crawl-ref/source/maps.cc, crawl-ref/source/ng-init.cc
Several old overflow altars were incorrectly tagged; this gave certain gods (Ashenzari and Nemelex are stand outs) significantly higher chances of getting a D:1 altar, and don't seem intended.
Many overflow temples to single gods could also place as mini vaults, but the weight for each depended on the god, resulting in an uneven appearance of earlier altars for certain gods. This also prevented non-minivault overflows from placing as frequently, which is sad because they're nice vaults.
Ecumenical altars suffer from the fact that they don't always show up before identified altars; the choice becomes more about a conduct than the chance to gamble for a serious advantage.
This commit sequence addresses all three of the above issues by implementing the following changes:
- All temple gods …
=> Resequence early and ecumenical altars

crawl-ref/source/terrain.cc
Change the message when slime_wall_damage() affects an icy monster from (e.g.) "The wall burns the fire elemental shaped block of ice!" to "The wall melts ...". Ice doesn't burn, and similar messages are already given for flaming weapons and the like.
Remove the message for when acid walls affect the player (I'd have otherwise wanted to handle ice form in a special way), as you.splash_with_acid() hasn't used custom messages since 91b4073.
=> Make acid walls "melt" icy monsters instead of burning them.

crawl-ref/docs/crawl_manual.rst
The RST version of the manual needs the | character escaped by a backslash for it to be displayed properly.
=> RST manual: escape the vertical bar key for layer toggle

crawl-ref/source/dat/des/arrival/large.des
adds a church based on the tristram cathedral from the first
diablo game. Hell has desecrated the altar, but a player must
first contend with the Imp guarding it if they dare. a hatch is
provided so you can worship and run or hatch if you get an
unlucky teleport. To the sides of the church there is a crypt and
through the windows the player can see the lust forest they leave
behind. There's also a baptism font (usually dry) because why not.
=> Add diablo church arrival vault

crawl-ref/source/dat/database/montitle.txt
Maud has gone, and her ghost cannot use this title, so it's just clutter.
=> Remove Maud from montitle.txt.

crawl-ref/source/ability.cc, crawl-ref/source/transform.cc
Even if you're [de]transforming into a non-flyer over dangerous terrain,
that's okay if you're currently in flight form. Closes #1881.
=> Allow detransforming over water if flying

crawl-ref/source/transform.cc
Changing the check for temporary forms to "true" when leaving water
keeps the boots from falling off. Closes #1875.
=> Unmeld statueform merfolk boots when leaving water

crawl-ref/source/arena.cc, crawl-ref/source/wiz-mon.cc
In the arena, create a sole ironbound beastmaster if the user asks for one. This means that, if the user wants an ironbound beastmaster and two lindwurms, "ironbound beastmaster,2 lindwurm" will now request this, where it would previously have to have been "2 lindwurm,ironbound beastmaster band no_bands".
In wizard mode, print a relevant message if the player tries to make a sole ironbound beastmaster. The player can remove unwanted monsters later on if needed.
The addresses the issues I raised in #1869
=> Improve the UI when the user creates an ironbound beastmaster.

crawl-ref/source/tileweb.cc, crawl-ref/source/webserver/game_data/static/player.js
After fc3203cb, defense boosts provided by the "acrobat and divine
shield are no longer coloured blue.
This is because unlike other boosts, these two are handled separately
in `tileweb.cc:_update_statuses()` and don't use `short_text` strings
from duration-data.h.
Fix this by updating `short_text`s in `_update_statuses()`. Also, fix
colouring of corroded AC and weapons on the HUD.
I checked all other defense boosts too and they are all coloured
correctly on WebTiles.
=> Further fix webtiles display of defense boosts

crawl-ref/source/invent.cc
Make the game give a "You aren't carrying any scrolls." message if you try to read() when you have no scrolls in your inventory or on the floor, but there is a spellbook on the floor.
The game had given an inventory prompt with no items on it instead.
The first bit of item_is_selected() dealt with reading scrolls, so the case I've deleted was only used for spellbooks. A restriction in use_an_item() means that you couldn't select a spellbok at the "read which item" prompt it gave you, even if you selected "show all".
=> Fix what happens when you try to read a spellbook.

crawl-ref/source/religion.cc
Split _gift_sif_kiku_gift() into _give_sif_gift() and _give_kiku_gift(), and rearrange each a bit.
In addition:
The "get a god gift" wizard command now works for Kikubaaqudgha.
The game doesn't crash if Kikubaaqudgha tries to create a spellbook when there are too many items on the level.
=> Split _gift_sif_kiku_gift() into a function for each god.

crawl-ref/source/mon-act.cc
The previous messages implied that nearby gold piles or the player's carried
gold caused the effect, which was confusing.
=> Change the gozag gold distraction message.

crawl-ref/source/art-func.h
Minor grammatical modification to the message when wielding the Sceptre of Torment.  "Terribly searing pain" (adverb modifying adjective describing noun) becomes "Terrible, searing pain" (compound adjective describing noun).  Both are correct, however, the former is a little awkward because it partially shifts the focus of the sentence from pain to searing.  The latter flows  better because the compound adjective shifts the focus of the introductory descriptions to pain.
=> Modify Grammar Sceptre of Torment

crawl-ref/source/mapdef.cc
Previously, if you using the wizard mode create monster command with
"dancing weapon; stone" on a build with asserts compiled in, the game
crashed with "ASSERT(wpn) in 'dungeon.cc' at line 5159 failed.". The
same happens for any non-weapon, or even "nothing", and the same if a
vault was created which included such a monster.
With this change, it prints "Monster 'dancing weapon' requires a
weapon." instead in wizard mode, and the game cannot start if any vault
contains a monster like that.
=> Fix the error message on creating a malformed dancing/spectral weapon.

crawl-ref/source/spl-damage.cc
After 73eefd5d, Ozocubu's Refrigeration users can get under penance for
opening the z? or Q menus or just for having the spell on the quiver.
It happens if they worship a god who cares about allies and if there
are allies nearby.
Fix this by skipping conducts when doing tracer checks.
=> Don't put Refrigeration users under penance for tracer checks

crawl-ref/source/dat/database/help.txt, crawl-ref/source/wiz-mon.cc
Entering ? as the monster name causes some help text to appear. This is
derived from the MONS section of docs/develop/levels/syntax.txt, but
with a few changes.
1. Use colour - yellow for headings, white for keywords which can be
entered as part of the command, and cyan for other things such as text
the game produces in response to a command, or file references.
2. Remove quotation marks from around keywords. I haven't done this with
cyan text, as this contains longer phrases which may be harder to
separate.
3. Don't give advice on how the command should be used (such as "use
this sparingly").
4. Rearrange the paragraphs a bit, and add a new opening paragraph.
5. Add lists of valid characteristics for mutant beasts and ugly things.
This change means that most of the information you need …
=> Add a help option for the wizard mode create monster command.

crawl-ref/source/dungeon.cc, crawl-ref/source/item-name.cc, crawl-ref/source/item-prop.cc, crawl-ref/source/items.cc, crawl-ref/source/known-items.cc, crawl-ref/source/tag-version.h, crawl-ref/source/tags.cc
Books being unknown had almost no impact on the game. They were a
little fun in antique shops, but that was fairly rare and not worth
keeping the feature given the limitations it presents (max 60 book
types), let's scrap it.
I strongly suspect there are some subtle nasty bugs here, so if someone wants to glance over it, I'd appreciate that.
=> Remove book ID

crawl-ref/docs/options_guide.txt, crawl-ref/source/cmd-keys.h
While testing the zoom for the next Android version, I found it's impossible to zoom in with my keyboard. Some European keyboards like Spanish or German require pressing shift-0 for the equals character, but ctrl-shift-0 doesn't work for zooming it and you get the reassign function instead.
This patch allows ctrl-'+' to be used for zooming in with the affected keyboards.
=> Allow zoom in via ctrl-'+'

crawl-ref/source/rltiles/dc-gui.txt
The newgame doll was missing red hair, which is the default according
to `tilepick-p.cc:tilep_race_default()`.
=> Fix Dj's hair on the species selection menu

crawl-ref/source/actor.cc, crawl-ref/source/artefact-prop-type.h, crawl-ref/source/artefact.cc, crawl-ref/source/describe.cc, crawl-ref/source/output.cc, crawl-ref/source/player-equip.cc, crawl-ref/source/wiz-item.cc
This adds Archmagi as a randart property and enables it to generate on
robes only (for now). Also added are equip/unequip messages, same as for
the Archmagi ego, and an indicator in the character overview screen.
=> Add Archmagi as a randart property

crawl-ref/source/dat/descript/items.txt
The description states that the power scales with your evocations skill.
This does not appear to be the case based on the following:
1. Since https://github.com/crawl/crawl/commit/6f112fb28d0ec403ccb98850db96906d9a5dba3a the damage dice are `dicedef_calculator<6, 6, 0, 1>`, which multiplies the power by 0 when calculating the damage.
2. No other interpretations of 'power' such as the range or radius appear to change based on my reading of the code.
I've done my best to test this in wizard mode and to read and understand the source, however, I am not deeply familiar with crawl or its source code, so please review the above carefully.
It looks like many items (E.G. Wand of Iceblast) show damage stats in the description. Since this is now fixed, should we add that for this item? Ditto the …
=> Corrects the description of Tin of Tremorstones

crawl-ref/source/ranged-attack.cc, crawl-ref/source/ranged-attack.h
Removed dead code ranged_attack::calc_to_hit
This method calls the base and then returns the result.
This can be achieved by simply not overriding the base method.
I believe this was missed during editing because of the conditional in the method, however, since this conditional just returns the same result, it is obsolete.
=> Removed dead code ranged_attack::calc_to_hit

crawl-ref/source/player.cc
The game previously only reported which monsters had "come into view" when a monster shouted or the player was ready to start a turn.
This interacted badly with ABIL_WU_JIAN_WALLJUMP (for one), as you move to a new location as part of the turn, and both you and the monster can act before the next "start of turn" rolls around.
Calling update_monsters_in_view() from moveto_location_effects() should make the "comes into view" message the first one you see for a monster. I also call check_for_interesting_features() so that nearby objects and features are announced at the same time.
=> Check for monsters, objects & features as soon as you move.

crawl-ref/source/delay.cc, crawl-ref/source/item-use.cc, crawl-ref/source/item-use.h
Make it so that:
1. A warning is generated if equipping an item reduces a stat below 1.
2. A warning is generated if removing at item (possibly as part of the same action as equipping a different one) reduces a stat below 1 at any point.
3. A warning is not generated if no stat will be reduced below 1 when equipping or removing items.
4. If a warning is generated and the player decides not to proceed, no in-game action takes place. There was a TODO for this.
The existing code didn't do any of these things reliably.
=> Fix some issues with "stat zero" warnings.

crawl-ref/docs/crawl_manual.rst
This commit fixes a typo in the manual's Missiles section. The verb
should be "throw" since it's being used as an infinitive.
=> Fix typo in the manual's Missiles section

crawl-ref/source/book-data.h
All the spells that appear in only one book and are not available in starting libraries are all level 7 or higher, except for Corpse Rot.  At the same time, Mephitic Cloud is available from Turn 1 for two backgrounds, and also appears in three books.  Thus with Mephitic Cloud being so easily gained, and Corpse Rot as hard to find as end-game spells, and both having a theme of noxious fumes, put Corpse Rot into the Book of Vapours in place of Mephitic Cloud.
=> Mephitic Cloud --> Corpse Rot in Book of Vapours

crawl-ref/source/main.cc
Saying 'n' to the warn_hatches prompts currently has no feedback and leaves the question on the screen, which may cause the player to try to repeat their response.  Since 'n' is a movement key, this is potentially dangerous.
=> "okay, then" for negative responses to warn_hatches prompts, and a nearby indentation fix

crawl-ref/source/webserver/process_handler.py, crawl-ref/source/webserver/static/scripts/client.js, crawl-ref/source/webserver/static/style.css, crawl-ref/source/webserver/templates/client.html
This lets spectators find potentially interesting games to view, i.e. from a speedrunning perspective.
`webserver/process_handler.py`:
* Treat the turn count and duration (real game time) as "interesting info" in the wherefile.
`webserver/static/scripts/client.js`:
* Show the new turn count and duration fields.
* While at it, rationalise the units shown for idle times ("min" -> "m", and drop the spaces).
`webserver/static/style.css`, `webserver/templates/client.html`:
* Add new fields.
Note that previous versions of the commit made the real time display increase automatically on the lobby's client side, similar to the idle time. However, this ignored the effect of `IDLE_TIME_CLAMP`; it's not valid to assume that real time is always ticking (instead, it stops after the game is idle for …
=> Show turn counts and real game times in lobby

crawl-ref/source/book-data.h, crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/god-abil.cc, crawl-ref/source/job-data.h, crawl-ref/source/l-debug.cc, crawl-ref/source/spell-type.h, crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/spl-data.h, crawl-ref/source/spl-util.cc
Scorch is a damage spell that strikes a random enemy in sight, dealing fire
damage to them and (if it beats AC & resists) applying Cerebov's rF- debuff
to them for a few turns. Currently, it does 2d5 damage at 0 power, scaling to
2d10 at 50 power.
Scorch is intended to provide additional variety to the Fire Elementalist
early game (reducing reliance on Foxfire) and to make Cinder Acolyte feel
more distinctive from FE by replacing its Foxfire entirely.
Open questions:
- Is the 'random targeting' gimmick actually fun, or should the player have
a bit more control over what they bap?
- Would the spell feel more fun with a limit on range (& perhaps some
compensatory buff)?
- Are the numbers reasonable?
TODOs:
- Add the spell to books properly.
- Add a message when spells become castable due to …
=> New spell: Scorch (L2 Fire)

crawl-ref/source/decks.cc
There are too many monsters with similar roles on this card. I want to cut out too many branches and leave only those who match the name of this card.
Modified Effect: Now it summon only these three(centaur warrior, naga sharpshooter, deep elf master archer).
=> Simplify the ranger card

crawl-ref/source/player.cc
e08c5e17fd added an air enhancer to the amulet of the air, but unlike the
rest of the spell enhancers in the game, it didn't permit stacking this
with the elemental staff. This looks to me like an oversight rather than a
balance issue, (especially given that you could still stack the amulet with
a vanilla staff of air), so here's a fix.
=> fix: allow unrand air enhancer stacking

crawl-ref/source/describe.cc
Improved the description given for for monsters bonus damage given in  619f226d55, the goal is to make it easier fot the player to understand what damage will be gone if they get the monster to stop attacking with ranged weaponry.
=> Improve archer description

crawl-ref/source/ability.cc
This specifically affected the "Abilities" section of the sidebar, but I'm not sure where else. It seems likely that this is legacy code from when walljump was more of a pseudo-ability, but since whether something can be used while silenced is determined by the failure basis (e.g., if it's an invocation), there's no need for this check to exist in get_god_abilities anymore.
Closes #2120.
=> Fix: don't list walljump twice while silenced

crawl-ref/source/dat/descript/mutations.txt
* To make style more consistent, this commit capitalizes stat names,
adds a missing serial comma, and replaces +Stealth with Stealth+.
* "Stab" has a special meaning for melee attacks, so replace it with
the spiked tentacle's attack verb, "pierce".
* Clarity blocking Rnd*Rage is a well-hidden mechanic, which is not
mentioned anywhere in the game, so let's fix this too.
=> text: fix, reword, and extend a few mutation descriptions

crawl-ref/source/spl-miscast.cc
As a followup to cf4520f7, this commit blocks nameless horrors from
Spellbinder under Okawaru or Sac Love.
=> fix: disable miscast-created allies when allies are forbidden

crawl-ref/source/spl-goditem.cc
... by letting it set ally targets correctly.
Also, tweak Smite's damage message to include attack strength punctuation.
=> Buff Beogh's Smite

crawl-ref/source/player-equip.cc
The item_name variable in _equip_weapon_effect() uses DESC_YOUR, so doesn't need "your" to be added later.
=> Remove a redundant "your" from a message.

crawl-ref/source/mon-ench.cc, crawl-ref/source/mon-poly.cc
At present, the bug described in #1935 still occurs in trunk.
dd09596130 made an attempt to fix this, but clear_far_engulf()
only applies to non-adjacent monsters by default.
This commit forces the engulf removal upon monster polymorph,
hopefully fixing the bug.
=> fix: really end engulf upon polymorph

crawl-ref/source/dat/clua/stash.lua
Searching for "fly" returned any equipment which gives flight, but not potions, and searching for "flight" returned potions and artefacts, but not boots of flying (as "find" searches artefact descriptions, but not ego item ones).
This change means that a search for "flight" finds everything. Searches for "fly" are unchanged.
=> Add "flight" to the stash search prefix for armour "of flying".

crawl-ref/source/acquire.cc, crawl-ref/source/species.cc
I was reading some Palentonga code to try to be less bad as them and
came across two things that looked like reasonable cleanups.
* Comment in acquire.cc suggests only nagas have increased chance to
acquire a barding but I think it applies to palentongas too since it's
based off you.wear_barding().
* wears_barding() checks the SPF_SMALL_TORSO flag instead of SPF_BARDING
which works because they both apply to the same species but I assume is
just coincidental.
Tested out trying to wear bardings and acquire a bunch on
nagas/palentongas and humans as a control and I don't think I broke anything.
=> A couple small barding cleanups

crawl-ref/source/item-prop.cc, crawl-ref/source/item-prop.h, crawl-ref/source/stash.cc, crawl-ref/source/stash.h
751e42844d described removing the const from a reference within seen_item() as a "major hack". 11 years later, fixing this involves removing the const from this function and one additional method, with no changes needed for stack_iterator.
=> Remove "const" from the parameter to seen_item().

crawl-ref/source/hints.cc
The call to is_feature('>', gc) will return true for a temporary portal because '>' is the command to use it, and it's not an altar. Not sure if that's the expected behaviour of that function or not, so didn't modify it. Instead, moved test for a portal entrance before that call so that portals are correctly identified in hints mode.
=> hint mode: prevent temporary portals being misindentified as downstairs

crawl-ref/source/l-moninf.cc
As with `is`, the `flags` function needs to init `mi_flags`.  Currently the function will fail until flags are initialized, which you can workaround by calling `is` first with a string, but that's silly.
=> bugfix: lua moninf_get_flags must init flags

.github/workflows/deps.py
I noticed there were some CI fails on running the llvm installation script, but there isn't any debugging information past that—this should improve that behavior.
=> Have deps.py print output of a command on fail

crawl-ref/source/skills.cc
With Abjuration gone, every spell in the Summonings school is inaccessible to
characters that have sacrificed Love to Ru. The skill is therefore useless to
them; we needn't bother allowing them to train it, and certainly shouldn't
offer manuals of Summonings from acquirement.
=> consider Summonings useless after sacrificing love

crawl-ref/source/form-data.h, crawl-ref/source/transform.cc
Currently, this form always displays "Storm fists" no matter the active species, despite tiles showing that the player character's anatomy is maintained in this transformation.
To be consistent with Statue Form and Blade Hands, this minor change uses the same logic used in Statue Form to fix this.
=> Storm Form should display weapon name as "Storm paws", "Storm tentacles" or "Storm fists" depending on species

crawl-ref/source/player.cc, crawl-ref/source/travel.cc
This PR fixes two travel trail-related bugs reported in #2081. These visual bugs happen because some events stop travel and clear delays *a bit* earlier than before.
=> Travel trail fixes (#2081)

crawl-ref/source/describe.cc
State in the description when a terrain blocks movement, but doesn't restrict reaching weapons or LOS_NO_TRANS spells.
At present, the former covers orcish idols, granite statues and malign gateways (the last only shows a description before the tentacle appears), and the latter also covers grates.
This knowledge could be useful for (e.g.) cheibrodos_spider_deadly_dance.
=> State when a terrain blocks movement, but not reaching or magic.

crawl-ref/source/spl-summoning.cc, crawl-ref/source/spl-summoning.h, crawl-ref/source/spl-util.cc
This commit disables the spell in the quiver and z/Z menu when there
is not enough space to open a gateway.
=> feat: allow checking if there is enough space for Malign Gateway

crawl-ref/source/spl-transloc.cc
Currently if you try to hop while frozen ramparts is active you get asked for confirmation before and after targeting.  This fixes that.  I tested hopping and blink scroll with barbed or ramparts statuses and it seems to do the right thing.
=> Fix double confirmation when hopping with frozen ramparts active

crawl-ref/source/player.cc
player::permanent_flight should not return true for temporary forms.
All forms appear to be temporary.
Resolves #1975.
=> Forbid temporary form lava/deep water exploration

crawl-ref/source/invent.cc
Trying to remove an amulet of faith (while worshipping a deity that cares about it) would trigger a confirmation to confirm your choice.
But there wasn't any confirmation like that for when you tried to put it on.
So I added a bit of code to a function so the game would ask the player if they were sure they wanted to wear an amulet of faith.
=> Check to make sure that the user wants to put on an amulet of faith.

crawl-ref/source/items.cc
This just re-uses the logic that was being used for wands, which also avoids the edge-case where if you floor-id something without using autopickup triggering (like when AP is disabled) then it was possible to have the item ID'd, marked as don't-pickup in `\`, and still picked up due to NEEDS_AUTOPICKUP_KEY set in its props.
The old code that led to this logic seems to imply there was an intentional hack for "previously-unknown items", but in testing, I found no unexpected behavior with the new version.
I also chose _not_ to merge the repeated code, as I unsure that it's too significant of an issue, and I have frankly no clue what the difference between the `if (fully_identified(item)) return false` and `get_ident_type(item) → return false` bits is in each of the branches.
=> fix: don't force picking up of newly IDd equipment

crawl-ref/source/jobs.cc, crawl-ref/source/main.cc, crawl-ref/source/newgame.cc, crawl-ref/source/newgame.h, crawl-ref/source/ng-setup.cc, crawl-ref/source/ng-wanderer.cc, crawl-ref/source/spl-book.cc, crawl-ref/source/spl-book.h
Wn is a really cool "random start" option, but has a couple annoyances. You can get some truly awful starts due to the way skill points are assigned, and are basically guaranteed to have awful stats due to the way stat points are assigned. This pr tries to rectify those problems and adds some new things that wn can get at game start. 
The new model assigns the equipment first, based entirely on species apts, then assigns stats and skills afterward depending on what we got. It tends to lead to more lopsided (ie useful) stat distributions and higher levels of skill in things that are useful, though these are by no means guaranteed.
Some new cool options I added:
- melee "good item" can get an upgraded base type or vorpal brand instead of enchant
- "good armour" can roll chain and "good …
=> Improve wanderers

crawl-ref/source/delay.cc, crawl-ref/source/view.cc
Change the "comes into view" messages to use the names the game normally uses for each monster by preference, rather than a name based on the monster type.
This is particularly noticeable with groups of dancing weapons or ugly things
Different names continue to be used when a lot of different monsters come into view at once.
This should fix bug #0012649.
=> Use the standard names for monsters in "comes into view" messages.

crawl-ref/source/describe.cc, crawl-ref/source/describe.h, crawl-ref/source/known-items.cc
This PR adds information about relative generation weights to the `\` screen. It'll look like this:
Also, it replaces strings like `It is found rarely compared to other types of scroll.`
with a more succinct `It is a rare scroll.` in item descriptions.
=> Display potion/scroll rarity on the item knowledge screen

crawl-ref/source/religion.cc
FIX. The game checked ignore_faith_reason() when a non-demigod puts on an amulet of faith, and checked is_useless_item() when one committed to a god. These give different results for artefacts (which are never considered "useless").
It now checks ignore_faith_reason() in both cases, and there is no special message when a character wearing an amulet of faith worships Ashenzari, Gozag or Ignis.
=> Stop artefact amulets of faith from flashing on first worshipping Gozag.

crawl-ref/source/beam.cc
The game doesn't warn the player when casting vampiric drain on natural monsters with immunity to negative energy.
I challenged Josephine to a vampiric drain duel, now all my familiy and friends are ashamed of me.
=> Check negative energy resistance when casting vampiric drain

crawl-ref/source/files.cc
When you climbed down a staircase while Xom was sliding them around, you could get the message " slides away from you right [...]". The stair was being described by feature_description_at which only uses the player map knowledge, which means the staircase would be DNGN_UNSEEN. This uses feature_description instead to get around that.
=> fix: moving staircases shouldn't be considered invisible

crawl-ref/source/beam.cc, crawl-ref/source/beam.h
Previously, if the phial of floods knocked a target back onto a non-floor or water feature like a staircase, then no flooding would generate at that location (fine) and consequently no waterlogging/engulfing (not fine).
Let's instead make create_feat_splash return a set of coordinates, and add back the center location before iterating over monsters to waterlog.
Closes #2331.
=> fix: phial should always engulf the center target

crawl-ref/source/describe.cc
If a bar was displayed of something with a negative value (like with EV) then text such as "EV: none (normally )" could be displayed. This is a bit odd, so let's make cases like that display "EV: none" instead.
I'm unsure if this breaks anything, but a bit of testing didn't show anything unexpected. The function isn't used for much besides showing player accuracy in `_player_spell_stats` (which seems to only be called when accuracy isn't -1) as well as monster EV, will, and AC.
Before:
After:
=> fix: display_bar should clamp negative values

crawl-ref/source/god-conduct.cc, crawl-ref/source/view.cc
Fully exploring the Slime Pits is a risk-free and tedious way of getting exploration piety under Jiyva. Let's not give players an incentive to do this.
=> Don't grant free piety to Jiyva worshippers

crawl-ref/source/god-item.cc
An orb of energy is primarily used for enhancing spellcasting, so it
makes sense that it should be considered a wizardly item and thus that
Trog should frown upon its use.
=> fix: make Trog tantrum if orb of energy is used

crawl-ref/source/Makefile, crawl-ref/source/crash.cc, crawl-ref/source/endianness.h, crawl-ref/source/files.cc, crawl-ref/source/initfile.cc
This patch is currently being used in the official Haiku package repo (https://github.com/haikuports/haikuports/pull/6114, https://github.com/haikuports/haikuports/pull/6118)
[This patch](https://github.com/Crestwave/haikuports/blob/65ca2d9c37210996f9f7f91b3cbdb339f12b79cb/games-roguelike/crawl/patches/crawl-0.27.0.patchset) can alternatively be used if it's too messy splitting the documentation from the data directory
=> fix: add support for Haiku

crawl-ref/source/dgn-overview.cc
The keybinds shown on ctrl-o were outdated, this aligns it with how
help lookup currently works.
=> fix: lowercase help lookup on ctrl-o

crawl-ref/source/main.cc
Currently, when a Felid has two lives, the related Experience Info message is off by one. E.g., at level 10 with 2 lives, it reads, "If you died right now, you'd get an extra life in 1 levels' worth of XP." If you died at that moment, however, you'd need to gain two levels to get another life.
This fixes the Experience Info to display the correct number of levels needed to gain another life following death when you currently have two lives.
=> when felid has 2 lives, fix Experience Info to show actual died-now xp needed

crawl-ref/source/dat/des/portals/trove.des
In the past year, identification scrolls have become increasingly less
important as gear now is automatically identified, and never cursed.
By the time players get into a trove, they generally will have no
further use for scrolls of identify, so those should be removed from the
good_scroll table. In their place, we now have immolation scrolls, which
are a fun tool for safely fighting large armies, and torment scrolls,
so that these troves can be just as fun for demons/undead as they are
for other species. These two additions are equally as common as scrolls
of holy word.
(20 weight of identify has been replaced by 16 weight of new scrolls, so a mere 4 weight is now evenly distributed among the remaining scroll types, which have a combined weight of ~~95~~ 96. edit: seems that these …
=> Remove identification scrolls from troves

crawl-ref/source/windowmanager-sdl.cc, crawl-ref/source/windowmanager-sdl.h, crawl-ref/source/windowmanager.h
Fixes #898
The issue was caused because `SDL_GetModState` returns an OR'd combination of the modifier keys, but `SDLWrapper::get_mod_state` was comparing against the exact values of the flags.
=> fix: click + key modifier detection in tiles

crawl-ref/source/webserver/requirements/dev.py3.txt
This is required to run the server on Python 3.10+
=> Update typed-ast to 1.4.3

crawl-ref/source/mon-info-flag-name.h, crawl-ref/source/mon-info.cc, crawl-ref/source/mon-info.h
Most of the reasons for a monster_info having MB_DISTRACTED give a description when the monster is selected on the level map, but not all.
This creates two flags to fill in the gap.
- Monsters which you can see, but which can't see you because of invisibility, are described as "can't see you" in the examine surroundings command and monster list summary.
- Monsters which are distracted (possibly because they are attacking a summoned monster rather than you) ar described as "not watching you" or as "distracted".
=> Add annotations for distracted monsters.

crawl-ref/source/delay.cc, crawl-ref/source/religion.cc, crawl-ref/source/religion.h, crawl-ref/source/spl-book.cc, crawl-ref/source/tilereg-mem.cc
This changes the meaning of "blue spell at the top of the list" from "spell Vehumet is offering you" to "spell which is only available because Vehumet is offering it to you". Vehumet can withdraw the offer, but you cannot lose the book.
This change doesn't affect the religion screen.
This change means that:
1. The memorise spell list is in order of difficulty except when there's a spell on it which Vehumet is providing. It's easier to look through the list when the spells are in order of difficulty.
2. The game shows the player which spells are only available because Vehumet is offering them. Until the last set of spells, this gives the player a motive to learn (say) LRD now as it may be useful later on. As things stand, someone using the default options has no easy way to check if a …
=> Don't highlight spells Vehumet offers if you've read a book about them.

crawl-ref/source/describe-spells.cc, crawl-ref/source/spl-damage.cc
There is an inconsistency with damage numbers. According to the monster utility, radroaches can do `3d25 / 3d26` damage with Irradiate. Monster descriptions show only one formula, though. Half of the time it will be `3d25`, and in other cases it will be `3d26`, even for the same radroach.
What would be the best way to address this?
For posterity:
> PleasingFungus: correct fix is to pass a random bool to the damage func and do false for the ingame monster damage desc
=> Display Irradiate damage in monster descriptions

crawl-ref/source/mon-ench.cc
The player can see invisible monsters which are bribed, charmed or hexed. When the status is lost, the monster may suddenly vanish.
This changes the message this generates from "You can no longer detect the Sigmund." to "You can no longer detect Sigmund.". The "the" is retained for non-unique monsters.
monster::add_enchantment_effect() is unaffected by this. It inserts an adjective before the monster name, so the "the" is acceptable.
=> FIX Remove an erronous "the" from a message.

crawl-ref/source/dat/des/branches/pan.des
I have reached my apotheosis: I have put a rune in a shop.
Since the demonic rune repeats if you don't pick it up, I figured it
would be the best option for a rune shop. (The abyssal rune also
reappears if you don't pick it up, but the theme is easier to fit into
Pandemonium.) If you already have the rune, the shop instead places
randarts of various kinds.
Out of 25 generated shops, the stats on the price of a demonic rune:
Minimum: 3804
Maximum: 8647
Average: 6640.76
St Dev:  1412.1
The vault also places fat stacks of cash, three other shops, and
demon-summoning monsters from other branches as visitors. Enjoy!
=> Add the most nicolae demonic rune vault possible

crawl-ref/source/mon-act.cc
When a monster uses a scroll or potion, it identifies the consumable and applies autoinscriptions. But unlike other methods of item identification, it didn't change inventory letters according to the ``item_slot`` option.
=> fix: apply item_slot when seeing monsters use unid'd scrolls or potions

crawl-ref/source/mutation.cc, crawl-ref/source/output.cc, crawl-ref/source/player-reacts.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/spl-transloc.cc, crawl-ref/source/stairs.cc
This PR adds some indication that teleportitis is suppressed in the Abyss to the mutations and character overview screens.
Also, it marks teleportitis as inactive on the ``A`` and ``%`` screens in more cases.
=> Fix teleportitis-related messaging and status display

crawl-ref/source/abyss.cc
It's basically a spoiler that an exit always generates near the AK
starting spawn.  If the player doesn't know that, they'll waste a fair
bit of piety using Depart the Abyss.  That could be fine, except that
now that means their starting escape mechanism, Bend Space, will be
offline for the first few levels of the Dungeon, defeating the purpose
of bumping AK piety to make it available.
Guaranteeing that the exit generates in LOS requires that the player's
LOS be known at the time we're generating the pseudo-abyss, so I had
to move the initial call to update_vision_range.  (Otherwise it
wouldn't work for Kobolds)
=> feat: guarantee that AK starting exit generates in LOS

crawl-ref/source/player-reacts.cc
There are two different attunement messages for items with Regen. The
first one is displayed when a character puts on such item while at full
health. When an injured character puts on an item with Regen and then
reaches full health, the second message is printed.
The first attunement message was fixed in 68df51542, and this commit
fixes the second one.
=> fix: further fix grammar for artefact bardings with Regen

crawl-ref/source/evoke.cc
Continuing with the removal of restrictions on attacking frenzied monsters, let the pieces affect insane enemies.
=> fix: let pieces from Xom's chessboard affect frenzied monsters

crawl-ref/source/mutation-data.h
Add spaces between the stat names and the numbers (to be consistent with
all the other similar mutation descriptions) and change Int/Str to Str/Int
for consistency with the order of the stats in the ui and elsewhere.
=> Stat mutation description adjustment

crawl-ref/source/dat/des/variable/mini_features.des
Add several small vaults which use transporters in ways besides just
setting off an optional murder zone. Some, with "diode" in their names,
allow the player to only move in one direction down one or more hallways.
The others just make weird intersections.
=> Add several small vaults containing transporters to mini_features.des

crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/util/monster/monster-main.cc
Primarily so that damage can be displayed in future. Don't rely on division by
power to recur, just caclulate the number of arcs to do upfront and do them at
full power. Additionally, random round all of the formulas to avoid messy power
breakpoints. New numbers give mostly similar damage at low power, I think.
At high power with a lot of targets things can get a bit wilder. If it's a
problem, can cap power at 50 instead of 100.
I didn't actually make a commit to display damage yet, will do that later probably.
=> Rework the static discharge formulas

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc
This might subtly hint to newer players that things have
gone awry sooner.
Before: yellow at 50%, red at 25%.
Now: yellow at 70%, red at 40%.
With devteam approval, I'd also like to set other warnings a bit higher, like hp_warning, mp_warning, autofight_stop.
=> Onboarding: set hp_colour to higher defaults

crawl-ref/source/dgn-overview.cc
Different gods forbid worship from different species (some despise undead, some abhor djinn, Beogh can only stand orcs and everyone hates demigods).
This change gives a way for the player to check which gods are available, and hides irrelevant information about whether an unusable altar has been found.
This list only changes during a game when a character sacrifices love to Ru. This seems fine to me.
=> Only list gods you can ever worship in the dungeon overview & dump.

crawl-ref/source/english.cc
In Australian English there is an "and" after "hundred" in numbers
of this kind. (Source: I asked all the Aussies I know.)
=> Correctly produce strings of the form "one hundred and one"

crawl-ref/docs/options_guide.txt, crawl-ref/source/Makefile.obj, crawl-ref/source/explore-greedy-options.h, crawl-ref/source/initfile.cc, crawl-ref/source/options.h, crawl-ref/source/stash.cc
explore_greedy_visit is added as an rc file option to adjust explore_greedy behavior. By default greedy explore travels to piles of items on each square in addition to items that are eligible for autopickup. This setting allows to also/only go to enchanted items instead. By choosing "enchanted" greedy exploration will ignore piles of mundane items and only visit the squares which contain
enchanted items. Choosing "both" will visit piles and singular enchanted items.
=> Allow adjusting of explore_greedy non autopickup item visit method

crawl-ref/source/spl-util.cc
Allow Poisonous Vapours to work under `-Clouds`, since as of 3f0e5c0cc there are no clouds involved.
=> fix: allow Poisonous Vapours to work under Still Winds

crawl-ref/source/dgn-overview.cc
As a followup to ed30ed24e, this commit fixes column alignment in the two-columns mode.
There wasn't enough space for branch names:
=> fix: tweak spacing on the dungeon overview screen

crawl-ref/source/tilemcache.cc
This commit fixes shield offsets for the following monster tiles:
* deep elf pyromancer, zephyrmancer, and demonologist;
* spriggan berserker and air mage.
Before and after:
=> fix: tweak shield offsets for several elves and spriggans

crawl-ref/source/mon-data.h
Now that each classed drac maps neatly onto a base drac color, it's silly for the white draconian stormcaller to be brown, or for the black draconian knight to be cyan.
=> Make classed draconians match their base color

crawl-ref/source/beam.cc
…by letting them use their starting spell without creating hostile skeletons.
=> Buff Necromancers of Okawaru

crawl-ref/source/god-abil.cc
Since Meteorae can become invisible only via the shadow form, there is no point to offer them petitions with the invisibility potion.
=> fix: don't offer Meteorae potion petitions with invisibility

crawl-ref/source/ui.cc
```
ui.cc:2174:9: warning: variable 'ew' set but not used [-Wunused-but-set-variable]
int ew = 0;
^
```
=> Remove unused variable

crawl-ref/source/dat/des/branches/temple.des
I suspect this TAG typo is preventing the level builder from choosing this map.
=> Permit a Temple map to actually be placed.

crawl-ref/docs/options_guide.txt
This breaks the corresponding help dialog in small screens.
Bug introduced in f02deff4a79ecda93b89ecfb91e49eea323dc6f2.
Credit to the Android player who reported the bug.
=> Fix missing newline in the options guide

crawl-ref/source/movement.cc
* Allow rampaging towards frenzied enemies. Treat them like regular hostile monsters.
* Disallow rampaging towards projectiles. The player cannot voluntarily move into an orb of destruction when it's right next to them, but it's possible to rampage into an orb if it's two tiles away.
=> fix: tweak valid targets for rampaging

crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/describe.cc
As per title.
Also documents Sticky Flame's inability to stick to insubstantial monsters.
This is a needed change because currently insubstantiality of monsters is highly spoilery, and I still need to check the wiki on occasion to see if a monster will be affected by e.g. roots.
=> Documents insubstantial in the monster x-V view

crawl-ref/source/webserver/game_data/static/action_panel.js, crawl-ref/source/webserver/game_data/static/cell_renderer.js, crawl-ref/source/webserver/game_data/static/dungeon_renderer.js, crawl-ref/source/webserver/game_data/static/util.js
This commit reverts 3925e268bea408. (And could use some eyes because of this.)
To get hidpi to work in a browser canvas object, the internal dimensions
need to be twice that of the external dimensions (essentially). The
normal way of implementing this is to multiply the internal dimensions
by devicePixelRatio, and scale the canvas accordingly. We used to do
this, but 3925e268bea40 changed things so that the external dimensions
were halved. This was, according to the commit message, in order to
prevent scaling artifacts on firefox. (Where the salient fact is that
window.devicePixelRatio on some browsers, these days including
chrome/firefox but not safari, also changes with browser zoom.) However,
a consequence is that tile rendering is halved on hidpi devices, exactly
not what should …
=> fix: correct webtiles hidpi implementation

crawl-ref/source/l-you.cc
The lua `you` object has almost everything else you can see in the HUD, but it's lacking `ac`, `ev`, and `sh`.  This PR adds those stats.
=> Add `ac`, `ev`, and `sh` functions to the lua `you` object.

crawl-ref/source/mon-abil.cc, crawl-ref/source/mon-cast.cc
Sheltering orbs of destruction from injuries does nothing, but ironbound preservers do it anyway.
Friendly guardian golems are so friendly, they protect even hostile OoDs. This happens because of how `mons_aligned()` treats all projectiles.
=> No shelter for projectiles

crawl-ref/source/describe-spells.cc, crawl-ref/source/mon-cast.cc, crawl-ref/source/mon-cast.h, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/util/monster/monster-main.cc
This PR caps the ally-dependent part of Resonance Strike damage and adds the damage numbers to the `xv` screen.
=> Resonance strike damage tweaks

crawl-ref/source/item-name.cc, crawl-ref/source/item-use.cc, crawl-ref/source/tileweb.cc, crawl-ref/source/tileweb.h, crawl-ref/source/webserver/game_data/static/action_panel.js
This PR adds better indication for currently useless items. If you can't use a consumable, it'll be greyed out on the action panel. There are already a lot of uselessness checks, but the second commit makes them more consistent and adds a few new ones. Also, there's a bonus bug fix in the third commit.
=> Add some uselessness to the action panel

crawl-ref/source/l-crawl.cc
Currently crawl.sendkeys(6) sends "6" instead of keycode 6.
Due to lua_isstring(int) returning true; ints treated as strings.
Moved number check else block ahead of lua_isstring() check.
Made number check explicit; lua_isnumber() can return True for strings.
=> Fix int params to crawl.sendkeys()

crawl-ref/source/acquire.cc, crawl-ref/source/item-prop.cc
See commit messages for details. The second commit sprinkles in some extra asserts in case that's also desirable, but I'm not a huge fan of how it only checks subtypes for weapons, since I can imagine this bug coming up in other situations.
Maybe probably hopefully fixes #2714.
=> Don't crash on reading acquirement scrolls

crawl-ref/source/dat/des/branches/lair.des
An absdepth conditional was placing a harder monster set at shallower depths. This flips the condition, and also makes the transition point L:3 instead of L:4, which I think seems in line with the recent reduction to 5 floors.
=> fix: adjust monser placement in wad_wood_setup.

crawl-ref/source/item-use.cc
After 4b7bca3bf, unidentified perma-useless scrolls are greyed out in the read menu. This affects ?butterflies and ?summoning for followers of Okawaru and ?teleport and ?blinking for Formicids. Also, it's not possible to read-identify permanently useless scrolls.
Fix this by checking perma-uselessness only of identified scrolls.
Closes #2877.
=> fix: don't leak usefulness of unidentified scrolls (#2877)

crawl-ref/source/shopping.cc
The menus have been showing temp uselessness of items for a long time. For example, potions of invisibility were greyed out for characters with enough magic contamination even in previous versions.
As a followup to 43e804b48, use perma-uselessness highlighting for these menus.
=> fix: show perma uselessness in shop and shopping list menus

crawl-ref/source/stash.cc
Currently altars are always included in stash search results as "useful" even if the player could never use them, i.e. by playing a Demigod.
This change simply adds a check to the dedup/useless filter to filter these out. Since the predicate got so big I also thought it merited refactoring out into its own helper function.
=> feat: Filter out useless altars from stash search

crawl-ref/source/attack.cc, crawl-ref/source/beam.cc
It's a very annoying interface tax without sinv. To replace it, increase the odds of agility for the beam version and add a chance of resistance for both beam and attack flavor versions.
=> remove invisibility from chaos effects

crawl-ref/source/player.cc
If you wear an amulet of magic regeneration, it's possible to cast Momentum Strike and then restore MP before -Move times out. Pressing `o` will just print "You cannot move." and you'll have to use `5` or `.` to rest -Move off.
Fix this by making autoexplore wait for -Move to expire before attempting to move. Tree form and Stuck status from Translocations miscasts also prevent autoexplore, so let's fix these cases too.
=> fix: make autoexplore wait for movement restrictions to expire

crawl-ref/docs/options_guide.txt, crawl-ref/source/stash.cc
Autoexplore does a lot of unnecessary item piles revisits now. For example, if you kill a monster that has a dagger of freezing, a plain +0 hat, and an artefact, autoexplore could visit the resulting pile of items up to four times. These (re)visits happen after
1) you kill the monster,
2) you apport the dagger,
3) the monster's corpse decays,
4) a Jiyva jelly eats the hat.
This PR fixes unnecessary revisits 2), 3), and 4).
Also, it reduces the number of unnecessary autotravel interruptions by ignoring piles of useless items during greedy explore.
=> Make greedy explore less greedy

crawl-ref/source/hiscores.cc
buffer size changed from 1300 to 1500.
P.S. my converted megaziging character from .26.1 got 1300+ characters string in highscores. Mouseover causes to crash
=> fix: highscores crash on stats-heavy characters

crawl-ref/source/dat/des/altar/overflow.des
Imagine my delight when I stumbled upon my very own vault in an online game, and then my abject horror when the wand, which really ties the whole room together, was missing!
I tested the game seed (4877243199622027174) locally and found that the wand had been placed correctly, so unless there are some possibilities I don't know about I think it's likely that a monster waltzed in and walked away with it.
=> fix: Make a flavor gimmick wand no_pickup

crawl-ref/source/form-data.h
Fixed #2742, changing front legs to front pincers, which we could also call Pedipalps if we wanted to follow more closely with real anatomy. Venomous is the more commonly used term for things that can poison, and technically is the right term here, so let's be consistent.
=> Tweaking spider text labels to be more consistent

crawl-ref/source/dat/descript/spells.txt
Pain still exists as a monster spell, and is inaccurately described as causing a minor backlash.
This fixes that.
=> Update description of Pain

crawl-ref/source/mon-death.cc
Killing bigger monsters gave you longer gold aura duration, which is mechanically weird (also not great that you could pseudo-count the duration by looking at the size of a gold stack that dropped!) Just roll independently instead, choosing numbers roughly equal to the case for human size. Gold amount being tied to corpse size is also weird in a post-chunk universe, but the gameplay implications there are mostly fine and it would be a significant balance change to decouple it - worth looking at if gozag needs another nerf, but I've left it alone for now.
=> decouple gold aura duration and corpse size

crawl-ref/source/tilereg-tab.cc
Andoird branch merge broke some menu height calculations. Options.tile_sidebar_pixels is 32px by default, so wouldn't affect rendering in all cases but then tile_sidebar_pixels is actually changed.
=> fix: local tiles sidebar height

crawl-ref/source/tilesdl.cc
We were using the m_fonts array to get the font sizes. This is wrong because caching leads to unpredictable array contents.
Now we are using proper char width and height. It also has the benefit of improved precision.
The bug was reported in reddit:
https://www.reddit.com/r/dcss/comments/107d1tj/what_has_changed_with_the_ui_trunk_compiled/
=> Fix estimation of the minimum usable window size

crawl-ref/source/describe.cc
Add space to fix description text.
=> added leading space to text message on uselessness

crawl-ref/source/chardump.cc
Since Djinn don't memorize spells or keep track of spell levels, I found this line confusing in my morgues.  (This PR strips out the "You couldn't/cannot memorise any spells." line for the same reason, since it's the same line.)
If this breaks some sort of parsing or is otherwise not desired, I could also tweak it to always say "You couldn't/cannot memorise any spells." instead.
=> Remove the "You had/have # spell level(s) left." line from Dj morgues

.github/workflows/ci.yml, crawl-ref/source/Makefile, crawl-ref/source/android-project/build.gradle
- Fix Github Actions deprecation warnings. 
* The current ccache action cannot be updated, it has been replaced with the most starred one. This obsoletes the cache action and the  manual ccache stats management.
* Update the checkout action to v3.
* Update the setup-python action to v4.
* Update the codecov action to v3.
* Replace the obsolete set-outputs commands with the new GITHUB_OUTPUT environment file.
- Update the Android Gradle plugin and use a compatible Gradle version.  This improves the build times and fixes the SDK XML related warnings.
- Ccache doesn't get hits on Android because the compiler's mtime  is different in every build. Change the compiler check strategy to  content.
- Proper fix for 093205a. I'm very sorry for that.
- Use the Maven Central repository instead of the …
=> Fix and improve CI builds

.github/workflows/ci.yml
The new ccache action adds a prefix and a timestamp suffix to the cache key by default. We are also adding another prefix and suffix in the workflow configuration. This doesn't work as expected in most cases so this commit removes the extra pre/suffixes from the configuration.
=> Fix ccache caching

crawl-ref/source/chardump.cc
The ability to highlight notes in different colours in the "browse character notes" display (constrolled with the menu_colour option) was lost with a02aae867c.
This returns it, but with one small change. If a note is too long to display on a single line of the display, the colour is chosen based on the whole note, instead of assessing each line of output separately.
The immediate effect on the user will be that "Reached XP level"
notes change from grey to white. The setting in [menu_colours.txt](https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/defaults/menu_colours.txt) is
still there.
=> FIX: Make the "browse character notes" screen obey menu_colour.

crawl-ref/source/evoke.cc, crawl-ref/source/god-item.cc
Good gods currently get upset only when condenser vane rolls Negative Energy clouds. The chance of rolling Negative Energy clouds is somewhere in the vicinity of 1/1000 at 0 evocations, rising dramatically as evo skill increases. This creates an odd incentive to not skill evocations.
Squashing negative energy clouds (as opposed to rerolling) was chosen to be the minimum change that resolved the problem, though rerolling instead is also sensible.
=> Make condenser vane good god approved

.github/workflows/ci.yml, .github/workflows/deps.py, crawl-ref/source/debian/control, crawl-ref/source/debian/rules
1. I made a fix for an old issue: #1344.  The implementation is very similar to the one used in the Fedora packages. While testing, I found two errors in release workflows.
2. AppImage builds can't run linuxdeploy because FUSE 2 is not available by default. The GitHub runners must have changed, they're probably using FUSE 3 now. The solution is easy because v2 is still in the repos and can be installed alongside v3.
3. The migration from the obsolete set-output commands in 94e0f26 was incorrect. My fault, sorry :disappointed:
Closes #1344
=> Three fixes for release CI workflows

crawl-ref/source/art-func.h, crawl-ref/source/item-use.cc
Some assorted Victory bugfixes that I ran into when looking into PF's meld bug; please see the commits for details.
fix: don't reset victory stats on meld
fix: reset victory stats when quaffing lig
fix: don't reset victory for cancelled scrolls
=> fix: a few victory bugs

crawl-ref/source/dat/des/builder/shops.des
nicolae, making shop vaults? How surprising!
Most of these are simple generic shop vaults, intended to help increase the amount of simple, non-gimmicky shops to increase variety a little. Also increase the weight on the very basic "shop" vault, so that simple one-tile shops get a little more representation. There are also a couple of multi-shop vaults.
I told myself I was just going to stick to simple, non-themed vaults, with no specially-defined inventories, but during a discussion where memes of antiquity came up, I was inspired. (And then after I broke the "only simple vaults" rule, I was inspired again, this time by one of my other shops.)
=> Add some new shops to shops.des

crawl-ref/source/fight.cc, crawl-ref/source/melee-attack.cc, crawl-ref/source/quiver.cc
Rift breaks the assumption that the only number besides two is one. This removes said assumption.
However, it still makes the assumption that every REACH enum is just an int with a fancy title. This will break spectacularly if a weapon is ever given a reach that isn't just a number.
Fixes #2683
=> adjust fight.cc to work when recieving cleave while wielding rift

crawl-ref/source/dat/des/builder/layout.des
Make layout_misc_corridors sometimes use boxy=false when in Lair.  This provides a more "natural" look than the square rooms it generates otherwise, and works well with Lair ruination.  As a bonus, it also creates more crevices for the player to hide in.
=> Edit layout_misc_corridors in Lair

crawl-ref/source/dat/des/branches/vaults_rooms_empty.des, crawl-ref/source/dat/des/branches/vaults_rooms_hard.des, crawl-ref/source/dat/des/branches/vaults_rooms_standard.des
Includes vaults for _empty, _standard, and _hard. I looked over the existing vaults, but Vaults vaults tend to have a simpler variety than other vaults because they tend to use a reduced glyph set. If I've accidentally duplicated some other existing vault, my apologies. Unless I've accidentally duplicated one of my own vaults, in which case I absolve myself completely of all wrongdoing.
=> Add a diverse assortment of Vaults vaults

crawl-ref/source/skills.cc
This means that a lua hook which catches the message can change the skill target for the relevant skill (imagine a script which sets an Axes target at 3, and sets it to 4 when it reaches 3). Previously, the game set the target to 0 after the message returned, whether or not the skill was still at its target.
=> Clear the training target before the message, rather than afterwards.

crawl-ref/source/arena.cc, crawl-ref/source/libunix.cc, crawl-ref/source/main.cc, crawl-ref/source/output.cc, crawl-ref/source/ui.cc, crawl-ref/source/viewgeom.cc
Changes in the terminal size are very likely to make Crawl crash or misbehave. This small set of patches attempts to improve this situation.
Closes #1497
Closes #3045
Closes #2311
=> Improved resilience when terminal size changes

crawl-ref/source/directn.cc, crawl-ref/source/lookup-help.cc
This resolves any confusion between them, and fixes #2824.
This is apparently what you do if you only want a class to be used in its own .cc file.
I also deleted some code which a comment said was to do with DescMenu being an InvMenu. It shouldn't be needed as that DescMenu isn't an InvMenu.
=> FIX: Put both DescMenu classes in unnamed namespaces.

.github/workflows/ci.yml, .github/workflows/debian_changelog.py
- Debian packages will be included in the standard release as a single .tar.xz file.
- Allow any version format in Debian packages so the workflow can be executed in beta releases.
- New workflow added for source packages.
=> Changes in release CI workflows

crawl-ref/source/mapmark.cc, crawl-ref/source/mapmark.h, crawl-ref/source/tag-version.h, crawl-ref/source/terrain.cc, crawl-ref/source/terrain.h, crawl-ref/source/tilepick.cc
**Fix 1: Save flavour in terrain-change markers**
Temporary terrain changes that replace walls (summon forest spell) are
not being properly reverted on wizlabs and some vaults with custom
walls. This change solves the problem by saving the old feature flavour
in the terrain-change markers.
**Fix 2: Fix the description of walls with unseen changes**
If a wall is changed but we haven't seen the new state yet, the
description shows the tile for the base wall without flavour.
Closes #2052
=> Let's fix the summon forest spell in wizlabs

crawl-ref/source/dat/defaults/misc.txt
Resolves issue #3139. This makes the default auto-exclude behavior for strange machines consistent with other dangerous stationary monsters like oklob plants, statues, etc.
=> Auto-exclude Strange Machine by default

crawl-ref/source/tilesdl.cc
Prevents the current scale to be much higher than the maximum zoom. Otherwise zoom out stops working until a lower value is reached again.
=> Fix zoom out

.github/workflows/ci.yml
a9a6e9e7af1 and ea43df2a32 removed a step that was probably intended to work around https://github.com/actions/checkout/issues/290 and https://github.com/actions/checkout/issues/882, but broke the CI build if anyone used a lightweight tag (because these fetch lines actually shallow the tag depth to 1). This commit attempts to thread the needle by making this workaround conditional only to releases, where (if the person doing the release has followed the steps correctly), there is guaranteed to be an annotated tag at depth 1 in the tag history. (If I'm parsing the checkout bugs correctly, they only trigger on a tag action anyways.)
=> build: workaround for an actions/checkout bug

crawl-ref/source/initfile.cc
Resolves issue #3133 . I think there was simply a typo/oversight to put `tile_weapon_offsets_option` instead of `tile_shield_offsets_option`. Either way, the `tile_shield_offsets` option now works as far as I can tell.
Here is an example with `tile_weapon_offsets = 20,10` and `tile_shield_offsets = -20,-10`
=> Fix tile_shield_offsets option

crawl-ref/source/dat/des/branches/slime.des
slime_pit: The main change was splitting out the various functions for making the clear walls disappear when TRJ dies. I also removed some downstairs glyphs, which were in there for some reason. I removed the "no_dump" tag, since now that there are variants, players might want to see which one they got. I also trimmed some excess walls off the edges to get the width less than 70 tiles, allowing the vault to be rotated, and accordingly removed the "no_rotate" tag.
slime_pit_nicolae_amoeboid: A variation on the basic slime_pit theme -- stairs near the outer edge of slime walls, with stone, loot, and TRJ in the center. The slime walls and loot boxes are of course shaped differently, and the corridors in between them here aren't as narrow as in slime_pit original recipe. …
=> Add some new Slime Pit endings

crawl-ref/source/dat/des/altar/overflow.des
Fixes: #3196 
- remove unneeded "\" from beargit_hepliaklqana_dungeon_heroes
Seems like a typo from commit that removed monster potions https://github.com/crawl/crawl/commit/e8cad7f256b05d460fdf43d9ebf327ed34a94874
=> fix vault formatting

crawl-ref/source/dat/descript/items.txt
Just a small inconsistency I noticed.
=> Correct reference to "caster" in granite talisman's description

crawl-ref/source/artefact.cc
The case for 'orb' was missing from _get_artefact_type, meaning it's name would not reference it's orbiness, defaulting to it's artefactitude instead.
This corrects that, even though it is perhaps the world's most trivial omission.
=> Make artefact orbs use slightly orbier names

crawl-ref/source/mutation.cc
As it stands, if an armataur gets hooves 3, any barding they're wearing will be forced off – but then they can immediately put it right back on.  As I understand it, the intended behavior is the latter, since bardings don't go directly over the feet, so this PR prevents them from falling away.
Test:
* Start up a game as an armataur
* Enter wizmode (<kbd>&</kbd> <kbd>yes</kbd> <kbd>&nbsp;</kbd>)
* Get a barding with <kbd>&</kbd> <kbd>o</kbd> <kbd>[</kbd> <kbd>barding</kbd> <kbd>&nbsp;</kbd> and wear it
* Ask for hooves 3 with <kbd>&</kbd> <kbd>]</kbd> <kbd>hooves</kbd> <kbd>3</kbd>
* If you haven't applied this PR:
* See "Your +0 barding falls away!"
* Put your barding back on
* If you have applied this PR:
* You now have hooves and are still wearing your barding
=> Hooves and talons shouldn't force bardings off

crawl-ref/source/mon-cast.cc
As far as I can tell this no longer deals even nominal amounts of damage, so it's a waste of a turn.
=> fix: don't meph cloud rpois players

crawl-ref/source/transform.cc
Previously storm form would breakpoint EV bonus at integer skill. This fixes that.
=> Remove Storm Form breakpoints

crawl-ref/source/tilepick.cc
In depth write-up of the cause of #3225:
Gauntlet portal would be leaked by magic mapping via a scroll of magic mapping/revelations and then examining shop/portal tiles. The bug can be reproduced by setting PLACE: D:2 on the gauntlet entrance vault, and then descending to the second level of the dungeon. Simply placing the gauntlet entrance tile in wizard mode, and then clearing map knowledge does not repro the bug; the custom lua script in gauntlet.des is what causes the leak.
gauntlet.des uses the dgn.til lua function, which leads to tile_env.flv(pos).feat being set when laying out the gauntlet entrance vault in a level. tile_env.flv(pos).feat can override env.map_knowledge(pos) in tileidx_feature, which is used by the describe popup to select the appropriate tile.
This commit prevents …
=> Updated tileidx_feature to prevent override of DNGN_UNKNOWN_PORTAL

crawl-ref/source/describe.cc
An in-game description was saying "It isextremely good for stabbing". Fix the typo.
=> Fix typo: "It isextremely good for stabbing"

crawl-ref/source/describe-god.cc
While it's not technically penance, Descent's debt mechanic is close enough to justify giving out Gozag's penance title.
=> Reallow gozag title for excessive spenders

crawl-ref/source/monster.cc
Maurice's sleight of hand may go unnoticed by a player; leaving a player who escaped confused by their mysteriously light pockets. Note the appropriation in the dump/morgue to help players find their missing loot.
Having things stolen is funny so recording this also makes for more interesting morgues.
=> feat: Note when Maurice steals items/gold

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc, crawl-ref/source/libunix.cc, crawl-ref/source/options.h
Use the terminal's default foreground and background colors. This can be used to enable a transparent background.
Closes #2534
=> New option use_terminal_default_colours

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc
The max memory in MB allowed for user Lua scripts is only configurable via command line options. Setting this value in the init file can be useful in platforms where the command line is not available, e.g. Android.
=> New init file option: lua_max_memory

crawl-ref/source/god-abil.cc
If there are lost souls in LOS when Grand Finale is used, one may create a new monster where the exploded one had been, causing a crash. Catch this and take the fallback path.
=> prevent a Grand Finale crash

crawl-ref/source/ghost.cc
Since red very ugly things don't have sticky flame anymore, it shouldn't be referenced when giving them their resists, either.
=> Remove spurious sticky flame reference in _ugly_thing_resists().

crawl-ref/source/wizard-option-type.h
The wizard option is defined in NOWIZARD builds. Define an enum it relies on then.
Compiling with NOWIZARD on gcc highlights a few unused parameters and unused functions, but I've left those.
=> Fix compiling with NOWIZARD.

crawl-ref/source/beam.cc
When the player is vitrified more by BEAM_VITRIFY_GAZE, there's a message for that. However, there isn't one for when the player is vitrified more by BEAM_VITRIFY. This fixes that.
Also, the monster messages for becoming as fragile as glass end in "!" in one place (Killer Klowns' clear moon pies), and "." in two others (the vitrify beam and the vitrifying gaze beam). This makes them all use "!", especially since vitrification does more damage now.
=> Fix inconsistencies in vitrify messages.

crawl-ref/source/god-blessing.cc
Now with a short-enough commit message, and without the breakage of the last attempt.
=> Fix warning if Beogh can't give an orc an orcbow.

crawl-ref/source/dat/database/monspeak.txt
Move the old Transmutations dialogue to Shapeshifting, and put the Poison Magic dialogue under Alchemy.
=> Recycle dialogue for alchemist player ghosts.

crawl-ref/source/spl-damage.cc
Makes lightning rod check against half AC rather than proportional AC. This change follows in a push to make lightning damage always ignore half AC, and also removes an inappropriate usage of proportional AC.
This is a buff, but it's unclear to me to what degree, as lightning rod damage code is fairly opaque.
=> Make Lightning Rods use half AC

crawl-ref/source/potion.cc
Missing parenthesis meant potion of cancellation was accidentally giving you contamination most of the time.
=> Fix !cancellation contamination (The Unspeakable)

crawl-ref/docs/changelog.txt, crawl-ref/source/dat/descript/spells.txt
The spelling changes consistently make the plural of "simulacrum" "simulacra".
"Simulacrula" is used in a few places, but "simulacra" is most commonly used, and matches what's used in-game (cf. english.cc:pluralise()).
=> Fix typos and spelling.

crawl-ref/source/mon-clone.cc
Ghost demon monsters can now be cloned. As for the others, named monsters still aren't clonable, which rules out Pandemonium lords, player ghosts, and player illusions; conjured monsters still aren't clonable, which rules out spectral weapons; and inugami are explicitly not clonable because you don't get the usual penalty if the inugami clone dies.
(I couldn't find a reason why ghost demons were barred from being cloned; git blame for that chunk of code goes back to 2010 when Mara's creating player illusions was added. Allowing clones of dancing weapons might be controversial, since a player could just cast Tukima's Dance and then use a phantom mirror on the resulting weapon, but I don't know if that's game-breaking.)
=> Allow cloning of uglies and dancing weapons.

crawl-ref/source/job-data.h
Since Passwall (now level 3) no longer uses the latter, and Stone Arrow (level 3) uses the former.
=> Give EEs Conjurations instead of Alchemy (#3444).

crawl-ref/source/ouch.cc
Djinn and Gargoyles can't be zombies or join the undead harvest.
Message suggested by regret-index.
=> Add Yred death message for nonliving players.

crawl-ref/source/invent.cc, crawl-ref/source/invent.h, crawl-ref/source/item-use.cc
If `MF_SECONDARY_SCROLL` is set, state in any menu "subtitles" that object class keys (such as ? or /) move to an item in its section. This was not previously communicated.
Add `MF_SECONDARY_SCROLL` to equip/unequip and identify menus.
The previous situation was:
The wield command showed weapons and staffs, but there was no one-key way to go to the staves.
The menu displayed if you read a scroll of identify showed scrolls and potions. If you typed `!` in that menu it would identify the first unidentified potion.
With this change:
Pressing `|` in the wield menu moves the cursor to the first staff.
Pressing `!` in the identify menu moves the cursor to the first potion.
Both keys are displayed within the menu.
=> Tell the player about MF_SECONDARY_SCROLL in menus.

crawl-ref/source/dat/descript/ability.txt
Fixes "No description found" when examining these with "a?" or "?/a".
=> Fix missing descriptions for Okawaru's "Receive {Weapon,Armour}" ability

crawl-ref/source/dat/database/monspeak.txt
Yred is fallen now; and Lugonu, being outside both the pantheon and the dungeon, is beyond fallen.
=> Adjust Recite for Yred flavour changes.

crawl-ref/source/attack.cc, crawl-ref/source/output.cc, crawl-ref/source/player.cc, crawl-ref/source/status.cc, crawl-ref/source/terrain.cc
Protecting yourself against corrosion with rCorr has feelsbad moments where you get corroded for the full amount. It's not noticeable when it prevents corrosion because some sources of corrosion aren't guaranteed to begin with.
Each stack of corrosion on the players reduces AC and slay by 1. Quadrupled most sources of corrosion to compensate. Having corrosion resistance will halve the number of stacks applied to the player instead of a coinflip chance to prevent the status entirely. This should hopefully make it feel more consistent. 
Corrosion from slime walls and Dis are not affected by this change, though this change makes it easier to halve the corrosion from slime walls if need be. Corrosion against monsters is not touched as well.
=> Make rCorr halve corrosion stacks on the player instead of a coinflip chance to prevent

crawl-ref/source/dat/des/portals/trove.des
As draconians do not use dragon armour, it is not a big deal for them to pay such small price to enter trove
=> Trove: stop asking for dragon armour toll from draconian

crawl-ref/docs/keybind.txt, crawl-ref/settings/colemak_command_keys.txt
This removes the leftover CMD_TOGGLE_TRAVEL_SPEED from colemak keybindings and keybind help.
=> Finish removing CMD_TOGGLE_TRAVEL_SPEED

crawl-ref/source/dat/species/armataur.yaml, crawl-ref/source/dat/species/barachi.yaml, crawl-ref/source/dat/species/deep-elf.yaml, crawl-ref/source/dat/species/demigod.yaml, crawl-ref/source/dat/species/demonspawn.yaml, crawl-ref/source/dat/species/deprecated-centaur.yaml, crawl-ref/source/dat/species/deprecated-deep-dwarf.yaml, crawl-ref/source/dat/species/deprecated-draconian-mottled.yaml, crawl-ref/source/dat/species/deprecated-mayflytaur.yaml, crawl-ref/source/dat/species/deprecated-meteoran.yaml, crawl-ref/source/dat/species/draconian-base.yaml, crawl-ref/source/dat/species/draconian-black.yaml, crawl-ref/source/dat/species/draconian-green.yaml, crawl-ref/source/dat/species/draconian-grey.yaml, crawl-ref/source/dat/species/draconian-pale.yaml, crawl-ref/source/dat/species/draconian-purple.yaml, crawl-ref/source/dat/species/draconian-red.yaml, crawl-ref/source/dat/species/draconian-white.yaml, crawl-ref/source/dat/species/draconian-yellow.yaml, crawl-ref/source/dat/species/felid.yaml, crawl-ref/source/dat/species/formicid.yaml, crawl-ref/source/dat/species/gargoyle.yaml, crawl-ref/source/dat/species/gnoll.yaml, crawl-ref/source/dat/species/mountain-dwarf.yaml, crawl-ref/source/dat/species/octopode.yaml
Some have them around species name, abbreviation, short name, adjective, and/or genus; and some don't. (Mountain Dwarf has them around some things and not others.) They're read properly either way, so the quotes aren't necessary.
=> Remove unneeded quotes from YAML files.

crawl-ref/source/mon-place.cc
So that _place_monster_aux() is a bit shorter and less complex, and so the function where setting gods is done has a more obvious name: _place_monster_set_god().
=> CLEANUP: Split out _place_monster_aux()'s setting of monster gods, and simplify it a bit.

crawl-ref/source/areas.cc, crawl-ref/source/ghost.cc, crawl-ref/source/ghost.h, crawl-ref/source/mon-place.cc, crawl-ref/source/monster.cc, crawl-ref/source/monster.h, crawl-ref/source/tag-version.h, crawl-ref/source/tags.cc
Currently only used for Pan lords with foul flame, who all get radius-1 umbras.
=> Let ghost demons have umbras.

crawl-ref/source/melee-attack.cc
This affects Sigils of Binding, Yred's Fathomless Shackles, and (indirectly) the slick slippers.
Closes #3547.
=> No moving via trampling/dragging if bound.

crawl-ref/source/actor.h, crawl-ref/source/art-data.txt, crawl-ref/source/monster.cc, crawl-ref/source/monster.h, crawl-ref/source/player-act.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/spl-other.cc
Immunity to binding sigils is now in its own actor-level function, the sigil messages are adjusted to not be player-specific, and the slick slippers now grant immunity to binding sigils on the player side.
=> CLEANUP: Binding sigils.

crawl-ref/source/attitude-change.cc, crawl-ref/source/attitude-change.h, crawl-ref/source/dat/database/monspeak.txt, crawl-ref/source/mon-death.cc
And such deathbed conversion will count as vengeance. This matches orc apostles, who, if they're marked for vengeance, only have it cleared by being defeated, although sneak attacks will also work on ordinary orcs.
This should fix #3576.
=> If an orc is marked for vengeance, it can only be converted via deathbed conversion.

crawl-ref/source/acquire.cc, crawl-ref/source/dungeon.cc, crawl-ref/source/item-prop.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/tag-version.h, crawl-ref/source/tags.cc, crawl-ref/source/wiz-item.cc, crawl-ref/source/xom.cc
Modeled after staff acquirement, in that it's accessible via the scroll, but only commonly so with enough shapeshifting skill. It's biased in favour of talismans you haven't seen, and more biased in favour of shapeshifting skill. However, no talismans are entirely ruled out; it's still possible, although rare, to acquire a talisman with no shapeshifting skill.
Accordingly, start keeping track of what talismans we've seen, as is already done with misc items.
Xom can also give talismans as gifts now, chosen entirely randomly.
(A lot of the seen-talisman tracking code is modeled after the seen-misc-item tracking code, some parts of which are rather confusing. It seems to work in my perfunctory testing, though.)
=> Add talisman acquirement.

crawl-ref/source/item-use.cc
When removing an item, `_safe_to_remove_or_wear` checked for the safety of removing the item if it provided flight and the player was above lava or deep water. However when swapping two items, `remove` is false and the removal of the old item is implicit. The function to check the safety of flight removal `safe_to_remove` is not called in this case.
This commit adds a flight removal safety check in the branch of `_safe_to_remove_or_wear` that has determined that we're swapping out an old item, echoing the check that was already happening for non-swap removal.
I added comments to both `safe_to_remove` checks, because it is not immediately clear that only flight removal safety is checked by that function. `_safe_to_remove_or_wear` has a comment stating that it checks for stat zero and does …
=> Check for flight item removal safety on swap

crawl-ref/source/webserver/webtiles/load_games.py
Use case: I disable forks by renaming them to `bcrawl.yaml.disabled`.
=> Ignore non-.yaml files in games.d/

crawl-ref/source/mutation-data.h
Having two mutations MUT_ROLL AND MUT_ROLLPAGE share the same short_desc means you can only interact with one of them in wizmode. Not a good idea to have 2 of anything share identical names anyhow.
=> Change short desc of rollpage mutation

crawl-ref/source/actor.cc, crawl-ref/source/melee-attack.cc, crawl-ref/source/ranged-attack.cc
It's unclear to me why misses call attack_strength_punctuation when the damage is always 0, so always use a period instead.
Make punctuation marks in collision messages vary with amount of damage dealt. This is averaged for collisions between creatures. Collisions can sometimes deal surprising amounts of damage and this better conveys that!!
=> Add punctuation to collisions, remove from misses

crawl-ref/docs/options_guide.txt, crawl-ref/source/abyss.cc, crawl-ref/source/activity-interrupt-type.h, crawl-ref/source/delay.cc, crawl-ref/source/initfile.cc
At least in local tiles, an abyss exit spawning does not interrupt autoexplore so you could press o and immediately find yourself 50 steps away from an exit that just spawned even with a force more for the message. This commit makes it that having an abyss exit or downstairs spawn interrupts autoexplore.
Also updated options_guide to include interrupt types for abyss_exit_spawned and ally_attacked.
=> Make abyss exit spawning interrupt travel

crawl-ref/source/beam.cc, crawl-ref/source/items.cc, crawl-ref/source/items.h, crawl-ref/source/traps.cc
Once upon a time there lived two bugs in a cottage.
The first bug caused a third throwing net that nets a target that's been netted and then netted again with a second net to get stuck on the target without increasing the net duration but remain stuck after the target breaks free, leaving behind a net that catches nobody but yet cannot be picked up.
The second bug caused netting a target that's standing on top of a net to merge the nets together, breaking both nets once the target breaks free.
Now the cottage is on fire and both bugs are dead. Throwing nets that hit a netted target will not net the target and nets that successfully net a target will not merge with any nets on the floor.
There is a third bug that causes a net that drops from killing a netted monster to not merge with any …
=> Unbug throwing nets

crawl-ref/source/ability.cc
Fixes an issue introduced by 926e5b6
Closes #3678
=> Fix makh major destruction firing acid globs

crawl-ref/source/mon-spell.h
Even after his previous buffs, Norris's killratio remains below 1%. In an actual game, he shows up at a time when you're already steamrolling most enemies, and then gets steamrolled.
Raise his draining gaze frequency dramatically so it can actually outdrain your mp regen and also increase primal wave's cast frequency slightly.
=> Buff Norris cast rates

crawl-ref/source/makeitem.cc, crawl-ref/source/shopping.cc
Rings of slaying are more than twice as expensive as other variable strength rings despite being arguably not that much better. Tone down its price to match other rings so it isn't often more expensive than good randart rings that generate in stores.
Slay rings are great in the early game and with short blades in the late game, but can end up being outclassed by stat rings which can provide more damage + ev. Using them also means forgoing potentially important defenses.
Closes #3279
=> Cheapen of rings of slaying

crawl-ref/docs/options_guide.txt, crawl-ref/source/initfile.cc, crawl-ref/source/items.cc, crawl-ref/source/options.h
Adds a new option: drop_disables_autopickup which removes all dropped items from autopickup automatically. A QoL thing that allows you to drop items (especially from local tiles inventory panel) without needing additional keypresses to enter the autopickup menu and disable autopickup manually. Defaults to off.
=> Add option to remove dropped items from autopickup

crawl-ref/source/beam.cc
Antimagic frequently rolls a duration of 0 on hits but will still print the "magic leaks into the air" message which doesn't seem right to me.
=> Don't leak magic if antimagic rolls 0 duration

crawl-ref/source/describe.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h
Similarly to how item descriptions show the effect equipping that item would have on your AC/EV, make it also show the effect it would have on your SH, if relevant.
For consistency, make AC/EV/SH previews in descriptions not include temporary effects (previously these were included for AC and excluded for EV). If you prefer the alternative, we can do that too; the most important thing is that it's consistent.
Also make AC/EV/SH previews use the same function to compute them, instead of using entirely separate functions with entirely separate logic.
AC/EV/SH preview will now show on all items that have a non-zero effect on them, except non-artefact rings of protection/evasion and amulets of reflection (as for these items, it is not useful). AC preview will always show on body armour and …
=> Add SH preview to item descriptions

crawl-ref/source/religion.cc
Previously the value was not up-to-date after gaining a level until your ancestor died and respawned.
=> Fix max HP value in description of your ancestor

crawl-ref/source/target.cc, crawl-ref/source/target.h
Display permafrost center targets with more opacity. This includes a nonstandard use of AFF_YES but I don't think any players would complain.
=> Display PE center targets with more opacity

crawl-ref/source/beam-type.h, crawl-ref/source/beam.cc, crawl-ref/source/god-abil.cc
The original is at #3332.
The only changes made in this version are to update it for current trunk, put the Disaster Area radius limitation back in so it doesn't always blast everything in LOS, constify a variable, disable the prompt when aiming it at yourself, and refactor it to actually not damage things it shouldn't damage when directly aimed at those things.
=> Updated version of Monkooky's Qazlal Upheaval friendly fire PR.

crawl-ref/docs/options_guide.txt, crawl-ref/source/viewchar.cc
DCHAR_ITEM_GOLD and DCHAR_ITEM_GEM were in a different order in dchar_names[] (used by the "display_char" option) to the one in dungeon_char_type, meaning that the option had unexpected effects.
Fix this, and add item_gem to the docs for this option.
=> Correct how the display_char option handles gems and gold.

crawl-ref/source/items.cc
In local tiles. Should be fine for ISFLAG_CURSED to be included in get_item_known_info now that the only source of curses is ash.
Closes #3683
=> Fix cursed item background not being red

crawl-ref/source/dat/descript/items.txt, crawl-ref/source/dat/descript/monsters.txt, crawl-ref/source/dat/descript/status.txt, crawl-ref/source/describe.cc, crawl-ref/source/mutation.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-util.cc
Change a few places where a word used a spelling which is not spelt correctly according to
https://www.australian-dictionary.com.au/wordcheck/.
This only changes things in places where the spellings may be displayed to the user. I include the documentation in this. I haven't changed the changelog or doc/develop, or any of the contrib stuff.
This changes:
channeling -> channelling
dueling -> duelling
offense -> offence
defense -> defence
skillfull/skillfully -> skilful/skilfully
willful -> wilful
=> Change the spelling of some words to Australian English.

crawl-ref/source/timed-effects.cc
Include ENCH_BULLSEYE_TARGET in timeout_enchantments. This is to avoid accidentally causing penance when shooting another target after an apostle becomes neutral/friendly without warning.
=> Clear dimensional bullseye when apostle yields

crawl-ref/source/tileweb.cc, crawl-ref/source/tileweb.h, crawl-ref/source/webserver/game_data/static/enums.js, crawl-ref/source/webserver/game_data/static/player.js, crawl-ref/source/webserver/game_data/static/style.css, crawl-ref/source/webserver/game_data/templates/game.html
Add a second weapon line for coglins to the WebTiles interface, just below the normal weapon line and above the quiver, which is hidden in all cases where you don't have an offhand weapon equipped.
This works differently from console/offline tiles, but I personally think this is how those formats should work too. (Currently, they have both weapons listed on the same line, which gives each weapon awfully little space for its properties, or in the case of artefacts, even just the name can be too long.)
[Important note: as this code relates to WebTiles I am unable to test it! I'm hoping the checks will reveal any mistakes.]
=> Show coglins' offhand weapon in the WebTiles interface

crawl-ref/source/items.cc
Don't disable autopickup when dropping missiles because missiles with different brands share the same base type.
=> Improve drop_disables_autopickup behavior

crawl-ref/source/dat/database/decorlines.txt
meat_and_reaction needed a quantifier preceeding it, unlike fruit_and_reaction. This was confusing and caused repeated errors, so we're changing it.
Also sneaking in a haggisification of death yak sausage
=> remove some meat

crawl-ref/source/output.cc
Self-explanatory. I can't think of anywhere else this might be displayed, but if there is anywhere else, it should of course be removed from there as well.
=> Don't show MPRegen line on % screen for djinn

crawl-ref/source/terrain.cc, crawl-ref/source/tilepick.cc
Temporary terrain changes produced by the summon forest spell can
affect dungeon features outside of the player's LOS. Those features
lose the flavour when described or if the dungeon view is reloaded.
The description is also wrong for the summoned trees after the spell
finished.
The first version of the patch had to be reverted because it crashed
on some vaults with loot on top of custom floor.
=> Fix the description of walls with unseen changes (take two)

crawl-ref/source/makeitem.cc, crawl-ref/source/makeitem.h, crawl-ref/source/ng-setup.cc
Previously, if your wanderer rolled a misc evoker, you could still get the same misc evoker generate in your game. Since they're meant to essentially be unrands, fix this.
[Sidenote: misc evokers are generally pretty unbalanced for starting equipment. The lightning rod in particular is insanely strong, with 4 charges of (2+)d15 unavoidable lightning damage. Some rebalancing may be desirable in future.]
=> Fix wanderer evoker starts from allowing duplicate evokers

crawl-ref/source/ng-wanderer.cc
These start with either a beast or a flux talisman.
Note that, unlike shapeshifters, they don't start in shapeshifted form. They won't have the skill for flux talismans, and starting in beast form only for beast talismans seems odd, given that their other equipment could include things melded under beast form. (Assume the difference is because they didn't go to Official Shapeshifter School.)
=> Allow wanderers with shapeshifting skill.

crawl-ref/source/dat/des/altar/overflow.des, crawl-ref/source/dat/descript/features.txt
This features altars to all three chaotic gods (now that Nemelex is considered chaotic), a walled-off chaos spawn (cf. the walled-off angel in a Zin overflow vault), a damaged chaos weapon for flavour, and chaotic decor such as (cosmetic) orange crystal walls.
=> Add abandoned chaos spawn temple overflow vault.

crawl-ref/source/ng-wanderer.cc, crawl-ref/source/skills.cc
- Troll, oni and spriggan wanderers now actually get armour when they roll armour skill (acid dragon scales for good quality, otherwise an aux slot) as originally intended. They'll also get armour skill if they start with acid dragon scales.
- Ghoul wanderers can now get potions of attraction like every other species
- Formicid wanderers can now start with a quarterstaff or a ranged weapon and a shield
- Starting wands of warping now get 2-4 charges like iceblast/roots instead of getting 15
Also, to incentivise using starting unarmed combat skill when wanderers get it, make wanderers that start with unarmed skill not get the default club/dagger if they weren't assigned another weapon.
This is courtesy of me generating hundreds of wanderers for testing their stats, and a couple of other …
=> Fix a few things about wanderer

crawl-ref/source/dat/database/monspeak.txt, crawl-ref/source/dat/des/altar/overflow.des, crawl-ref/source/dat/descript/features.txt, crawl-ref/source/dat/descript/monsters.txt
To help integrate Nemelex vault-wise as a chaotic god, since there are Zin/Xom vaults and Zin/Makhleb vaults.
This has (cosmetic) pink crystal walls, a talking Zin angel, and a talking goblin sharper worshipping Nemelex (only dialogue, no abilities). Note that the latter's dialogue provides minor spoilers as to what some cards do.
=> Add Zin vs. Nemelex temple overflow vault.

.github/workflows/ci.yml
Just seeing if this works but I had the same error in WSL and --break-system-packages just forces the "old" behaviour of pip install, so it's worth a try
=> Break system packages (Fix MacOS build?)

crawl-ref/source/player-equip.cc
Before, the game referred to "your injured body" if you tried to wear an amulet of magic regeneration when your health and magic were both below their maxima.
The message for that item no longer mentions your physical injuries.
=> Fix a message for items giving magic regeneration.

crawl-ref/source/zap-data.h
Spells implicitly take the lesser of their defined power cap and their corresponding zap's defined power cap when deciding what their real power cap should be. Since Hellfire Mortar is linked to ZAP_HELLFIRE_MORTAR_DIG, which had a cap of 100, Hellfire Mortar erroneously also had a cap of 100. Since it doesn't appear that power actually does anything for this zap, just raise the zap's cap to 200.
=> Fix Hellfire Mortar power cap (#3820)

crawl-ref/source/mon-pathfind.cc
A fairly old bug seemingly introduced in 323ad4e. Monsters would open doors under the simplest circumstances (standing right next to them, and/or with an otherwise unobstructed view to the player) but as soon as waypoint pathfinding kicked in, the is_habitable check was happening too early and they never got to check if they were able to traverse the door. Closed doors are not considered habitable (probably since 323ad4e).
These checks were introduced to solve an issue with clinging but were not purged in 53d2a09 when clinging was removed. Both checks were duplicated in mons_can_traverse but in the correct sequence to also account for doors.
=> Remind monsters how to open doors

crawl-ref/source/nearby-danger.cc
Refuse to rest if suffering from fatal poison, sticky flames or emergency flight, even in a Zin sanctuary. Before, the game paused for a turn to let these cause damage before stopping.
Also remove the word "standing" from "You're standing in..." (you may not have any feet) and split some long lines
Addendum: I don't know why i_feel_safe() doesn't check for a sanctuary when called with just_monsters, but I haven't changed anything. The option is used in _mons_is_valid_target() and _cancel_ice_move().
=> Don't rest if you're dying in a sanctuary.

crawl-ref/source/describe-god.cc, crawl-ref/source/religion.cc
Apparently Webtiles uses regular expressions to parse the ^ screen, and it really doesn't like the use of parentheses in strings describing god powers. There is a way around this, but it puts the resistance in the cost column on Webtiles (in the same way as Cheibriados' stat boost), which is unacceptable.
Also change "injuring" to "harming" when referring to jellies, for better flavour.
=> Fix ^ screen for Jiyva and Ignis in Webtiles (#3851)

crawl-ref/source/ng-wanderer.cc
- Give wanderers three unique skills, rather than occasionally only getting two (when the same skill was rolled twice); incompatible skills will also be rerolled earlier in the process.
- Tweak wanderer starting stat distribution very slightly
- Remove decent staves skill and make good staves skill give a +0 quarterstaff.
See individual commits for details. In the process of writing this PR, I have also made a branch which generates 1,000,000 wanderers whenever a wanderer is started and records the total numbers of each skill picked, as well as the average stat gain. If you're interested, see my `NormalPerson7:wn-investigations` branch.
=> A few more tweaks to wanderer

crawl-ref/source/dat/database/help.txt
! is used to toggle between travel and view in the search window. ? seems to do nothing.
=> Update search help text for shops (PJRamaglia)

crawl-ref/source/directn.cc
The "monsters in view" display wraps long lines. It ignored monster_item_view_coordinates when calculating this (except with local tiles), so missed the ends of some lines. It no longer does.
=> Improve wrapping for monster_item_view_coordinates.

crawl-ref/source/beam.cc, crawl-ref/source/beam.h
this flag is entirely redundant; it is true only when aimed_at_feet is and checked only when aimed_at_feet is
=> remove auto-hit flag

crawl-ref/docs/tiles_help.txt
Adds a 'character appearance' section in tiles_help.txt that gives an overview of the Doll Editor.
Resolves #2815
=> Add doll editor info to docs/tiles_help.txt

crawl-ref/source/dat/clua/stash.lua
Presumably broke after the rename from gold -> golden.
I also noticed test/stress/qw.rc has the old name still, but it already seems to have been fixed in the qw repo, so I left that alone. (The file seems rather out-of-date anyway; it generates other errors as a result)
=> Fix stash search prefixes for golden dragon scales

crawl-ref/source/android-project/app/src/main/java/org/develz/crawl/DCSSLauncher.java, crawl-ref/source/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, crawl-ref/source/android-project/app/src/main/res/layout/launcher.xml, crawl-ref/source/android-project/app/src/main/res/values/constants.xml, crawl-ref/source/android-project/app/src/main/res/values/strings.xml
I got this message from an Android user:
> can't enable full screen mode by setting "tile_full_screen = true",
> still shows a black bar on top with device status.
I agree a full screen option for Android can improve the user
experience. Mostly when playing on landscape mode with modern devices.
You can read this in the docs:
> Where you set the UI flags makes a difference. If you hide the system
> bars in your activity's onCreate() method and the user presses Home,
> the system bars will reappear. When the user reopens the activity,
> onCreate() won't get called, so the system bars will remain visible.
> If you want system UI changes to persist as the user navigates in and
> out of your activity, set UI flags in onResume() or
> onWindowFocusChanged().
Tried both options and the behaviour …
=> Android: Add a full screen option to the launcher

crawl-ref/source/art-func.h, crawl-ref/source/skill-menu.cc
Make the Charlatan's Orb explicitly update the player's HP and MP in its equip/unequip functions.
Also add the Charlatan's Orb as a cause of increased skills on the skills screen to fix the previous text
`Skills enhanced by  are in green.`
Resolves #4015. (Forgot to mention in commit message, sorry)
=> Fix HP/MP not updating when (un)equipping the Charlatan's Orb

crawl-ref/source/fineff.cc, crawl-ref/source/fineff.h, crawl-ref/source/mon-death.cc
Previously, if a bennu was friendly-bribed in their first life, it would revive as a permanent friendly ally that could follow the player everywhere. If it was temporarily neutral-bribed, it would revive as a permanent neutral monster.
Fix this issue by preserving friendly and neutral bribe enchantments upon revival.
Sidenote: currently unbribed bennu get a second chance to become bribed upon revival - is this good behaviour?
Resolves #4026.
=> Preserve bribe enchantments for reviving bennu

crawl-ref/source/god-companions.cc
Previously it was possible to kill your apostles with e.g. scrolls of poison, not incur wrath, and gain experience from the kill.
I can't really imagine players ever wanting to take advantage of this, but nonetheless it goes against the spirit of Beogh so let's prevent apostles from giving experience.
Resolves #4024.
=> Don't gain experience from killing allied apostles

crawl-ref/source/spl-book.cc
Previously, if you worshipped Okawaru (for example), spells which could not be memorised would be silently added to your library and also hidden in your library.
Spells that can't be memorised do not appear on the spell library interface, so this had no actual effect as long as the spell could not be memorised. But, say, if you then abandoned Okawaru, you would find all your previously unmemorisable spells hidden in the library (so that, to unhide and memorise them, you would have to visit the "Show" screen).
In practice, this meant many players would just assume the spell was lost forever.
Resolves #3994.
=> Don't auto-hide currently unmemorisable spells when picking up books

crawl-ref/source/god-passive.cc
If a player is surrounded by monsters to depth 3+, `_get_shadow_spots` produces an empty vector and the game crashes trying to dereference the first entry. Check for an empty vector first.
(https://cbro.berotato.org/morgue/ChongLi/crash-ChongLi-20240908-132253.txt)
=> don't crash if shadow can't be placed (ChongLi)

crawl-ref/source/xom.cc
If `place_monster_corpse` returns nullptr, the game crashes when trying to call `turn_corpse_into_skeleton`.
Possible when placing a skeleton on a terrain feature that destroys items, like lava. (`move_item_to_grid` destroys the would-be corpse item)
Example crash log: https://underhound.eu/crawl/morgue/seandewar5/crash-seandewar5-20240902-225318.txt
=> Fix crash in Xom's wave of despair effect

crawl-ref/source/status.cc
Makes it consistent with other such status light texts, and should fix the WebTiles hover tooltip showing "No description found" despite a correct description existing in [`dat/descript/status.txt:458`](https://github.com/crawl/crawl/blob/14434f1371bfaccec06cb57e55e632dca4d32c04/crawl-ref/source/dat/descript/status.txt#L458) (though I couldn't locally test that; assumed from looking near [`tileweb.cc:1213`](https://github.com/crawl/crawl/blob/14434f1371bfaccec06cb57e55e632dca4d32c04/crawl-ref/source/tileweb.cc#L1213) and [`webserver/game_data/static/player.js:447`](https://github.com/crawl/crawl/blob/14434f1371bfaccec06cb57e55e632dca4d32c04/crawl-ref/source/webserver/game_data/static/player.js#L447)).
=> Add missing space to Horror status light text

crawl-ref/source/mon-act.cc
Brom's Barrelling Boulder can push monsters into terrain you haven't seen. This created a message such as " Your boulder crushes the orc against  and falls apart!" as feature_description_at() returns an empty string for unknown terrain.
Replace the empty string with "something" for that message.
=> Use more nouns when a boulder pushes something into the unknown.

crawl-ref/source/item-prop.cc
Enhancer staves are currently two handed for Ko and Sp.  I feel like it mostly catches people off guard and doesn't matter much as far as their power level goes. 
It might be worth taking a look at other stuff since it feels like there is little reason behind what is two and what is one handed for small species.
=> 1h enhancer staves for small species

.github/workflows/ci.yml
Both are already installed on current GHA images; the former is actually redirected to install a different variant (there are two: the original, and a fast but buggy C version), which then conflicts with the already-installed version. So simply skip installing both.
=> disable installation of pkg-config and libpng

crawl-ref/source/mutation.cc
Draconian wings would remain on player dolls until saving and reloading if they had lost their big wings mutation. This change has the loss of the big wing mutation initialize the player doll so we properly lose the wings when this occurs.
Reported by [kuniqsX](https://github.com/kuniqsX) and resolves [#3973](https://github.com/crawl/crawl/issues/3973)
* Added `init_player_doll();` with a `USE_TILE` def compiler flag under the `MUT_BIG_WINGS` switch case for the following code:
* `crawl-ref/source/mutation.cc`
* `static bool _delete_single_mutation_level(mutation_type mutat, ...`
Tested with the committed code change alongside the *NOT* committed code changes to `potion.cc` for easy reproduction:
```c++
bool effect(bool = true, int = 40, bool = true) const override
{
if …
```
=> Update player doll to visually lose wings when big wings mutation is lost (Resolves #3973)

crawl-ref/source/fight.cc
Fulsome fusillade can damage your summons so it should warn when you
try to summon with it active, similar to spells like polar vortex.
Should resolve #4055
=> Warn when summoning with fulsome fusillade active

crawl-ref/source/Makefile
The pattern matches Arch's 14.2.x, which leads to inconsistent optimization and crashes with their build flags.
It was later noted that g++ 4.2 didn't support C++11, which we require these days, so the test no longer serves a purpose anyway. And Macs have shipped clang instead of gcc for years.
=> remove old g++ check

crawl-ref/source/dungeon.cc, crawl-ref/source/fight.cc, crawl-ref/source/files.cc, crawl-ref/source/hints.cc, crawl-ref/source/item-use.cc, crawl-ref/source/lookup-help.cc, crawl-ref/source/mon-act.cc, crawl-ref/source/potion.cc, crawl-ref/source/shout.cc
Replace "a %s" (and equivalent) with article_a() in some places where the noun can start with a vowel sound, or where the noun isn't clear from the context.
For instance, typing ?/i with the default setup now prints "Describe an item;" rather than "Describe a item;".
=> Use article_a() instead of "a article" in a few places.

crawl-ref/source/mon-act.cc
If the lava stream for Hellfire Mortar is shortened by an obstacle which is no longer there when the mortar reaches the spot, and the player sees it, this could give the message "The hellfire mortar collides with a floor and sinks back into the magma."
Omit the "collides with a floor " part unless the mortar hits a monster or "solid" terrain.
Remove the death message which followed this (which seemed redundant) and stop blaming a monster for the death. That is, change the killer_index in monster_die() to NON_MONSTER and the silent flag to true.
...
I don't have an opinion on the mechanics of Hellfire Mortar, but the messages seemed a bit off.
A mortar could collide with "a floor" (not even "the floor") if it ran out of magma. It called monster_die() with a killer_index of "true". As …
=> Stop mortars from colliding with "a floor" and then being "destroyed!".

crawl-ref/source/menu.cc
Previously, if a player had a spell library containing every spell, searching it for "hat" led to Shatter being selected. Searching for "a" after this led to Shatter still being selected, but only the top of the spell list being displayed.
This happened because UIMenu::update_items() resized item_info but didn't set the x, y, row or column fields, and UIMenu::get_item_region() relied on those being up to date.
Call UIMenu::do_layout() to fix it.
=> Fix the way the scroller works when a menu grows.

crawl-ref/source/beam.cc
When a player is blinded, they can miss with spells that are supposed to never miss, such as Magic Dart, LRD, and Chain Lightning. This only applies to spells that solely rely on having AUTOMATIC_HIT as their to hit for this purpose (e.g. Fireball doesn't currently miss even when blinded, since it is an explosion). This commit makes sure that the aforementioned spells will be unaffected by blindness.
=> fix: Make spells that never miss unaffected by blindness

crawl-ref/source/beam.h, crawl-ref/source/target.cc
The situation I was trying to fix is to stop Mephitic Cloud targeter from trying to avoid the Qazlal-worshipping player. The harmlessness check is already there, but not called by the beam targeter.
`bolt::harmless_to_player()` was private. However, it makes sense for the beam targeter to call this, and making it public would be the straightforward way to do this.
=> Let beam targeter take whether it's harmless into account.

crawl-ref/docs/develop/contribution-process.md, crawl-ref/docs/develop/git/quickstart.txt
The git quickstart guide now mentions the most important git commit message conventions, and links to a page with more detailed information and additional common conventions.
=> document git conventions

crawl-ref/INSTALL.md, crawl-ref/source/MSVC/Console.props, crawl-ref/source/MSVC/Console.vsprops, crawl-ref/source/MSVC/Tiles.props, crawl-ref/source/MSVC/Tiles.vsprops, crawl-ref/source/Makefile, crawl-ref/source/glwrapper-ogl.cc, crawl-ref/source/glwrapper-ogl.h
Avoid depending on deprecated GLU library by dynamically loading
OpenGL 3+ function glGenerateMipmap where available.
If it's not available, Where it's not, we just render without mipmapping.
Note that for a lot of resolution / rc setting / zoom level combos,
we don't mipmap anyway, and this PR doesn't change those cases at all.
Also note that OpenGL 3.0 was released in 2008.
glGenerateMipmap is available even on decade old GPUs and iGPUs as a result.
For players running truly ancient GPUs and systems that supported GLU,
but not OpenGL 3, and who happened to have just the right setup for us to
enable mipmapping, we will now render without it.
If anyone actually does turn out to be affected, they may be able to use
a version of llvmpipe that supports OpenGL 3+ as a software renderer. …
=> Remove GLU dependency

crawl-ref/settings/advanced_optioneering.txt
The autopickup function is matching against the return from l_item_do_subtype, which is a wrapper around equip_slot_name, which in 2dbd7c1f was changed so that the strings are capitalized.
thanks to @lmplojin on discord for the pointer.
=> Update add_autopickup_func to use capitalized subtype

crawl-ref/source/item-name.cc
Add food and rods to the "always known" list in item_type_known(). This restores some behaviour from before _full_ident_mask() was deleted, in that you are no longer asked if you want to identify "removed food" items.
=> Automatically identify some obsolete items.

crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/spl-util.cc
When casting Olgreb's toxic radiance with no enemies in view, it would give the message "You can't see any susceptible monsters within range! (Use Z to cast anyway)". However, when casting with only poison resistant and immune enemies in view, it would cast normally even though it couldn't effect anything. Fix this inconsistency by also requiring uppercase Z to cast with only poison reistant and immune enemies in view.
This change also fixes a bug where monsters would always act as if they could see invisibly even when they couldn't when deciding whether to cast OTR.
Fixes #3957
=> Cast OTR with uppercase Z when all enemies resist poison (CrawlOdds)

.github/workflows/ci.yml, crawl-ref/source/Makefile.obj, crawl-ref/source/catch2-tests/test_tilecell.cc, crawl-ref/source/directn.cc, crawl-ref/source/tilecell.cc, crawl-ref/source/tilecell.h, crawl-ref/source/view.cc
In rare cases, you can exceed the 20 overlay limit.
This leads to a crash.
To fix this:
* Deduplicate all overlays, not just the most recent
* Reduce overlay cap to 16 instead of 20 for vectorization reasons
* Make packed_cell fit into 196 bytes, because why not + cache alignment
* Make add_overlay an instance method for convenience
Modern clang versions auto-vectorize and unroll this std::find nicely. GCC doesn't do quite as well, but at least clones/unrolls it 4 wide. We'll see if it's a win or not.
=> fix: overflow of overlays with Qazlal's Disaster area (prawnwizard)

.github/workflows/ci.yml, crawl-ref/docs/index.html
* Generate Lua docs with ldoc
* Generate FAQ.html with make docs
* When on master, publish generated artifact to GitHub Pages
* Add a very rudimentary index.html to serve as landing page
* Once merged, https://crawl.github.io/crawl/ should show the new index.html
* With working links to FAQ.html and lua/index.html :)
One less task to do manually :)
=> ci: Generate docs in CI and publish to GitHub Pages

crawl-ref/source/dat/jobs/forgewright.yaml
Reorders the starting items to be consistent with other backgrounds
with a similar kit.
=> Fix: Reorder Forgewright starting items

crawl-ref/source/mon-death.cc
We were checking if the radius of any of the monster's halo, umbra or silence were not equal to zero. However, they have a radius of -1 when they don't exist.
=> Fix always invalidating the area grid when a monster dies

crawl-ref/source/spl-summoning.cc
The foxfire swarm ability was creating foxfire with a power of GOD_NO_GOD (0) instead of 20 and marshlight set to 20 instead of its default value of false.
=> Fix foxfire swarm using the wrong tile and power

crawl-ref/source/beam.cc
When you killed a monster with the white draconians breath ability while worshipping Gozag, you would get a message saying it shattered and turned to gold but you would get a block of ice and no gold. Fix this by not freezing a monsters corpse if it has been turned to gold.
Fixes #4185
=> Don't freeze corpses that have been turned to gold

crawl-ref/source/delay.h, crawl-ref/source/dungeon.cc, crawl-ref/source/spl-cast.cc, crawl-ref/source/target.cc, crawl-ref/source/target.h
Fixes #4262
* Removes unused fields where it make sense
* In the case of targeter_wall_arc, put field back into use (and move where the hard-coded value is)
* Also fixes one other warning that only occurs in debug-lite or release configurations
=> style: fix a few warnings

.github/workflows/ci.yml, crawl-ref/source/MSVC/crawl.vcxproj, crawl-ref/source/util/gen-all.py
* Add msvc build job covering all x64 build configurations           
* Fix gen-all.py to run targets in the correct order so that a clean msvc build works
* clean up vcxproj - Visual Studio can be repetitive for no reason
* YY_NO_UNISTD_H needs to be defined for all msvc configurations after wheals' latest cleanup.
=> ci: Add msvc build job

crawl-ref/source/initfile.cc
Hopefully fix #4299.
I'm not entirely convinced all usage of unlink should not be unlink_u. But that's a separate discussion.
=> fix: unistd.h inclusion for macOS 10.14

.github/workflows/ci.yml, crawl-ref/source/util/checkconventionalcommit.py
Add a python script to check line lengths of all commits not in master.
Should work properly even in the case where it's ran on master, though it's a bit pointless there.
=> ci: Automatically check commit messages against guidelines

.github/workflows/ci.yml
As currently written, the `deploy_docs` action runs on forks, which means anyone with a fork of the crawl repo gets a build failure when updating the fork. This patch makes it only run on the main crawl repo (hopefully).
=> only deploy docs and try to send IRC notification on the main repo

crawl-ref/source/mon-util.cc
After equipment slots were reworked in commit 2dbd7c1, the `monster::wearing_ego` function stopped checking the shield slot for egos when checking armour for egos leaving monsters unable to benefit from shield and orb egos.
Fixes #4324
=> Fix monsters not getting shield and orb egos (yrdzrfxndfvh)

crawl-ref/source/mon-death.cc
Previously, Blorkula would split into vampire bats when banished, and if they reformed, trying to banish them again would cause a crash.
Will fix #4205.
=> Don't let Blorkula cheat banishment (#4205)

crawl-ref/source/mon-place.cc
There was a bug that made plants hostile while being placed and Fedhas worshippers cannot be on top of hostile oklob plants (but can be on top of other hostile plants). This allowed growing ballistomycetes under the player but not oklobs.
Fixes #4048
=> Fix grow oklob not placing under the player

crawl-ref/source/religion.cc
Good gods are usually fine with you switching to another good god, so it doesn't make sense for you to get the traiter title from the religion you left in this case.
Resolves #4329
=> Don't become a religious traitor when switching good gods (A0rika)

crawl-ref/source/dat/database/monspeak.txt
Imp speech `_suck_up_adj2_` throws an error because of a missing `then`. Restore correct syntax.
Should fix https://github.com/crawl/crawl/issues/4344.
=> Fix imp _suck_up_adj2_ syntax

crawl-ref/source/shopping.cc
If an antiques shop contains two unidentified amulets, rings or wands of the same type, it gives a price for each item. If the player tries to buy both, the game charges a different price for the second item.
Change it to charge the agreed price for everything.
This avoids a situation where the player could agree to pay X for some goods but actually be charged Y for them. There are others (such as asking separately about the second item or not selling it in the same transaction), but this one doesn't involve changes to the UI.
Shops with two similar unidentified amulets, ring or wands are rare, so it shouldn't matter too much how it's handled. Charging a lot of money without warning seems like quite a bad way to do it, though.
=> Stop antique shops from overcharging.

crawl-ref/source/fight.cc, crawl-ref/source/fight.h, crawl-ref/source/melee-attack.cc, crawl-ref/source/spl-transloc.cc
Allow manifold assaulting with a weapon that warns
Because manifold assault chooses its targets at random, it has to avoid
targets that would warn the player so as not to put them in penance etc.
However, when using a weapon that would warn when attacking any monster
(e.g. the singing sword with an ally in view) this lead to it not
finding any targets it could hit. To fix this, promt when attacking with
a weapon that would always warn when attacking and only exclude targets
where the actual target is the problem (e.g. to close to an ally when
using devastator).
Fixes #3838
=> Allow manifold assault to be cast when it would warn

crawl-ref/source/mon-act.cc
Dead felids awaiting revival could still receive attacks of opportunity while they were dead, which cluttered up the message log.
Will resolve #4292.
=> Prevent attacks of opportunity on dead felids (#4292)

crawl-ref/docs/options_guide.txt
As it stands there's no documentation of any kind regarding custom dump sections, other than options_guide mentioning it exists. A more detailed description should save potential users much of the headache figuring out how it works.
=> Clarify options_guide.txt regarding player-defined dump sections

crawl-ref/source/ng-setup.cc, crawl-ref/source/skills.cc, crawl-ref/source/skills.h
Calculate how much exercise spell skills gives for a new character before splitting spell skills. This means that level 1 djinn auto-train magic to a similar degree to other species.
Train spell skills (roughly) in proportion to the exercise put into them, where it had been much less.
The aim of this is to make the auto-train behaviour feel similar for Djinn to the way it feels for other species. The 0.31 version feels very different to me, with no spell training at level 1 and little emphasis on it later on (to the extent that setting focus on a different skill could eliminate spell skill training altogether).
=> Make auto-training train spell skills more readily for djinn.

crawl-ref/source/tilepick.cc
A small modification, when you use Merfolk's Mons Tile as your player tile, it correctly displays their differential in water
=> When you use mon-tile as a player-tile, display their changes in water

crawl-ref/source/ability.cc
Currently, when the player tries to Summon Divine Warrior (TSO ability), while having Fulsome Fusillade (or Polar Vortex) active, the game does not prompt the player to confirm the action, rather it simply summons, which easily causes penance. This commit aims to fix this issue by calling ```stop_summoning_prompt``` before calling ```summon_holy_warrior``` at ability.cc:3423-3424.
=> Fix: no prompt when invoking Summon Divine Warrior while having Fulsome Fusillade active (#4182)

crawl-ref/source/describe-spells.cc, crawl-ref/source/spl-util.h
Currently, in WebTiles, the colours of spells in spellbooks are far from useful. The most important question when x-v-ing a book (e.g. in a gauntlet, or a ghost vault) and seeing its spells is "do I already have this spell in my library?". There was previously no way to check this without leaving the x-v menu and manually checking.
With this PR, all spells will be greyed out in book descriptions if you already have them in your library (or if they are useless, or if you have memorised them via Vehumet), lightred if forbidden, lightgrey if eventually useful, and lightblue if you could memorise it immediately, in that order of priority.
Better suggestions for colouring are welcome. I had wondered whether it would be better to change WebTiles to use the local tiles (and I presume console) …
=> Improve colours of spells in spellbooks

crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-summoning.cc, crawl-ref/source/spl-summoning.h, crawl-ref/source/target.cc, crawl-ref/source/target.h
This is similar to my PR to improve malign gateways targeter (#3968) except the spell can now target directions that aren't one of the 8 compass directions. Closes #3910
=> Improve malign gateways targeter and simplify targeting

crawl-ref/source/dat/descript/unrand.txt
One of the players noticed that the Skull of Zonguldrok's artefact text was unclear as to the equip slot which caused some problems with the 2H they were using.  This adds a "When held" to the second sentence to clarify.
=> bugfix: Zong text was ambiguous as to the equipment slot

crawl-ref/source/dactions.cc, crawl-ref/source/mon-death.cc
Move the "With Pikel's spell broken..." message into the DACT_PIKEL_MINIONS handler, so it only prints if you can see any lemures which survived long enough to depart.
=> Stop lemures from thanking you for killing them.

crawl-ref/source/dat/descript/spells.txt, crawl-ref/source/dat/descript/zh/spells.txt, crawl-ref/source/spl-data.h
Asterion's current ability name, "Greater Servant of Makhleb", comes from Makhleb's old ability names before the 0.32 overhaul.
Since the overhaul was mostly merging the lesser/greater pairs while leaving the actual mechanics untouched, I think we can keep the     existing monster spells (along with icons and descriptions), but use the new ability titles.
The other ability, "Major Destruction", is contrasted with another monster spell "Legendary Destruction". It is thus not changed in this PR.
=> fix: Bring Asterion's ability names in line with overhauled Makhleb

crawl-ref/source/art-data.txt
Its description said that it gives effective stabs with any weapon, but it only gives them on melee weapons. Change its description to say any melee weapon.
=> Clarify that the hood of the assassin only effects melee

crawl-ref/source/tilereg-map.cc, crawl-ref/source/tilereg-map.h, crawl-ref/source/ui.cc, crawl-ref/source/viewmap.cc, crawl-ref/source/viewmap.h
In local tiles while in map view mode, you should be able to right click and drag the mini map to view those parts of the map. However, in version 0.26 dragging the mouse stopped doing anything and in version 0.28 right clicking the map stopped doing anything.
Fixes #3804
Fixes #3802
=> Fix far viewing

crawl-ref/source/ability.cc, crawl-ref/source/art-func.h, crawl-ref/source/fight.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/spl-transloc.cc, crawl-ref/source/spl-transloc.h, crawl-ref/source/spl-util.cc
When the Sword of Power shoots a bolt, start the bolt from one space before the defender in the direction from the attacker to defender instead of always starting from the attacker. This allows it to make attacks it a distance with manifold assault.
=> Allow manifold assault with the Sword of Power

crawl-ref/source/coordit.cc, crawl-ref/source/coordit.h, crawl-ref/source/fineff.cc, crawl-ref/source/mon-abil.cc, crawl-ref/source/mon-cast.cc, crawl-ref/source/mon-clone.cc
The old fair_adjacent_iterator would visit the tiles around it in the following order
1 4 6
2 x 7
3 5 8
starting from a random tile and wrapping around when it reached the last tile e.g. if the random start was 4 then 4,5,6,7,8,1,2,3. So imagine for example a yellow ugly thing surrounded by walls and other ugly things trying to pick a random ugly thing around it when changing colour as shown below
w=wall
r=red ugly thing
y=yellow ugly thing
b=brown ugly thing
c=cyan ugly thing
g=green ugly thing
w w r
w y b
w c g
if the random start was an adjacent ugly thing that ugly thing would be selected, however, if the random start was one of the walls the iterator would be advanced until it reached the cyan ugly thing and it would be selected givng the cyan ugly thing a 5/8 chance of being …
=> Make fair_adjacent_iterator fair

.github/workflows/ci.yml, crawl-ref/source/util/checkconventionalcommit.py
Python version in CI doesn't like line 36.
My local version of Python is fine with it.
Split the statement in 2 to satisfy more Python versions.
Also exclude certain branches from main repo.
We're not gonna fix past commit messages.
=> ci: fix checkconventionalcommit.py

crawl-ref/docs/options_guide.txt, crawl-ref/docs/tiles_help.txt, crawl-ref/source/delay.cc, crawl-ref/source/initfile.cc, crawl-ref/source/tilesdl.cc, crawl-ref/source/tilesdl.h, crawl-ref/source/tileweb.cc, crawl-ref/source/tileweb.h, crawl-ref/source/travel.cc, crawl-ref/source/view.cc
This option controls how often we render in milliseconds when resting, exploring, or travelling. However, it was being ignored resulting in large amounts of time being washed waiting for vsync or rendering updates that were never going to be visable. I also, reduced its default value from 100ms to 17ms as 10 fps felt choppy.
=> Fix the tile_runrest_rate option

crawl-ref/source/directn.cc
When targeting outside the map,
`direction_chooser::update_previous_target()` would search for the
monster closest to the target to set as your previous target. However,
the radius_iterator used for this was asserting that the target was
inside the map.
Fixes #4368
=> Don't crash when targeting outside map

crawl-ref/source/l-item.cc
Currently, no way to set inscriptions from lua aside from sendkeys().
That gets messy and spams the dialog.
Added function to append or replace an existing inscription.
=> Add lua function item.inscribe(inscription="", append=true)

crawl-ref/source/beam.cc
When a monster cast phantom blitz with all 700 monsters on a level, the game would crash.
=> Fix a crash when casting phantom blitz (Colgate)

crawl-ref/source/dgn-shoals.cc, crawl-ref/source/ui.cc
Make Crawl shut down correctly in some situations where it didn't already.
Make wizard_mod_tide() respond to seen_hups, rather than ignore it.
Make ui::delay() treat seen_hups as if the user had pressed the Escape key.
=> Don't hang on SIGHUP in wizard_mod_tide().

crawl-ref/source/tileweb.cc
It would be beneficial to indicate status expiration in the tooltip description ui, especially for status like DDoor. 
While this is a workaround, I have implemented it with simple string matching.
Every expiring status wil now display "(expiring)" in its tooltip description. 
we can already check status detail with '@' but it would be helpful check it with addtional ui
| Before (without Expiration Indicator)           | After (with Expiration Indicator)           |
|---------------------------------|---------------------------------------------|
|<img width="411" alt="스크린샷 2024-11-05 오후 5 01 08" src="https://github.com/user-attachments/assets/980f7c2f-fc4b-4266-8423-e2a7feaa21ae">|<img width="410" alt="스크린샷 2024-11-05 오후 5 02 12" …
=> [webTile] : add expiring description for expiring status

crawl-ref/source/command.cc, crawl-ref/source/command.h, crawl-ref/source/macro.cc, crawl-ref/source/tilereg-dgn.cc, crawl-ref/source/tilereg-msg.cc, crawl-ref/source/tilereg-stat.cc, crawl-ref/source/tilereg-tab.cc
We were converting some mouse commands into the key press that would result in that command with default key bindings. For example, if the '<' key was rebound to open the read scrolls menu, clicking on an up staircase you were standing on would open the read scrolls menu.
Fixes #3799
=> Fix the mouse doing incorrect commands when keys are rebound

crawl-ref/source/item-name.cc
Existing code only marks useless misc evokers as such if they're in shops, but if they're just laying on the floor they are currently not considered useless. This is a nuisance in zigs, which have one or more evokers on almost every floor, quickly maxing them out and adding more visual noise to an already overloaded ctrl-X menu.
The hacky inventory check is not ideal, but I couldn't come up with a better solution without going out of my depth and messing with core functions. I checked all edge cases I could think of like standing on +5 evo while having a copy in your inventory
=> Mark maxed out misc evokers as useless if not in player's inventory

crawl-ref/source/map-knowledge.cc
The game makes a note of some features whenever they are marked as "seen". The "forget level map" command clears the "seen" flag for most of the features on the current level, meaning that something could have several notes made about its discovery.
Only make a note the first time something is seen.
=> Stop making notes about once-forgotten features.

crawl-ref/source/dat/descript/features.txt
Zot traps don't actually have the effect of throwing you into the abyss in their effects table so I removed that line in the description and replaced it with petrification.
=> Fixed description of Zot trap to be more accurate

crawl-ref/source/attack.cc, crawl-ref/source/beam.cc, crawl-ref/source/beam.h, crawl-ref/source/decks.cc, crawl-ref/source/evoke.cc, crawl-ref/source/fight.cc, crawl-ref/source/god-abil.cc, crawl-ref/source/god-passive.cc, crawl-ref/source/l-spells.cc, crawl-ref/source/misc.cc, crawl-ref/source/misc.h, crawl-ref/source/mon-abil.cc, crawl-ref/source/mon-act.cc, crawl-ref/source/mon-cast.cc, crawl-ref/source/mon-ench.cc, crawl-ref/source/mon-explode.cc, crawl-ref/source/mon-util.cc, crawl-ref/source/mon-util.h, crawl-ref/source/movement.cc, crawl-ref/source/spl-clouds.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-summoning.cc, crawl-ref/source/spl-transloc.cc, crawl-ref/source/spl-util.cc, crawl-ref/source/target.cc, crawl-ref/source/throw.cc
Players can fire two kinds of tracers. The first is used to check for a target and e.g. gray out your quivered spell if it has no target. The second is fired by functions like `player_tracer` and warns when there are bad targets (e.g. yourself or an ally). Instead of choosing between these two by setting a combination of flags on a bolt before firing it, choose between them by passing a different tracer class to the bolts fire method.
when firing a tracer with the `player_tracer` function don't just warn about one of your allies that would be hit, instead warn about all of them in the same way that melee attacks do (e.g. when using the singing sword). Also, don't spam warnings when firing a starbust that will target you multiple time, instead just say up to how many times the starbust can …
=> Improve player tracers

crawl-ref/source/tilereg-dgn.cc, crawl-ref/source/tilereg-map.cc, crawl-ref/source/tileweb.cc, crawl-ref/source/travel.cc, crawl-ref/source/travel.h
Control left mouse clicking an open door would result in an unknown command message instead of attacking in the direction of the door. The reason for this is that the game would try to close an open door if you control left clicked it and couldn't see a monster on it, but generate the command to do so incorrectly. This is a bad idea as control left clicking is almost always used to attack invisible monsters. This change moves closing doors to shift left clicking and fixes the generation of the command.
Fixes #3801
=> Fix closing doors with the mouse

crawl-ref/source/beam.cc
There shouldn't be a prompt warning you that you will hit your allies with a beam if the beam is harmless to your allies. I accidentally broke this in commit 1564750
=> Fix harmless beams prompting when hitting allies (cool 3)

crawl-ref/source/directn.cc, crawl-ref/source/directn.h
In #1422 several ways to improve accessibility for visually impaired players are discussed. I believe the issue can be closed when this PR is merged.
This PR adds showing location description along with tile descriptions during aiming and viewing.
To enable this feature `Options.monster_item_view_coordinates` needs to be set to true.  See also "Options for blind players" from the options_guide.
Also added some comments to some description methods.
Some pictures (or terminal outputs) to visualize the changes. New is `Location (x, y)`.
```
Fire: e) +0 orcbow
Press: ? - help, Q - select action
Shift-Dir - straight line
Location (0, 3)
sefie the Shield-Bearer           *WIZARD*
Minotaur
Health: 19/19     ========================
#..                   AC:  6 (26%)      Str: 20
#.ß …
```
=> Optionally add target location description

crawl-ref/source/webserver/webtiles/ws_handler.py
When webtiles clients request an rc file's contents,
they send a
`get_rc` message with a `game_id` property. The webt iles sever responds
with a `rcfile_contents` message that has a `content s` property.
Because the response doesn't include `game_id`, the client has to treat this as a stateful request. It has to remember what was recently
requested and can't pipeline multiple requests.
The current webtiles client stores this state in the
UI and will ignore
the additional property. But its existence will simp lify design of
future webtiles clients.
=> feat(webserver): Add game_id to rcfile_contents

crawl-ref/source/dat/clua/autofight.lua
If immotile (e.g. from -Move), we should not wait when you try to autofight by default.
No other case that I can see will wait unless AUTOFIGHT_WAIT is set - why is this one different?
This logic was added last year in 52037ea7a925a6ae6b1b67939267cd8f1f4837a4.
I'm guessing because it was confusing to hit tab and have nothing happen? but mpr would make more sense to me to solve that.
Gate the old behavior behind autofight_wait.
Could add another option for it instead, but it seems consistent with the behavior of the autofight_wait option in general.
Closes #4394
=> bugfix: AUTOFIGHT while immotile should not wait a turn (CrawlOdds)

crawl-ref/source/viewmap.cc
Currently, waypoints are only displayed on otherwise empty squares on the level map view. In combination with them not being xv-able and not reporting any sort of coordinates other than what level they're on, this makes it so that if anything overrides them, they become impossible to find without actually traveling to their exact location.
For my use case, this is a very annoying problem - I use waypoints to track timed portals and mark encounters with monsters that indicate potential branch entrances (e.g. redback on L:3), and in general for annotations that are more location-sensitive where annotating the whole floor doesn't cut it. Especially when scouting portals, being able to see exactly where the waypoints are at all times is very important. I understand that x-marks-the-spot may …
=> console: draw waypoints over other items and features

crawl-ref/source/beam.cc
When trying to shoot through a plant or transparent wall you should get a message such as "Your line of fire to the ogre is blocked by a plant". However, I broke this in commit 1564750
=> Fix player tracers not warning when path is blocked (staticshock)

crawl-ref/source/beam.cc, crawl-ref/source/beam.h
The beam would stop at the enemies, so the warning was incorrect. This was broken in commit 1564750
=> Fix erroneous warning when firing at enemy in front of friendly (dilly)

crawl-ref/source/tilesdl.cc
When zooming in local tiles we call `do_layout` to calculate the new size of the view buffer (as well as other things). however, we need to call `redraw_screen` to actually resize the view buffer before next rendering or the game will crash. We were calling `mprf` before `redraw_screen` which can lead to a force more which can sometimes result in rendering.
This change maybe should be applied to earlier versions to, as in at least version 0.32 zooming in map view mode causes force mores by default.
=> Fix a crash when zooming local tiles (sulla)

crawl-ref/source/target.cc
Passwall had previously assumed LOS 0 was simply impossible, and trying to cast or aim it with 0 LOS triggered an assert.
This will fix #4348.
=> Fix a crash on casting Passwall during Primordial Nightfall

crawl-ref/source/mon-cast.cc
Summon Holies has a summon cap of 4, but the code previously allowed seraphs to make up to at least 8 at once, causing the excess to immediately disappear.
This will fix #4288.
=> Stop Summon Holies trying to summon too many monsters

crawl-ref/source/fight.cc
If you attacked an enemy with a ranged weapon by trying to move into their space and it give you a warning prompt, saying no to the prompt would still spend a turn.
=> Fix bump attacks with range using a turn when cancelled (Kab)

crawl-ref/source/player-reacts.cc
It used to increase by more per turn if your turns were quicker e.g. taking a turn of length 10 auts would increase it by 5 auts but taking a turn of length 1 aut would increase it by 50 auts and a turn being cut short to 0 auts by your rest being interrupted would result in a crash. After this change the increase is equal to half the time your turn took.
=> Change how flayed duration increases when a flayed ghost is in view

crawl-ref/source/god-abil.cc
For Issue https://github.com/crawl/crawl/issues/4456
The constriction removal now happens after the targeting and checking for exclusions.
=> Fix "Aiming Wall Jump instantly removes constriction"

crawl-ref/source/mon-util.cc
When placing an electric eel using wizard mode, if there isn't any water near by it should place water and then place the eel in the water. However, it was placing a floor tile instead.
=> Fix wizmode not being able to place electric eels

crawl-ref/source/mon-util.cc
We where giving eldritch tenacles a habitat of HT_FLYER instead of HT_FLYER | HT_MALIGN_GATEWAY which was preventing them from spawning on the tile containing the malign gateway.
Fixes #4464
=> Fix malign gateway not spawning its tentacle (caiman-dorohedoro)

crawl-ref/source/god-abil.cc
A turn that took 5 auts would spawn in twice the number of orcs that a 10 aut turn would spawn, resulting in 4 times as any orcs spawning per aut. This change makes the average number of orcs spawned per aut the same no matter how long your turns take. It keeps the same spawn rate if you are taking turns of length 10 auts although this might need adjusting as many melee characters can have an attack delay closer to 7 auts when getting blood for blood online which would spawn at about twice the rate with the old system.
This also fixes a crash that would sometimes occur as sometimes turns can be cut short to 0 auts (e.g. when resting is interupted).
=> Fix blood for blood spawning orcs faster the faster your turns

crawl-ref/source/mon-poly.cc
When shape shifter vampire thralls changed shape they would incorrectly lose their thrall status icon.
Fixes #4386
=> Fix shape shifters losing their thrall status icon (Monkooky)

crawl-ref/source/tilereg-map.cc
When ctrl-clicking a spot on the map adjacent to you in local tiles, you perform an attack. If this attack was with a ranged weapon, the arrow animation would stick around until you took a different action.
Fixes #4381
=> Fix arrow animation sometimes sticking around to long

crawl-ref/source/player-equip.cc
In `player_equip_set::get_forced_removal_list` we were passing a comparator to std::sort that returns true for equal items, however, it should return false.
=> Fix an invalid comparator being passed to std::sort

crawl-ref/source/areas.cc
When a monster was using a ranged weapon but had Eos or Brilliance as its backup melee weapon it would incorrectly get a halo/umbra.
Fixes #4487
=> Fix monster backup weapons giving halos/umbras (NormalPerson7)

crawl-ref/source/beam.h
=> Fix uninitialized variables in beam.h (#4491)

crawl-ref/source/mutation.cc
...given that mutations can no longer be partially suppressed. Also simplify the description from "Completely suppressed" to just "Suppressed", and fix some unnecessary whitespace.
=> Change suppressed muts on the A screen from (()) to ()

crawl-ref/source/adjust.cc, crawl-ref/source/quiver.cc, crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-cast.h, crawl-ref/source/spl-selfench.cc
Spells which were not currently useful because there was no targetable monster in sight would be greyed out on the forget/adjust/quiver spell lists.
This will fix #4397.
=> Fix spells being greyed out on forget/adjust/quiver spell lists

crawl-ref/source/describe.cc
The ?/ menu can be used to describe all skills including those that you can't train. However, it would crash when trying to calculate how much your AC/EV/SH would increase by when training the corresponding skill if it wasn't trainable.
=> Fix a crash when describing an untrainable skill

crawl-ref/source/beam.cc, crawl-ref/source/target.cc, crawl-ref/source/target.h
When casting a cloud spell such as freezing cloud, the targeter would try to avoid hitting the player even when they were immune to the cloud.
Fixes #4592
=> Fix the cloud targeter avoiding immune players

crawl-ref/source/tileview.cc
When examining a level that you weren't on, rampage hints would still show up leaking information about where you were relative to the map borders.
=> Fix rampage hints showing on levels you aren't on

crawl-ref/source/terrain.cc
When peeking down a staircase in descent mode, monsters would be left with unidentified wands even though seeing a monster usually identifies its equipment.
Fixes #4495
=> Identify monster equipment when peeking a staircase (napthats)

crawl-ref/source/beam.cc, crawl-ref/source/mon-util.cc
Jiyva currently doesn't turn slime-shaped shifters neutral, but she would previously prevent attacks on them anyway. This behaviour leaves the player (temporarily) with a monster they cannot attack.
I have elected to effect this by not banning attacks on hostile slimes. This may need to be adjusted if there are other ways for hostile slimes to appear under Jiyva; I am not aware of any.
=> Don't let Jiyva ban attacking hostile slime-shaped shifters

crawl-ref/source/dat/des/altar/kiku_cage.des, crawl-ref/source/dat/des/altar/trog_wizard.des
2 altar vaults have harmless monsters behind grates or transparent walls that are supposed to do nothing and die. However, you can dig them out and for a good chunk of xp if you find them early enough. This pr makes them neutral so that they don't give xp and there is no incentive to dig them out (works with sac love too)
=> Make decorative altar monsters neutral

crawl-ref/source/decks.cc, crawl-ref/source/mon-project.cc, crawl-ref/source/mon-project.h
Ever since 45c4a97, the Orb card has had the same effect at its lowest power level (power level 0) as at its highest (level 2), specifically a circle of 4-8 orbs of destruction around the player. At power level 1, it has always just fired a single orb of destruction. Prior to that commit, power level 0 instead cast the old version of Iskenderun's Mystic Blast.
With no suitable pure-conjurations-based replacement for orb of destruction these days, I have elected to keep the orb of destruction theme at power level 0. The effects are now:
power level 0: single orb of destruction using
spell power = card power/10
power level 1: 2-3 orbs of destruction around you using
spell power = card power/6
power level 2: 4-8 orbs of destruction (same as current) using
spell power = card power/6
This …
=> Fix the Orb card

crawl-ref/source/fixedp.h
It was trying to store 2,000,000,000,000 in a long which won't work on 32 bit builds or MSVC builds.
=> Fix a test requiring long to be 64 bit

crawl-ref/source/skills.cc
Listing them all here for ease of viewing:
Octopode 27 UC from Crusher to Kraken to feel more epic and more unique to Op
Octopode/Merfolk 27 Invo Lugonu gets Abyssopelagic (https://en.wikipedia.org/wiki/Abyssal_zone)
Minotaur 27 Invo Ash gets Lord of the Labyrinth (Navigating a labyrinth feels very appropriate for Ash to me)
Merfolk 27 Hexes gets Siren
Octopode 27 Invo with an evil god gets Leviathan (Leviathan is one of those loosely defined mythological creatures, but is definitely a sea monster of some sort, was considered demonic pretty often. Crawl's tainted leviathans are not aquatic at all, so I would understand if this adds unwanted confusion.)
Human of Yred 27 Fighting gets Death Knight (Hell Knight is also specifically a Fighting title, not an Invocations title, so I kept …
=> Add several new skill titles

crawl-ref/source/dat/des/builder/alphashops.des
When alphashops selects an excluded item from an item set (e.g. Wand of Light in a Wand of Acid game), the shop will fill the slot with a random item instead, which will probably not match the theme.
Filter out excluded items to preserve purity.
=> Remove random items from alpha shops

crawl-ref/source/status.cc
... so that *ahem* [certain people](https://crawl.project357.org/morgue/DispaterIsMyDaddy/morgue-DispaterIsMyDaddy-20250518-155010.txt), do not forget to pick them up once they have the orb of zot.
~~Please let me know if I need to assign to `inf.light_colour` here as well~~ done.
=> Make `more_gem_info` show unacquired gems

crawl-ref/source/mon-ench.cc, crawl-ref/source/monster.cc
A kraken can move into temporary deep water such as that created by the summon forest spell and then be left on land when the water reverts back. This should result in the kraken flopping around on land taking damage. However, the check for this was checking if the monster's habitat was HT_WATER and krakens are HT_DEEP_WATER now.
=> Fix krakens not flopping around on land

crawl-ref/source/movement.cc
When you to rampage over blastemotes, still spend a turn on the move even though you only moved one space instead of two due to the -move from the blastemotes.
=> Spend a turn when failing to rampage over blastemotes (Hellmonk)

crawl-ref/source/melee-attack.cc, crawl-ref/source/melee-attack.h
As a coglin, when attacking with an unrand weapon that should give a prompt due to its unrand property (e.g. singing from the singing sword hiting allies) in your primary hand, you would only get a prompt half the time.
Fixes #4558
=> Fix missing weapon prompts on coglin

crawl-ref/source/player-equip.cc, crawl-ref/source/player-equip.h, crawl-ref/source/player.cc
While wearing the fungal fisticloak with gloves on it, trolls would lose the damage from their claws.
Fixes #4598
=> Fix trolls not keeping claws with fungal fisticloak

crawl-ref/source/bloodspatter.cc, crawl-ref/source/bloodspatter.h, crawl-ref/source/mon-cast.cc
Shredding enemies with sawblades feels like it should result in a lot of blood, which it wasn't producing before. I limited each sawblade to only spraying blood in a small area around its victims as its hard to tell where the blood is coming from otherwise.
=> Make diamond sawblades splatter more blood (GnomeSayin)

crawl-ref/source/libconsole.h, crawl-ref/source/libutil.cc, crawl-ref/source/libw32c.cc, crawl-ref/source/mutation.cc
It isn't meant to change the cursor position. However, it was changing it which meant we had to disable some asserts on windows in b0d7ede
=> Fix clear_to_end_of_line for windows console builds

crawl-ref/source/cio.h, crawl-ref/source/libconsole.h, crawl-ref/source/libunix.cc, crawl-ref/source/libw32c.cc, crawl-ref/source/macro.cc, crawl-ref/source/menu.cc, crawl-ref/source/state.cc, crawl-ref/source/state.h, crawl-ref/source/ui.cc, crawl-ref/source/view.cc
Responding to console resize events in menus was disabled in 9746042 as the way we were handling them lead to generating another resize event resulting in an infinite loop. However, this results in the menu becoming fairly unreadable until you exit it and go back in. With a slight adjustment we can use the normal resize handling code in menus as well which doesn't have this problem.
=> Fix resizing the console while in a menu on windows

crawl-ref/source/tileweb.cc, crawl-ref/source/tileweb.h, crawl-ref/source/webserver/webtiles/process_handler.py
When a spectactor joins we send the full map data to the spectator that just joined and record this map data is the last sent map data. However, the player and any pre-exiting spectators might not have received this map data yet and as we set it as the last sent map data it won't be sent again until it changes. To fix this, make sure all the pre-existing clients have the most up to date map data before sending the full map data to the new spectator.
Fixes #1474
Fixes #1637
Fixes #2473
Fixes #2499
Fixes #2704
Fixes #3153
Fixes #3222
Fixes #3489
Fixes #3974
Fixes #4013
Fixes #4169
Fixes #4536
=> Fix a webtiles desync when a spectator joins

crawl-ref/source/monster.cc
Since they're made of mostly ugly thing fragments, they shouldn't polymorph the usual way, and since they don't have different colours the way ordinary ugly things do, disallow their polymorphing, and make their mutation only cosmetic.
(Coincidentally, both of these are exactly how polymorphed/mutated abominations are treated.)
=> Adjust crawling flesh cage polymorphing/mutation.

crawl-ref/source/mon-info.cc
There are various bugs that can result in a monster being in view with an unidentified wand and it would be better not to crash when examining them. For example, monsters opening doors or peeking down a stairscase in descent mode etc can result in you seeing monsters with unidentified wands.
=> Fix a crash when examining a monster with unknown wand

crawl-ref/source/item-use.cc
The text for `easy_floor_use` in the case of floor items didn't have any explicit color information set, causing the color of the nearby cyan text to partially overlap.  This fixes that by just explicitly setting it as lightgray.
Before:
After:
=> fix: make '[X] to wear' text coloring gray

crawl-ref/source/dat/des/branches/temple.des
dpeg_three_leaves_temple places [9 or 21] not [9 or 18] altars.
Hopefully fixes #4725
=> fix: A temple with the wrong number of altars

crawl-ref/source/acquire.cc
Okawaru worshipers cannot make use of this armour ego without abandoning Okawaru. Surely Oka wouldn't encourage the player to abandon!
=> Don't allow Command armour in Okawaru capstone gifts (55-ENN)

crawl-ref/source/stash.cc
This was broken by 01fb971, which made runed doors no longer be considered notable features.
Resolves #4533.
=> Track runed doors in stashes again (#4533)

crawl-ref/source/describe.cc
2 commits, one to display weapon delay in item descriptions (even if you're at the base delay) and one to include your current delay on throwing weapons as well.
---
https://github.com/crawl/crawl/blob/3cd4677b91f90b0ed0b777eed8f9afef84451c52/crawl-ref/source/describe.cc#L2254
I wanted to ask about this `crawl_state.needsave`. This check was performed elsewhere https://github.com/crawl/crawl/blob/3cd4677b91f90b0ed0b777eed8f9afef84451c52/crawl-ref/source/describe.cc#L1506 and I copied it over but I am not sure what it's guarding against exactly. I thought it would be easier to ask about it if I provided the context. Needs attention!
=> Changes with display of current attack delay in weapon descriptions

crawl-ref/source/lookup-help.cc
When typing part of a monster's type into the ?/m menu, it will list all monsters who's type is similar to what you typed in. In this list, monsters that usually have a randomized tile will always show the same tile. However, after selecting one of these monsters to view its description, it will have a randomized tile. To fix this tile mismatch, also don't randomize the tile when viewing the description.
=> Fix tile mismatch on monster lookup menu

crawl-ref/source/xom.cc
prompt_for_int() signals an error to debug_xom_effects() by returning -1, which caused it to create a nonsensical xom_debug.stat file.
Fix this by only generating a file if the user requests a positive number of iterations.
=> Stop debug_xom_effects() (&^X) from trying to run -1 times.

crawl-ref/source/dungeon.cc, crawl-ref/source/traps.cc, crawl-ref/source/wiz-dgn.cc, crawl-ref/source/wiz-dgn.h
In wizmode, don't ask which trap to make if the type is already specified. Also, fix trap always made at the character's tile even when told to make at another place.
Fixes #4757.
=> Don't ask which trap to make if already specified (and fix some minor issues)

crawl-ref/source/dat/mons/cloud-mage.yaml, crawl-ref/source/dat/mons/headmaster.yaml, crawl-ref/source/dat/mons/hellbinder.yaml, crawl-ref/source/dat/mons/pandemonium-lord.yaml, crawl-ref/source/dat/mons/player-ghost.yaml, crawl-ref/source/mon-flags.h, crawl-ref/source/mon-util.cc, crawl-ref/source/mon-util.h, crawl-ref/source/view.cc
When Beogh wrath sent a named orc after you with other orcs, the "comes into view" message would have a stray 'a' or 'an' before the orc name, for example "An Olfrun and 2 orcs come into view."
Fixes #4724
=> Fix comes into view messages for named orcs (cfcfcfcfcfcfcfcfcfcf)

crawl-ref/source/dat/des/altar/lugonu_bribe.des
The lugonu_bribe vault is supposed to place an orb of light on its alter when the player first sees it if the player worships The Shining One, however, it was using the wrong item spec for creating one which resulted in an error showing up in the player's message log instead.
=> Fix a vault failing to place an orb of light

crawl-ref/source/l-crawl.cc
Lua API lists `Regex:find()` when it's actually `Regex:matches()`.  Updated the docstring to reflect this. Updated cpp function name to follow existing pattern.
Built and tested with `make -j4 TILES=y BUILD_PCRE=y` on MacOS tiles.
Tested in lua interpreter. Works as intended.
=> Correct Lua Regex:matches() doc/name

crawl-ref/source/god-conduct.cc
Piety gain for Okawaru scales with the difficulty of the monster faced; the gain is otherwise identical to that of other gods (which, I imagine, is why mention of its special scaling was omitted). This commit adds an acknowledgement that Okawaru "really likes" it when you kill tougher monsters.
Notes:
- Okawaru is placed at the end of the switch statement, specifically to line up with the comment that "unique/unusual piety gain methods [should go] first" -- killing stronger foes isn't *that* unusual or unintuitive.
- Also, the specific wording -- "challenging foes" -- is somewhat intended (if imperfect?). Objective mightiness is surprisingly not relevant; instead, the relative strength of the monster to your character is what matters.
Closes #4656.
=> Note Okawaru's joy of hard battles in Powers screen

crawl-ref/source/tilepick-p.cc
Quill form is not a full-body polymorph like Dragon or Fortress Crab; it only alters certain body parts, similar to Hive or Maw. Therefore the tile should preserve the player's original species silhouette.
Genies and nagas already have bespoke lower-body tiles for this purpose, but merfolk were left wearing a humanoid "legs" layer on top of their fish tail. Copy the approach used for Hive: when a merfolk is in water (fishtail active) simply crop the bottom of the Quill armour tile so the tail remains the only visible lower extremity. This produces a clean, species-consistent sprite.
After fix:
_on land_
_in water_
=> Fix merfolk fish-tail clipping in Quill form

crawl-ref/source/beam.cc, crawl-ref/source/map-cell.h, crawl-ref/source/mon-ench.cc, crawl-ref/source/monster.cc, crawl-ref/source/monster.h, crawl-ref/source/player-equip.cc, crawl-ref/source/show.cc, crawl-ref/source/tag-version.h, crawl-ref/source/tags.cc
Usually, when we show invis indicators we show them where the monster is. However, when a monster turns invisible and then moves in just one player turn, we would show the invis indicator at the square where the monster went invisible (or an adjacent square if there is now a monster in this square). This happened rarely enough that players usually thought that it was a bug. Instead, when showing an invis indicator, we should always show it on the square with the monster.
This also brings some sanity to the `show_update_at` function as it now only affects the location that we told it to affect.
=> Make invis indicators accurate

crawl-ref/source/dat/descript/features.txt, crawl-ref/source/dat/descript/monsters.txt
There's sunlight in shoals and thus not 'dank' or 'in the absence of sun' so note that when describing a plant, fungus,
or ballistomycete. (Closes #4452)
=> Improve plants mon descriptions
