crawl/crawl

crawl-ref/source/ghost.cc
Treat rF and rC the same during Panlord generation, and make SInv random too.
=> Panlord resists

crawl-ref/source/dungeon.cc
There were some weird old artifacts in there and some missing new gods.
Xom also now gets a fixed chance of appearing anywhere.
=> Update random altar god distribution.

crawl-ref/source/dat/des/portals/volcano.des
The former and almost certainly the latter seem unintended.
=> Add cloak to make_fiery_armour & swap lajatang/glaive weight.

crawl-ref/source/spl-summoning.cc
random_choose is better than coinflip when applicable, and certainly better than a switch/case!
=> Simplify choice of dragons in Dragon's Call

crawl-ref/source/beam.cc
Before this patch, briar patches hit by TSO's cleansing flame display the message "The briar patch writhes in agony!"
=> Don't let plants writhe in agony

crawl-ref/source/mon-util.cc
Instead of `if (x) return true; else return false;`, just `return x`;
=> Remove needless if/else

crawl-ref/source/dat/descript/monsters.txt
Envelope is a noun, envelop is a verb.
=> Fix spelling

crawl-ref/source/command.cc, crawl-ref/source/main.cc, crawl-ref/source/wiz-you.cc, crawl-ref/source/wiz-you.h
Your actions all take 0 turns while this is on.
=> Add "freeze time" option to wizmode

crawl-ref/source/dat/descript/quotes.txt
Spelling corrections in quotes
=> Spelling corrections in quotes

crawl-ref/source/dat/descript/quotes.txt
=> Quote for Azrael

crawl-ref/source/dat/descript/quotes.txt
=> Quote for reaper

crawl-ref/source/itemprop.cc
I found this a while ago just looking up how something works. This pointless brevity served only to confuse.
=> Expand jarring abbreviation in a comment

crawl-ref/source/describe.cc, crawl-ref/source/player.cc
I spent 15mins today wondering why my attacks were not always at mindelay, which probably reflects poorly on me, but I figure we can stop other newbies making the same mistake :star2:
=> Show your skill for shields (like weapons).

crawl-ref/source/ability.cc
Tested with dracs and non-dracs picking up ring of tele and then levelling up to 7
https://crawl.develz.org/tavern/viewtopic.php?f=8&p=245372#p245372
=> Drac breath slot

crawl-ref/source/itemprop.cc, crawl-ref/source/itemprop.h, crawl-ref/source/newgame.cc
For the Throwing option, the hunting nets the player also receives are
shown. For launchers, the type of ammunition the player also receives
is shown.
=> Give the player more information on the ranged weapon loadout screen

crawl-ref/source/dat/des/branches/temple.des
=> A temple offering.

crawl-ref/source/religion.cc
Put Donate Gold on "e", after more commonly used invocations.
=> Tweak Zin ability letters

crawl-ref/source/evoke.cc, crawl-ref/source/item_use.cc, crawl-ref/source/item_use.h, crawl-ref/source/misc.cc, crawl-ref/source/player-act.cc, crawl-ref/source/player.cc, crawl-ref/source/spl-cast.cc
Noise was generated inconsistently, mostly for lore's sake it seems.
=> Make amulets of stasis silent.

crawl-ref/source/xom.cc
Like Trog does with antimagic.
=> Let Xom chaos-brand god gift weapons.

crawl-ref/source/dat/des/branches/temple.des, crawl-ref/source/dat/des/portals/icecave.des, crawl-ref/source/dat/des/portals/ossuary.des
An ancient temple, mostly destroyed and covered in water. 6-12 altars,
with the missing altars replaced by faded ones.
=> Temple vault: Sunken Temple

crawl-ref/source/attack.cc
Split the proc chance out so it can be tweaked individually.
=> Simplify distortion_affects_defender.

README.md
=> Fix monster_speech.txt link in README.md

crawl-ref/source/viewmap.cc
Implemented by just removing the arity of _find_feature that is
passed a feature list, instead always using the one that scans the
whole map. Slower to be sure, but not terribly important.
=> Let XE show you exclusions in unexplored terrain

crawl-ref/source/webserver/game_data/static/monster_list.js, crawl-ref/source/webserver/game_data/static/style.css
This is a bit preliminary in that it works, but looks kind of bad because I don't know what I'm doing when it comes to CSS. Screenshot attached. Is there anyone who does know what they're doing who can help?
Comments on the approach are also welcome.
=> Show monster health in webtiles with tile_display_mode = glyphs

crawl-ref/source/dat/dlua/ziggurat.lua
Reverts crawl/crawl#207
Per @gammafunk & @MarvinPA , there are issues with some of the new sets (too much variance in threat between sets), and reducing the floor filling was undesirable.
=> Revert "Zig stacking: slow down floor-filling, scale sets instead"

crawl-ref/source/mon-gear.cc
=> Orc shields

crawl-ref/source/Makefile, crawl-ref/source/rltiles/Makefile
Most of these fix build failures.
=> A few build system improvements

crawl-ref/source/godabil.h, crawl-ref/source/mon-info.cc, crawl-ref/source/mon-util.cc, crawl-ref/source/religion.cc
Randomization of resist unlocks for H's ancestor.
=> Chequers' combo god stuff

crawl-ref/source/describe.cc, crawl-ref/source/ghost.cc
Mess around with AC/EV, rF/rC immunity, and rElec levels
=> Panlord tweaks

crawl-ref/source/art-data.txt, crawl-ref/source/attack.cc
This gives it AUTOMATIC_HIT, but also reduces its enchant.
=> Improve Unrand: Sniper

crawl-ref/source/dat/database/rand_all.txt
=> more fun randart strings

crawl-ref/source/items.cc
Remove digging and disintegrate from wand of random effects. See https://crawl.develz.org/tavern/viewtopic.php?f=8&t=19945
=> Remove digging and disintegrate from wand of random effects

crawl-ref/source/dat/database/rand_arm.txt
(fit better grammatically with the randnames they can appear in)
and add a few more while I'm here!
=> make a few randart strings fit better

crawl-ref/source/melee_attack.cc, crawl-ref/source/mon-death.cc, crawl-ref/source/mutation.cc, crawl-ref/source/mutation.h, crawl-ref/source/player-reacts.cc
Both these commits are pretty crazy on d:1-d:5 after my past changes, here's an attempt to make them more sensible.
Spiny commit is done, but I'm looking for comments on the powered by death rework. I think the numbers need further tweaking.
=> Ds mut nerfs

crawl-ref/source/player.cc, crawl-ref/source/xom.cc
Fix an invisibility check and improve some #xomcode 🎲
=> Improve some Xom/Invisibility code

crawl-ref/source/dat/des/portals/ossuary.des
These things are more dangerous than an ogre, in a portal that players can typically count on being low in danger and poor in loot. Nasty surprise for the unspoiled, especially players with a few wins under their belt who know what to expect from low-level portals.
Still deals 25 damage!!!!!!!!!! but is a lot easier to kill... if it doesn't 1-hit the Spriggan/DE player.
=> nerf ossuary bog body

crawl-ref/source/duration-data.h, crawl-ref/source/enum.h, crawl-ref/source/main.cc, crawl-ref/source/player-reacts.cc, crawl-ref/source/xom.cc, crawl-ref/source/xom.h
Turn it from a "bad" effect (which was really more a no-op) to a good
effect that leaves a random cloud trail behind you.
This is considered good because you can use it to cut off monster
pathing and so on, although cutting off your escape is a potential
problem.
=> Rework Xom's smoke trail.

crawl-ref/source/xom.cc
Don't try to confuse monsters that will never give XP (oods,
battlespheres, etc) (minmay).
Change how Xom player confusion works -- be less likely to confuse
surrounding creatures as severity increases.
=> Standardise Xom confusion application.

crawl-ref/source/l_item.cc
=> Remove an un-unused include

crawl-ref/source/dat/descript/features.txt
Dug into features.txt to slightly rewrite the Desolation entry description per PF, ended up reorganizing that file.
=> New Desolation entry description

crawl-ref/source/mon-util.cc
Signed-off-by: Naruni <kram321@gmail.com>
=> Dithmenos now gives piety for killing flaming dancing weapons (10417)

crawl-ref/source/art-func.h, crawl-ref/source/describe.cc, crawl-ref/source/food.cc, crawl-ref/source/invent.cc, crawl-ref/source/itemname.cc, crawl-ref/source/main.cc, crawl-ref/source/nearby-danger.cc, crawl-ref/source/ouch.cc, crawl-ref/source/player.cc, crawl-ref/source/player.h, crawl-ref/source/tags.cc
Clarify what's happening in the case of felids/wizmode, and also doesn't
overlap terribly with lots of other text.
=> Rename 'dead' to 'pending_revival' (|amethyst)

crawl-ref/source/ng-wanderer.cc
Refactors _good_potion_or_scroll() and clarifies a few species checks.
=> Fix VSWn getting !HW (10669)

crawl-ref/source/dat/des/altar/overflow.des
"WORSHIP ME, MORTAL," Xom booms, "AND I SHALL GRANT YOU THE GREATEST GIFT OF ALL."
ppY
A goblin pops into existence! It looks at you with admiration.
"Friendship. The greatest gift is friendship!"
=> New Xom overflow altar

crawl-ref/source/dat/database/monspeak.txt
https://crawl.develz.org/mantis/view.php?id=10677
=> First-person hissing (10677)

crawl-ref/source/mon-cast.cc
Really a very minor change, but seems cute.
=> Cantrip message variety (9055, Xelif)

crawl-ref/source/butcher.cc, crawl-ref/source/directn.cc, crawl-ref/source/evoke.cc, crawl-ref/source/food.cc, crawl-ref/source/godpassive.cc, crawl-ref/source/item_use.cc, crawl-ref/source/itemname.cc, crawl-ref/source/itemname.h, crawl-ref/source/items.cc, crawl-ref/source/travel.cc
I felt like this name better described what the function is being used for.
=> Replace get_menu_colour_prefix_tags with menu_colour_item_name

crawl-ref/source/itemname.cc
=> Add missing semicolon

crawl-ref/source/main.cc, crawl-ref/source/stash.cc
Just a little bit of code cleanup.
=> Clean up two dead stores

crawl-ref/source/ability.cc, crawl-ref/source/attack.cc, crawl-ref/source/beam.cc, crawl-ref/source/godabil.cc, crawl-ref/source/godpassive.cc, crawl-ref/source/godwrath.cc, crawl-ref/source/itemprop.cc, crawl-ref/source/ranged_attack.cc, crawl-ref/source/religion.cc
Mainly a crash-stopping fix, and some QOL and rebalancing.
=> Ieoh Jian day one patch + DLC

crawl-ref/source/libunix.cc
When a colour flip would likely result in an invisible glyph, prefer
to resolve the issue by adjusting the background colour instead of the
foreground colour.
This typically results in a significantly more noticeable flip than one
resolved using a foreground colour adjustment.
Additionally, adjust some related comments for clarity.
=> Adjust the background colour for invisible flipped colours (|amethyst)

crawl-ref/INSTALL.txt
Void Linux prerequisites have been added.
=> Void Linux prerequisites have been added

crawl-ref/source/tags.cc
(ab781cdc92f8 and 4c9d53b3c18c7e)
This commit repairs saves where the desolation branch's place info had
been spuriously set to global after _reset_game.  These changes couldn't
be cherrypicked because they use a minor version increment to time-limit
the check in trunk.  This commit also rolls in some smaller changes to
the same code region from ab50500f2268832.
=> Backport fix for loading saves with corrupted branch_info (0.19 backport)

crawl-ref/source/dat/des/sprint/arena_sprint.des, crawl-ref/source/dat/des/sprint/fedhas.des, crawl-ref/source/dat/des/sprint/linesprint.des, crawl-ref/source/dat/des/sprint/menkaure.des, crawl-ref/source/dat/des/sprint/pitsprint.des, crawl-ref/source/dat/des/sprint/red_sonja.des, crawl-ref/source/dat/des/sprint/sprint_mu.des, crawl-ref/source/dat/des/sprint/zigsprint.des
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Add Wu Jian Council to Zigsprint.

crawl-ref/source/dat/database/monspeak.txt
maybe pikel's fine as-is, maybe not. maybe taking out the creepy stuff would be an improvement?
*shrugs*
=> make pikel less awkward

crawl-ref/source/xom.cc
=> Invert conditional

crawl-ref/source/item-use.cc
Add a missing question mark to the Wear prompt.
=> Fix "Wear which item" typo

crawl-ref/source/dat/descript/cards.txt
All but three cards had sentences starting with "Drawing this card ....", and now they all do.
=> Use consistent wording on cards

crawl-ref/source/skills.cc
Making a PR instead of committing directly to get Travis to run over it, and leave time for complaints from verbosity lovers before I merge.
=> Simplify some expressions in skills.cc

crawl-ref/source/item-prop.cc, crawl-ref/source/notes.cc, crawl-ref/source/notes.h
This is a more thorough implementation of aolowin's idea in #582. I've tested and it seems to work, but I would welcome a style/correctness review from anyone before merging.
=> Improve notes for finding unrand items

crawl-ref/source/dat/des/arrival/simple.des
First time writing vaults. I started with basic arrival vaults.
=> Several arrival vaults

crawl-ref/source/describe-god.cc
Don't list Chei supporting attributes for Gnolls in the god description
screen.
=> Don't list Chei attribute support for Gnolls (#11183)

crawl-ref/source/command.cc, crawl-ref/source/menu.cc, crawl-ref/source/menu.h, crawl-ref/source/tilesdl.cc
This fixes a bug where the message region would add and remove lines
repeatedly as the window was slowly made less tall.
=> Fix tiles message region resize behaviour

crawl-ref/source/menu.cc
Looks like I borked this one earlier; sorry about that!
=> Fix formatted_scrollers not redrawing after line_up()

crawl-ref/source/religion.cc
Fixes #11275 on Mantis and also improves messages for losing **** and ***** abilities.
=> Improve WJC messaging (sokol815)

crawl-ref/source/monster.cc, crawl-ref/source/monster.h
Now Maurice should give proper message in the form of "Maurice steals 1 of your 2 scrolls of immolation!"
=> Improve Maurice's message and fix #11241

crawl-ref/source/menu.cc
I missed these when doing 417d9d2c4b
=> Fix webtiles section boundaries not being updated

crawl-ref/docs/crawl_manual.rst
This spell no longer exists and potions of haste don't contaminate you anymore.
=> Remove reference to Haste

crawl-ref/docs/options_guide.txt
This fixes mantis issue #11323; I only fixed the two known issues mentioned.
=> Fix some outdated info in options guide

crawl-ref/source/travel.cc
replace string#find() to starts_with().
=> fix explore_discoveries::cleaned_feature_description()

crawl-ref/source/tilepick.cc, crawl-ref/source/tilepick.h
This fixes monsters' tiles varying on the ?/M screen.
=> ?/M monster tile improvements + fixes

crawl-ref/source/religion.cc
pretty straight-forward: I'll merge this after the tournament finishes unless there's any objection to the change
=> Shorten Trog ability description to fit in one line

crawl-ref/settings/init.txt, crawl-ref/settings/neo_command_keys.txt
See http://www.neo-layout.org/ (german) or https://en.wikipedia.org/wiki/Keyboard_layout#Neo for some information on the layout.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crawl/crawl/566)
=> Add neo command keys

crawl-ref/source/evoke.cc
This works, but I'm pretty unfamiliar with this part of the code so I'd appreciate a double-check.
=> Fix traps not being activated by wind-blasted actors

crawl-ref/source/art-func.h
All ye who think ifs are better for control flow than functions, speak now or forever hold your peace.
=> Simplify code for changing pluses on mace of Variability.

crawl-ref/source/player-equip.cc
This commit incorporates the suggested changes from aidanholm in my previous PR, #736, while simultaneously removing all the extra commits I had inadvertently created.
=> Fix the message order when unwielding Fragile weapons (damerell, #11427)

crawl-ref/source/dat/database/monspeak.txt
Since TSO no longer hates poison, this line doesn't make any sense.
=> Change Donald's line about TSO worshipper's rPois ring to rN

crawl-ref/source/dat/descript/status.txt
Since this mechanic was removed in 74fa8348.
=> Remove references to loud noises breaking mesmerisation and fear

crawl-ref/source/dat/des/builder/layout_halls.des, crawl-ref/source/dat/des/builder/layout_pools.des
Small changes to address TODOs on a couple of layouts.  Originally [posted on Mantis](https://crawl.develz.org/mantis/view.php?id=11214) a while back; @ebering requested I submit a pull request so he could more easily see what was changed.
=> Layout tweaks

crawl-ref/source/player-equip.cc
https://crawl.develz.org/mantis/view.php?id=11692
No gameplay effects.
=>  Properly notify non-users of Gourmand

crawl-ref/source/player-equip.cc, crawl-ref/source/tilemcache.cc
Also fix an issue with 394fb52 not properly accounting for trolls.
=> Clean up some code

crawl-ref/source/throw.cc
This commit makes it so that both the f and F methods of firing
ammunition end up calling the _fire_choose_item_and_target function,
which sets up the direction chooser with the behaviour required to get
blowgun chances, net immunity descriptions and chaotic descriptions (for
silver ammo) to display.
Previously this function was only called when targeting through f, which
meant that all three of these extra pieces of information were not
provided when firing through F.
I also made a docstring. If anyone has any improvements to the docstring I can do them if you want.
=> Show blowgun chance on firing with F (11777)

crawl-ref/source/religion.cc
=> Make god gifts interrupt & clear runrest delays only (11825)

crawl-ref/source/l-you.cc, crawl-ref/source/output.cc, crawl-ref/source/output.h
Two new functions return the number of pips for each of these
resistances.
=> Expose MR and Stealth to Lua

crawl-ref/source/dat/species/vampire.yaml
Fixes bug #11870
Bug was introduced when species data was moved to yaml in 0.23
=> Remove incorrect fake_mutations from vampire (11870)

crawl-ref/source/item-use.cc, crawl-ref/source/l-you.cc
Corrects a couple of comments.
=> Correct comments

crawl-ref/source/religion.cc
Typo.
Is master the correct branch to do this against?
=> Typo, update religion.cc

crawl-ref/source/movement.cc
When attempting to move into a closed door with the wall_jump_move
option set to true, the function wu_jian_can_wall_jump was being called,
which meant spurious messages describing why wall jumping was impossible
in the current situation were being printed to the message log.
To fix this, move the check for moving into a closed door (a situation
where it is not possible to wall jump by moving) to inside the
definition of bool can_wall_jump, before the function
wu_jian_can_wall_jump() is called.
=> Fix spurious message on moving into door with wall_jump_move (11940)

crawl-ref/docs/crawl_manual.rst
Actually, after each release a tournament will be held, but I do not think, it is relevant at this point.
=> There are two tournaments per year.

crawl-ref/docs/crawl_manual.rst
I have used texts from https://crawl.develz.org/trunk/changes.txt
=> Wands have an other behavior since the wand merge

crawl-ref/source/dat/des/portals/wizlab.des
This can generate in some wizlabs still.
=> Remove reference to Akashic Record in wizlab.des (Mintice)

crawl-ref/source/monster.cc, crawl-ref/source/terrain.cc, crawl-ref/source/transform.cc
I commented on two of these on the Mantis tracker but figured I'd go ahead and open a PR. I'm still very new to the DCSS codebase so if there's a better way to implement any of these fixes please let me know!
=> Three Bugfixes (11954, 11965, 11967)

crawl-ref/source/dat/descript/ability.txt
Now that vampires are hungerless.
=> Remove blood from Gozag shop description

crawl-ref/source/dat/descript/items.txt
=> Update scroll of brand weapon description

crawl-ref/source/dat/descript/features.txt
=> Mark trove portals as single-use

crawl-ref/source/dat/descript/unrand.txt, crawl-ref/source/fight.cc
This PR is actually two separate Mantis tickets:
https://crawl.develz.org/mantis/view.php?id=11907
https://crawl.develz.org/mantis/view.php?id=12093
They are both simple text fixes that I tried to solve as minimally as possible.
=> Minor Text Fixes - Two Tickets

crawl-ref/source/throw.cc
853fe2e fixed this for harming allies, but not yourself.
=> Warn when exploding portal projectiles would hit you

crawl-ref/source/food.cc
Currently if the player is about to starve to death, they will
automatically eat from their inventory if they have food available.
Since the player can now eat directly from the floor, this commit
extends that check to seeing if there is anything available to eat on
the floor.
This is an edge case and not likely to matter often, but it's good to
have consistent and unsurprising behaviour. I take it the intention of
commit 2474f45a (which added forced eating when starving) was just about
eating rather than starving, if it's possible, and that nothing special
about the location of the food in inventory was intended; if that's
right, this commit updates behaviour to be in line with that intention.
As a player I wouldn't expect location of the food to matter, only that
the game is kindly not …
=> Make the game check the floor when emergency eating

crawl-ref/source/attack.cc
* Common effects added: might, agility
* Rare effects added: infestation, unravelling, chain of chaos
* Cloning can sometimes make neutral/friendly copies of monsters
* Level 0 miscasts removed, and miscast overall chance reduced
=> Add some more chaos brand effects

.gitignore
This directory contains editor config for VS Code for the repository. It includes things like default include paths, cpp standard, compiler path, and so on.
=> Ignore VS Code editor config

crawl-ref/source/stairs.cc
So there's no ambiguity about "will they open again"?
Inspired by watching a player on CPO.
=> Change the messaging for abandoned shops

crawl-ref/source/dat/descript/spells.txt
Dragons were cut from the spell and replaced with lindwurms in 9b5a2163.
=> Update Summon Drakes description

crawl-ref/source/traps.cc
Is American (color, practice) or British (colour, practise) spelling preferred?
=> Typo Fixes

crawl-ref/source/dat/database/rand_all.txt
tired of seeing Foo's Supremacy on items!
=> Add more kinds of divine favor

crawl-ref/source/util/checkwhite, crawl-ref/source/util/server/install-ubuntu-chroot, crawl-ref/source/util/server/port-dgl-chroot, crawl-ref/source/util/server/setup-build-chroot
This adds some scripts for migrating aging server chroots to newer ubuntu images.
=> WIP: Add server chroot migration scripts

crawl-ref/source/travel.cc
Also, fix autotravel trying to path around shafts and ignoring shorter routes.
=> Allow autotravel to shafts (12196)

crawl-ref/source/dat/des/branches/spider.des
Currently, `nicolae_crawler_farm` has a few demonic crawlers trapped behind lava,
because they can no longer cling to walls.
=> Free the crawlies

crawl-ref/source/cluautil.h, crawl-ref/source/l-crawl.cc, crawl-ref/source/l-dgn.cc, crawl-ref/source/l-dgnbld.cc, crawl-ref/source/l-dgnit.cc, crawl-ref/source/l-dgnmon.cc, crawl-ref/source/l-item.cc, crawl-ref/source/l-los.cc, crawl-ref/source/l-mapgrd.cc, crawl-ref/source/l-moninf.cc
It would be useful to get some more eyes on this.
=> Lua userdata memory management fixes

crawl-ref/source/god-passive.cc
Found a missing word, and added it back in.
=> Fixed a typo in god-passive.cc

crawl-ref/docs/develop/git/quickstart.txt, crawl-ref/docs/develop/god_creation.txt, crawl-ref/docs/develop/monster_creation.txt, crawl-ref/docs/develop/mutation_creation.txt, crawl-ref/docs/develop/patch_guide.txt, crawl-ref/docs/develop/tiles_creation.txt, crawl-ref/docs/develop/translation.txt
Why yes I **am** fun at parties.
=> Fix up some typos in the docs folder.

crawl-ref/source/fight.cc
TSO blocks all stabs, not just on intelligent monsters.
=> Fixed TSO stabbing comment

crawl-ref/source/dat/database/monspeak.txt
0.01% of players will quaff lig right after they get this, and
they'll think they made the joke up.
Devilry revelry:
Grinder the shadow imp
came 'round the corner with
"Make like a tree!"
Who would have known that my
lignificational
beverage wasn't quite
his cup of tea?
=> Add Grinder taunt "Make like a tree!"

crawl-ref/source/dat/des/builder/alphashops.des
Book was renamed from Enchantments to Hexes in d415a3f.
=> Move book of Hexes from E to H alphashop

crawl-ref/source/dat/database/monspeak.txt
Donald has been saying nothing to followers of Wu Jian Council.
It seems that DCSS database could not accept the concept of Democracy.
=> DonaldSpeak_Wujian bugfix

crawl-ref/source/describe-spells.cc, crawl-ref/source/webserver/game_data/static/ui-layouts.js
Commit 9d7e6eef added this functionality to console and Local Tiles.
Also, since `_effect_string()` already returns a hex chance, deduplicate
some code.
=> Show monster spell damage on xv in WebTiles

crawl-ref/source/dat/descript/cards.txt
The card is no longer capable of banishing the user (and hasn't been for quite some time).
=> Fix "The Exile" Description

crawl-ref/docs/crawl_manual.rst
Replace Centaurs with Palentongas in size description,
change WL to Will, remove note about ghosts not using stairs,
clarify traps, add max hp to monster description.
=> Small corrections in the manual

README.md
Fixes the link to the quickstart.md file in README.md.
=> Fix link to quickstart.md

crawl-ref/source/database.cc, crawl-ref/source/english.cc, crawl-ref/source/english.h, crawl-ref/source/game-options.cc, crawl-ref/source/game-options.h
According to Cppcheck, this is "usually faster" than passing by value
and "recommended in C++."
=> Pass some parameters by reference

crawl-ref/source/dat/des/branches/shoals.des, crawl-ref/source/dat/des/variable/mini_monsters.des
The map was a PLACE: instead of a DEPTH:, fix this, and
move the vault to shoals.des, since it only appears there
anyhow.
=> Fix: Don't guarantee nzn_prometheus_bound

.github/workflows/ci.yml
No breaking changes. Several minor improvements to performance. Will hopefully reduce incidence of spurious errors.
=> Migrate to actions/cache v2 (was v1)

crawl-ref/source/util/art-data.pl
Stop art-data.pl from rewriting files which haven't changed.
Before writing to an output file, art-data.pl now reads the file, and only writes it if the new version is different.
This should reduce the number of files make rebuilds when art-data.txt is changed. In particular, many files depend on art-enum.h, but this only stores the names and ID numbers of artefacts, so need only be rewritten when they change.
=> Stop art-data.pl from rewriting files which haven't changed.

crawl-ref/source/skills.cc
=> Add another species title

crawl-ref/source/Makefile, crawl-ref/source/webserver/templates/client.html
File was added with 7ddf969 but needs to be added here to appear in
webtiles.
=> Add the AK splash screen to webtiles

crawl-ref/source/dat/des/branches/vaults.des, crawl-ref/source/dat/des/portals/trove.des
New treasure trove with some Trog acquirements mixed in with the usual weapon trove loot.
Also a minor update to a Vaults entry of mine to vary the wall types used.
=> New Trog-themed trove

crawl-ref/source/dat/des/branches/spider.des
This vault was significantly nerfed when spiders lost the ability to climb. Replaces non-climbing stuck spiders with hornet.
=> Fix Scorpion pit Vault

crawl-ref/source/dat/des/variable/mini_monsters.des
d:1 adders should not be allowed
=> Remove d:1 adder in vault

crawl-ref/source/dat/des/variable/mini_features.des
Self explanatory pls mash that merge button.
=> Very important vault.

crawl-ref/source/dat/des/altar/ecumenical.des
It wasn't green enough. Oops sorry.
I'm not sure which one is more inappropriate between making pr for this ONE change or asking devs to fix it. I chose the former.
=> Minor fix for gnrine

crawl-ref/source/webserver/game_data/static/player.js
Highlight boosted AC when palentongas curl up.
=> Highlight Curl's AC boost on webtiles HUD (12567)

crawl-ref/source/religion.cc
Deng Ai, Jiang Wei, Zhang Bao, Sun Luban(especially this one) are not appropriate for the masters of martial arts council.
=> WJC Sifu names change

crawl-ref/source/dat/des/builder/shops.des
Idea in conjunction with nicolae; a shop that sells great gear for 1 gold,
appearing only on Zot:5.
=> New Zot:5 shop vault

crawl-ref/source/dat/des/branches/spider.des
Now you, too, can collect a star_item in 0.5 a presses
=> New spider minivault

crawl-ref/source/dat/species/barachi.yaml
Four weren't enough. Let players do something else more.
=> Add Wr and AM for Ba recommends

crawl-ref/source/dat/descript/quotes.txt
=> Second Antaeus quote

crawl-ref/source/dat/descript/quotes.txt
I have added (and in one case changed) various quotes for items, monsters, spells, features, and so forth.
=> Adding new quotes to the Crawl quotes list

crawl-ref/source/dat/des/branches/blade.des, crawl-ref/source/dat/des/branches/elf.des, crawl-ref/source/dat/dlua/vault.lua
As promised, the Hall of Blades vaults for Elf are in a separate pull request, ywgf
=> Some new vaults for the Hall of Blades

crawl-ref/docs/develop/levels/syntax.txt, crawl-ref/source/dat/des/branches/elf.des
Some new vaults for Elf; additions to the Hall of Blades section will get their own pull request, at gammafunk's suggestion.
=> Some new vaults for Elf

crawl-ref/source/dat/database/rand_wpn.txt
=> Add a few more _anger_possessive_ strings

crawl-ref/source/dat/descript/quotes.txt
Scroll of tele quote (ADMIN) moved to Swiftness, at PF's
suggestion. Existing scroll of fear quote moved to /dev/null,
it's not even by Plato, and replaced with old eidolon quote.
Add new quotes, featuring T.S. Eliot, Homer, Lovecraft, Pablo
Neruda, Shakespeare, Lord Byron, Nine Inch Nails, and more.
=> Rearrange existing quotes and add new ones

crawl-ref/source/dat/descript/items.txt
=> fix: typo: Correct a typo in the description of the Book of Pain

crawl-ref/docs/options_guide.txt
Changed '-=' to '+=' to correctly describe default behavior.
=> Updated documentation of use_animation

crawl-ref/source/initfile.cc, crawl-ref/source/tileweb.cc, crawl-ref/source/webserver/game_data/static/action_panel.js
This PR adds a main menu button to the action panel and refactors code for drawing actions and item glyphs.
=> Main menu button for the action panel

crawl-ref/source/dat/des/builder/shops.des
Issue was reported here: https://github.com/crawl/crawl/issues/2039
Based on the seed provided, the vault was nicolae_take_the_stairs
My fix is to just add some extra padding (floor tiles) around the outside.
=> Edit a vault to prevent breaking level connectivity

crawl-ref/source/dat/des/branches/spider.des
A brief pass through spider vaults. Updates entry vaults and endvaults (as well as a few miscellaneous ones) and adds two new entries, two new ends, and a few other vaults.
=> Spider vaults

crawl-ref/source/evoke.cc
"A hideous howling noise" was a lie: the horn has never produced a sound.
This commit gives the horn a proper noise.
=> The final element of the Hell reform

crawl-ref/source/webserver/webtiles/config.py
=> Use append for lists, not add

crawl-ref/source/webserver/webtiles/ws_handler.py
Return boolean success.
Also add a missing import used in on_message.
Fixes #2382.
=> Change return signature for set_rc

crawl-ref/source/dat/descript/mutations.txt
Filling some holes in mutations.txt
=> Add descriptions for a few resistance mutations

crawl-ref/source/dat/database/rand_all.txt
=> feat: add a new randart name

crawl-ref/source/mon-info.cc
Fixes a missing space in the monster list.
=> Space for fellow slimes

crawl-ref/source/art-data.txt
It's a bit more useful, and I've adjusted the numbers slightly to fit the theme (8).
=> Tiny improvement of Oct's ring

crawl-ref/source/dat/des/branches/orc.des
=> New Orc ending

crawl-ref/source/dat/descript/es/quotes.txt, crawl-ref/source/dat/descript/quotes.txt
Altars are missing quotes, except faded altars and Quazlal's. I think this is the perfect quote for Gozag's.
References:
https://www.uco.es/~fe1rupep/4_coms/1_quev.pdf (Spanish)
https://www.spainthenandnow.com/spanish-literature/quevedo-poderoso-caballero
https://web.seducoahuila.gob.mx/biblioweb/upload/Selected%20Poetry%20of%20Francisco%20de%20Quevedo%20A%20Bilingual%20Edition.pdf
=> Quote for Gozag's altar

crawl-ref/source/dat/des/branches/temple.des
Adds several new temples, including several variable-size temples, an edit of my old great_sept temple so it has a chance to place 7 altars again, a temple where demons yell at you, and a temple featuring Lugonu's victory over the temple gods.
=> Add several new temples, add section for tiny temples

crawl-ref/source/dat/des/portals/ossuary.des
All but the outer edge of the map is silenced. Typical ossuary monster set.
=> silent ossuary map

crawl-ref/source/dat/des/builder/uniques.des
Rather than scaling with runes just do a flat 10% per pan floor in games where he spawns. Let people actually see the lad.
=> rework Ignacio spawn rate

crawl-ref/source/mon-death.cc
The power scaling was a bit too good.
=> nerf Simulacrum

crawl-ref/source/dat/des/branches/zot.des
This vault was spoilery, weird, and not very good by modern crawl standards.
=> remove grunt_zot_stairs_overgrown

crawl-ref/source/dat/des/altar/overflow.des
Teaches the player what a real friend looks like.
=> feat: new Okawaru overflow

crawl-ref/source/ability.cc
A condition was inverted.
Among other things fixes #2754
=> Fixes power leap, line pass, and shadow step

crawl-ref/source/mutation.cc
I was robbed, and want no others to suffer as I have
=> Update mutation.cc so ashenzari correctly blocks beaks

crawl-ref/source/wiz-fsim.cc
Use fake projectiles rather than whatever you're quivering (eg using your crossbow as a missile for your crossbow). Bug exists in 0.29.1 too.
=> fix fsim with ranged weapons

crawl-ref/docs/options_guide.txt
Add explore_item_greed, messaging, suppress_startup_errors, sounds_on and tc_forbidden to options_guide.txt. Also correct the spelling of trap_item_highlight.
=> Add a few missing options to options_guide.txt

crawl-ref/docs/changelog.txt, crawl-ref/docs/options_guide.txt
This may seem like a non-issue nowadays, but it is if you are playing on a smartphone.
=> Fix doc files wider than 80 characters

crawl-ref/source/cloud.cc
=> Fix cloud side effects

crawl-ref/source/god-abil.cc, crawl-ref/source/spl-damage.cc
Seeing lots of !!!!!s is fun. Let's make Grand Finale's and MCC's messages print some out for however much HP the monster you killed had.
=> Show attack strength punctuation for instakills

crawl-ref/source/version.cc
=> Add version information for Clang

crawl-ref/INSTALL.md
Credit to lukem12345.
Closes #2108
=> Fix two links in INSTALL.md

crawl-ref/source/dat/database/monspell.txt
Continuing the work of this commit: https://github.com/crawl/crawl/commit/cbcab8c68d17d1623b564816eca41d8d4ce8847d
=> Don't gender satyr spell messages

crawl-ref/source/spl-damage.cc, crawl-ref/source/zap-data.h, crawl-ref/source/zap-type.h
Pull out the lightning component to a new beam so it's not dependent on lightning bolt.
=> fix plasma beam damage

crawl-ref/source/skills.cc
A reference to [Crypt of the NecroDancer](https://en.wikipedia.org/wiki/Crypt_of_the_NecroDancer) video game
=> Added NecroDancer title

crawl-ref/source/dat/des/branches/swamp.des
Reduce cloud placements in swamp_icy and swamp_pestilence, and replace the pestilence oklob with a (much funnier) spectral bunyip.
=> Make some swamp ends less annoying

crawl-ref/source/mon-cast.cc
Reverts crawl/crawl#3247
See cacbf3a157da15eec1e600b9acd3a51729ae0e64 for reasoning.
=> Revert "fix: don't meph cloud rpois players"

crawl-ref/source/dat/des/branches/lair.des
kikubaaqudgh***a***. fbwer reported the a missing in discord
=> Correct a typo (credit to fbwer!)

crawl-ref/source/dat/database/monspeak.txt
lich -> death form. Imps can compliment the player again.
I needed to properly submit this pr since the commit title was very important
=> fix: implement a correction for imp-liments

crawl-ref/source/dat/database/monspeak.txt
Here are a few more speech lines I thought of for Donald (complaints regarding gods, especially gods he currently has few complaints about) and Crazy Yiuf (one more line of Xom-related philosophy).
=> Add more monster speech lines for Donald and Crazy Yiuf.

crawl-ref/docs/crawl_manual.rst
Felids aren't fast any more
See 406407be8511ac9846d21bd4a51990ab4ce1dbb7
=> Felid: update manual about Felids

crawl-ref/docs/crawl_manual.rst
=> Consistently capitalize Human in species descriptions in the manual.

crawl-ref/source/mon-info.cc, crawl-ref/source/mon-poly.cc, crawl-ref/source/spl-cast.cc
Polymorphing Pan lords into other monsters is still disallowed.
=> Allow polymorphing monsters into uglies.

crawl-ref/source/attack.cc
this will div_rand_round beast form slaying for accuracy displaying otherwise
=> Make the throwing slaying bonus non-random for accuracy calculation

crawl-ref/source/Crawl.xcodeproj/project.pbxproj, crawl-ref/source/MSVC/crawl.vcxproj, crawl-ref/source/MSVC/crawl.vcxproj.filters, crawl-ref/source/android-project/jni/src/Android.mk
not that they're likely to work afterward
=> fix xcode and visual studio projects

crawl-ref/source/tileweb.cc
It was displaying 4 times the corrosion for weapons
=> Bugfix corrosion display for weapons in webtiles

crawl-ref/source/player.cc
=> Let armataurs with bardings and talons kick foes

crawl-ref/source/attack.cc
There's two more in levcomp.lex.cc but I'm not brave enough to touch some 16 year old code.
=> Remove a random useless semicolon

crawl-ref/source/mon-place.cc
=> Don't let krakens into toxic bogs

crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h, crawl-ref/source/spl-util.cc, crawl-ref/source/target.cc
=> Don't leak invisible monster location with PE

crawl-ref/source/player.cc
Show player as immune to charming with clarity and polymorph when undead.
=> Show player as immune to polymorph/charming when immune

crawl-ref/source/beam.cc, crawl-ref/source/ouch.cc, crawl-ref/source/spl-cast.cc, crawl-ref/source/spl-damage.cc, crawl-ref/source/spl-damage.h
=> Display chance for wand of warping to blink

crawl-ref/source/dat/des/builder/shops.des
great addition to the collection i'd say
=> add Charlatan's Orb to shop of orbs

crawl-ref/source/dat/database/rand_wpn.txt
adds cardinal as a randart weapon name (github locked me out of my account and made me reset my password when i was creating this)
=> add cardinal

crawl-ref/source/dat/database/monspeak.txt
Another probably ancient and completely inconsequential bug
=> Make Killer Klown rare speech actually rare

crawl-ref/source/android-project/jni/src/Android.mk
=> add mon-aura.cc to Android project

crawl-ref/source/dat/database/monspeak.txt, crawl-ref/source/dat/database/montitle.txt, crawl-ref/source/dat/descript/monsters.txt
EDIT: This now applies to Terence, not Erolcha, but I can't change the title or branch name here.
=> Reflavour Erolcha.

.github/workflows/ci.yml, crawl-ref/source/android-project/app/build.gradle.in, crawl-ref/source/android-project/build.gradle, crawl-ref/source/android-project/gradle/wrapper/gradle-wrapper.properties, crawl-ref/source/android-project/jni/Application.mk
Starting August 31, new apps and app updates must target Android 14 (API level 34) to be submitted to Google Play.
https://support.google.com/googleplay/android-developer/answer/11926878
Depends on:
- https://github.com/crawl/crawl-sdl2/pull/3
- https://github.com/crawl/crawl-sdl2-image/pull/3
- https://github.com/crawl/crawl-sdl2-mixer/pull/2
=> Update Android SDK - API level 34

crawl-ref/source/dat/des/arrival/simple.des
=> Added simple arrival vault

crawl-ref/source/dat/des/builder/custombooks.des
...from Nicolae's custom books shop
=> Remove Gell's Gravitas

crawl-ref/source/artefact.h, crawl-ref/source/fixedvector.h, crawl-ref/source/newgame-def.h, crawl-ref/source/package.h, crawl-ref/source/player-equip.h
Fix all the remaining failing header tests
=> fix: failing header tests

crawl-ref/source/mon-death.cc
_make_derived_undead() now allows overriding the default success and failure messages (the "mist gathering" ones). Do this for kills using the reaping brand, so that its messages are only displayed when monsters are successfully spectralised (and visible to the player).
The failure message only applies to zero-headed hydras, which should be impossible to get with a reaping brand, but it's in place just in case a bladed weapon somehow gets both the flaming and reapling brands, or otherwise non-reapable monsters of living holiness get added.
Fixes #4251.
=> Improve reaping brand messaging.

crawl-ref/source/skills.cc
After Ogre was removed there no titles for Oni.
(I'm not an enthusiast of Japanese folklore, so can not suggest cool titles)
Also there were no Forgecraft titles, two are added for Oni
=> Add Oni's titles

crawl-ref/source/dat/database/monspeak.txt
fix the missing %%%% on line 3147 for #4334
=> Update monspeak.txt to fix  #4334

crawl-ref/source/attack.cc, crawl-ref/source/ouch.cc
I think this version has neater messaging. It does require changing the current message for cold vuln, however. Long term that might be better for simpler pattern matching? Either way, one of these two prs should be merged and the other closed.
=> Flaming/freezing warning trigger (alt #3868)

crawl-ref/source/dat/dlua/ziggurat.lua
old monster revenants are now revenant soulmongers
=> fix plain revenants spawning in zig

crawl-ref/source/fight.cc
For example if you have an allied zombie hydra and it defeats an orc challenger sent after you by Beogh, it shouldn't use its remaining attacks to attack the now friendly orc.
Partial fix of #4352
=> Make monsters stop attacking when their target becomes friendly

crawl-ref/source/dungeon.cc, crawl-ref/source/god-abil.cc, crawl-ref/source/item-prop.cc, crawl-ref/source/shopping.cc
Reduce the price of heavy armours and orbs. Increase the price of most strong
weapon types. Increase price scaling with depth, especially for consumables. 
Hoping for more interesting shop decisions later in the game; more changes 
to come but probably not in this version.
=> Adjust shop pricing

crawl-ref/source/menu.cc
When more items were added to an existing menu and then the hovered over item was updated the game would crash. This could happen when trying to add an existing macro from the macro quick add menu or when searching for a specific spell, hovering the mouse over the spell and then doing a broader search that included the spell etc.
The reason for the crash is that setting the hovered menu item was accessing some rendering related data that isn't generated until the next time we render.
Fixes #4391
=> Fix a local tiles menu crash

crawl-ref/source/beam.cc
Other ranged weapons will stop at their target if doing so will avoid hitting allies that are past their target, so damnation should to.
=> Stop at target with damnation if doing so avoids allies (Kab)

crawl-ref/source/dat/des/branches/vaults_rooms_hard.des, crawl-ref/source/dat/des/branches/vaults_rooms_standard.des
Most of them are using the themes regret-index whipped up a while back, but a few have more bespoke themes.
Edit: I'm realizing as I'm pushing this to github that we usually do one file per commit. Mea maxima culpa.
=> Add some themed little-v vaults to big-V Vaults

crawl-ref/source/dat/des/branches/lair.des
Add more decor vaults to Lair. Main themes:
- Ruined remnants of human habitation (statues, dry fountains, etc.)
- Beast attacks (blood, skeletons, etc.)
- Vegetation (trees, plants, bushes, fungi, etc.)
=> Add more decor vaults to Lair

crawl-ref/docs/crawl_manual.rst
"they can they can" -> "they can"
=> fix typo in manual

crawl-ref/source/dat/database/monspeak.txt
=> fix Wiglaf speech line (slitherrr)

crawl-ref/source/branch-data.h, crawl-ref/source/dgn-overview.cc, crawl-ref/source/dungeon.cc, crawl-ref/source/dungeon.h
Fix descent dungeon overview to match that mode's structure.
=> fix descent dungeon overview

crawl-ref/source/skills.cc
When raising all magic skills by 2 skill points, a magic skill with a target could be capped by the target to only raise by 1 skill point instead. This would happen when you had magic skills focused and a non-magic skill enabled but not focused with manual skill training and could also sometimes happen with automatic training.
Instead we should cap the skill point increase of all magic skills by which ever magic skill target would be reached first (as this target will turn off all magic skills).
=> Fix djinn training skills with targets less (cool 3)

crawl-ref/docs/crawl_manual.rst
Updates the descriptions of a few backgrounds to match changes in .33:
- Fighters now have two might potions
- Shapeshifters now have baubles
- warpers now have darts of disjunction, rather than dispersal
=> Update some background descriptions in crawl_manual.rst

crawl-ref/docs/options_guide.txt
of force_spell_targeter and force_ability_targeter defaults.
=> update options guide documentation

crawl-ref/source/xom.cc
as reported by 55-ENN in discord
=> fix: xom speech @head@ (55-ENN)

crawl-ref/source/dat/forms/bat.yaml
The generated form-data.h is identical.
=> Remove a duplicate yaml key (no functional changes)

crawl-ref/source/dat/des/variable/mini_monsters.des, crawl-ref/source/dat/descript/monsters.txt, crawl-ref/source/dat/mons/blorkula-the-orcula.yaml
=> Unify Capitalization of Blorkula the orcula
